/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createAdminUpdateDomainResponseFromDiscriminatorValue, serializeAdminUpdateDomainRequest, serializeAdminUpdateDomainResponse, type AdminUpdateDomainRequest, type AdminUpdateDomainResponse } from '../../../../../../models/admin/index.js';
// @ts-ignore
import { createErrorResponseFromDiscriminatorValue, type ErrorResponse } from '../../../../../../models/reserr/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/admin/orgs/:orgId/domains/:domain
 */
export interface DomainRequestBuilder extends BaseRequestBuilder<DomainRequestBuilder> {
    /**
     * Handles AdminUpdateDomain requests
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<AdminUpdateDomainResponse>}
     * @throws {ErrorResponse} error when the service returns a 400 status code
     * @throws {ErrorResponse} error when the service returns a 401 status code
     * @throws {ErrorResponse} error when the service returns a 500 status code
     */
     post(body: AdminUpdateDomainRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<AdminUpdateDomainResponse | undefined>;
    /**
     * Handles AdminUpdateDomain requests
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: AdminUpdateDomainRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const DomainRequestBuilderUriTemplate = "{+baseurl}/api/admin/orgs/:orgId/domains/:domain";
/**
 * Metadata for all the requests in the request builder.
 */
export const DomainRequestBuilderRequestsMetadata: RequestsMetadata = {
    post: {
        uriTemplate: DomainRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createErrorResponseFromDiscriminatorValue as ParsableFactory<Parsable>,
            401: createErrorResponseFromDiscriminatorValue as ParsableFactory<Parsable>,
            500: createErrorResponseFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createAdminUpdateDomainResponseFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeAdminUpdateDomainRequest,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
