// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package sys_admin

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
    i33b313a9f66fb27124acf027b067204a8f878cf88c95cc5ebd551e89642f948d "github.com/nbrglm/nexeres/sdks/nexeres-go/models/models"
)

type SysAdminCreateOrgRequest struct {
    // Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
    additionalData map[string]any
    // The avatarURL property
    avatarURL *string
    // The description property
    description *string
    // The name property
    name *string
    // The settings property
    settings i33b313a9f66fb27124acf027b067204a8f878cf88c95cc5ebd551e89642f948d.OrgSettingsable
    // The slug property
    slug *string
}
// NewSysAdminCreateOrgRequest instantiates a new SysAdminCreateOrgRequest and sets the default values.
func NewSysAdminCreateOrgRequest()(*SysAdminCreateOrgRequest) {
    m := &SysAdminCreateOrgRequest{
    }
    m.SetAdditionalData(make(map[string]any))
    return m
}
// CreateSysAdminCreateOrgRequestFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateSysAdminCreateOrgRequestFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewSysAdminCreateOrgRequest(), nil
}
// GetAdditionalData gets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
// returns a map[string]any when successful
func (m *SysAdminCreateOrgRequest) GetAdditionalData()(map[string]any) {
    return m.additionalData
}
// GetAvatarURL gets the avatarURL property value. The avatarURL property
// returns a *string when successful
func (m *SysAdminCreateOrgRequest) GetAvatarURL()(*string) {
    return m.avatarURL
}
// GetDescription gets the description property value. The description property
// returns a *string when successful
func (m *SysAdminCreateOrgRequest) GetDescription()(*string) {
    return m.description
}
// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error) when successful
func (m *SysAdminCreateOrgRequest) GetFieldDeserializers()(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error)) {
    res := make(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error))
    res["avatarURL"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetAvatarURL(val)
        }
        return nil
    }
    res["description"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetDescription(val)
        }
        return nil
    }
    res["name"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetName(val)
        }
        return nil
    }
    res["settings"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetObjectValue(i33b313a9f66fb27124acf027b067204a8f878cf88c95cc5ebd551e89642f948d.CreateOrgSettingsFromDiscriminatorValue)
        if err != nil {
            return err
        }
        if val != nil {
            m.SetSettings(val.(i33b313a9f66fb27124acf027b067204a8f878cf88c95cc5ebd551e89642f948d.OrgSettingsable))
        }
        return nil
    }
    res["slug"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetSlug(val)
        }
        return nil
    }
    return res
}
// GetName gets the name property value. The name property
// returns a *string when successful
func (m *SysAdminCreateOrgRequest) GetName()(*string) {
    return m.name
}
// GetSettings gets the settings property value. The settings property
// returns a OrgSettingsable when successful
func (m *SysAdminCreateOrgRequest) GetSettings()(i33b313a9f66fb27124acf027b067204a8f878cf88c95cc5ebd551e89642f948d.OrgSettingsable) {
    return m.settings
}
// GetSlug gets the slug property value. The slug property
// returns a *string when successful
func (m *SysAdminCreateOrgRequest) GetSlug()(*string) {
    return m.slug
}
// Serialize serializes information the current object
func (m *SysAdminCreateOrgRequest) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter)(error) {
    {
        err := writer.WriteStringValue("avatarURL", m.GetAvatarURL())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("description", m.GetDescription())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("name", m.GetName())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteObjectValue("settings", m.GetSettings())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("slug", m.GetSlug())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteAdditionalData(m.GetAdditionalData())
        if err != nil {
            return err
        }
    }
    return nil
}
// SetAdditionalData sets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
func (m *SysAdminCreateOrgRequest) SetAdditionalData(value map[string]any)() {
    m.additionalData = value
}
// SetAvatarURL sets the avatarURL property value. The avatarURL property
func (m *SysAdminCreateOrgRequest) SetAvatarURL(value *string)() {
    m.avatarURL = value
}
// SetDescription sets the description property value. The description property
func (m *SysAdminCreateOrgRequest) SetDescription(value *string)() {
    m.description = value
}
// SetName sets the name property value. The name property
func (m *SysAdminCreateOrgRequest) SetName(value *string)() {
    m.name = value
}
// SetSettings sets the settings property value. The settings property
func (m *SysAdminCreateOrgRequest) SetSettings(value i33b313a9f66fb27124acf027b067204a8f878cf88c95cc5ebd551e89642f948d.OrgSettingsable)() {
    m.settings = value
}
// SetSlug sets the slug property value. The slug property
func (m *SysAdminCreateOrgRequest) SetSlug(value *string)() {
    m.slug = value
}
type SysAdminCreateOrgRequestable interface {
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.AdditionalDataHolder
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    GetAvatarURL()(*string)
    GetDescription()(*string)
    GetName()(*string)
    GetSettings()(i33b313a9f66fb27124acf027b067204a8f878cf88c95cc5ebd551e89642f948d.OrgSettingsable)
    GetSlug()(*string)
    SetAvatarURL(value *string)()
    SetDescription(value *string)()
    SetName(value *string)()
    SetSettings(value i33b313a9f66fb27124acf027b067204a8f878cf88c95cc5ebd551e89642f948d.OrgSettingsable)()
    SetSlug(value *string)()
}
