// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package sys_admin

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
    ic7d34f839369ab91a5311ee5a6ae5e652b971dc81e681d8e5685de282a1af791 "github.com/nbrglm/nexeres/sdks/nexeres-go/models/resquery"
)

type SysAdminListOrgsRequest struct {
    // Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
    additionalData map[string]any
    // The filters property
    filters ic7d34f839369ab91a5311ee5a6ae5e652b971dc81e681d8e5685de282a1af791.QueryFiltersable
    // The pagination property
    pagination ic7d34f839369ab91a5311ee5a6ae5e652b971dc81e681d8e5685de282a1af791.QueryPaginationable
    // The sort property
    sort []ic7d34f839369ab91a5311ee5a6ae5e652b971dc81e681d8e5685de282a1af791.SortOptionable
}
// NewSysAdminListOrgsRequest instantiates a new SysAdminListOrgsRequest and sets the default values.
func NewSysAdminListOrgsRequest()(*SysAdminListOrgsRequest) {
    m := &SysAdminListOrgsRequest{
    }
    m.SetAdditionalData(make(map[string]any))
    return m
}
// CreateSysAdminListOrgsRequestFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateSysAdminListOrgsRequestFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewSysAdminListOrgsRequest(), nil
}
// GetAdditionalData gets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
// returns a map[string]any when successful
func (m *SysAdminListOrgsRequest) GetAdditionalData()(map[string]any) {
    return m.additionalData
}
// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error) when successful
func (m *SysAdminListOrgsRequest) GetFieldDeserializers()(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error)) {
    res := make(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error))
    res["filters"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetObjectValue(ic7d34f839369ab91a5311ee5a6ae5e652b971dc81e681d8e5685de282a1af791.CreateQueryFiltersFromDiscriminatorValue)
        if err != nil {
            return err
        }
        if val != nil {
            m.SetFilters(val.(ic7d34f839369ab91a5311ee5a6ae5e652b971dc81e681d8e5685de282a1af791.QueryFiltersable))
        }
        return nil
    }
    res["pagination"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetObjectValue(ic7d34f839369ab91a5311ee5a6ae5e652b971dc81e681d8e5685de282a1af791.CreateQueryPaginationFromDiscriminatorValue)
        if err != nil {
            return err
        }
        if val != nil {
            m.SetPagination(val.(ic7d34f839369ab91a5311ee5a6ae5e652b971dc81e681d8e5685de282a1af791.QueryPaginationable))
        }
        return nil
    }
    res["sort"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetCollectionOfObjectValues(ic7d34f839369ab91a5311ee5a6ae5e652b971dc81e681d8e5685de282a1af791.CreateSortOptionFromDiscriminatorValue)
        if err != nil {
            return err
        }
        if val != nil {
            res := make([]ic7d34f839369ab91a5311ee5a6ae5e652b971dc81e681d8e5685de282a1af791.SortOptionable, len(val))
            for i, v := range val {
                if v != nil {
                    res[i] = v.(ic7d34f839369ab91a5311ee5a6ae5e652b971dc81e681d8e5685de282a1af791.SortOptionable)
                }
            }
            m.SetSort(res)
        }
        return nil
    }
    return res
}
// GetFilters gets the filters property value. The filters property
// returns a QueryFiltersable when successful
func (m *SysAdminListOrgsRequest) GetFilters()(ic7d34f839369ab91a5311ee5a6ae5e652b971dc81e681d8e5685de282a1af791.QueryFiltersable) {
    return m.filters
}
// GetPagination gets the pagination property value. The pagination property
// returns a QueryPaginationable when successful
func (m *SysAdminListOrgsRequest) GetPagination()(ic7d34f839369ab91a5311ee5a6ae5e652b971dc81e681d8e5685de282a1af791.QueryPaginationable) {
    return m.pagination
}
// GetSort gets the sort property value. The sort property
// returns a []SortOptionable when successful
func (m *SysAdminListOrgsRequest) GetSort()([]ic7d34f839369ab91a5311ee5a6ae5e652b971dc81e681d8e5685de282a1af791.SortOptionable) {
    return m.sort
}
// Serialize serializes information the current object
func (m *SysAdminListOrgsRequest) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter)(error) {
    {
        err := writer.WriteObjectValue("filters", m.GetFilters())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteObjectValue("pagination", m.GetPagination())
        if err != nil {
            return err
        }
    }
    if m.GetSort() != nil {
        cast := make([]i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, len(m.GetSort()))
        for i, v := range m.GetSort() {
            if v != nil {
                cast[i] = v.(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable)
            }
        }
        err := writer.WriteCollectionOfObjectValues("sort", cast)
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteAdditionalData(m.GetAdditionalData())
        if err != nil {
            return err
        }
    }
    return nil
}
// SetAdditionalData sets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
func (m *SysAdminListOrgsRequest) SetAdditionalData(value map[string]any)() {
    m.additionalData = value
}
// SetFilters sets the filters property value. The filters property
func (m *SysAdminListOrgsRequest) SetFilters(value ic7d34f839369ab91a5311ee5a6ae5e652b971dc81e681d8e5685de282a1af791.QueryFiltersable)() {
    m.filters = value
}
// SetPagination sets the pagination property value. The pagination property
func (m *SysAdminListOrgsRequest) SetPagination(value ic7d34f839369ab91a5311ee5a6ae5e652b971dc81e681d8e5685de282a1af791.QueryPaginationable)() {
    m.pagination = value
}
// SetSort sets the sort property value. The sort property
func (m *SysAdminListOrgsRequest) SetSort(value []ic7d34f839369ab91a5311ee5a6ae5e652b971dc81e681d8e5685de282a1af791.SortOptionable)() {
    m.sort = value
}
type SysAdminListOrgsRequestable interface {
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.AdditionalDataHolder
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    GetFilters()(ic7d34f839369ab91a5311ee5a6ae5e652b971dc81e681d8e5685de282a1af791.QueryFiltersable)
    GetPagination()(ic7d34f839369ab91a5311ee5a6ae5e652b971dc81e681d8e5685de282a1af791.QueryPaginationable)
    GetSort()([]ic7d34f839369ab91a5311ee5a6ae5e652b971dc81e681d8e5685de282a1af791.SortOptionable)
    SetFilters(value ic7d34f839369ab91a5311ee5a6ae5e652b971dc81e681d8e5685de282a1af791.QueryFiltersable)()
    SetPagination(value ic7d34f839369ab91a5311ee5a6ae5e652b971dc81e681d8e5685de282a1af791.QueryPaginationable)()
    SetSort(value []ic7d34f839369ab91a5311ee5a6ae5e652b971dc81e681d8e5685de282a1af791.SortOptionable)()
}
