// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package models

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

type AdminCreateDomainResponse struct {
    // The domain property
    domain Domainable
    // Response message.
    message *string
    // Indicates if the request was successful.
    success *bool
}
// NewAdminCreateDomainResponse instantiates a new AdminCreateDomainResponse and sets the default values.
func NewAdminCreateDomainResponse()(*AdminCreateDomainResponse) {
    m := &AdminCreateDomainResponse{
    }
    return m
}
// CreateAdminCreateDomainResponseFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateAdminCreateDomainResponseFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewAdminCreateDomainResponse(), nil
}
// GetDomain gets the domain property value. The domain property
// returns a Domainable when successful
func (m *AdminCreateDomainResponse) GetDomain()(Domainable) {
    return m.domain
}
// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error) when successful
func (m *AdminCreateDomainResponse) GetFieldDeserializers()(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error)) {
    res := make(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error))
    res["domain"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetObjectValue(CreateDomainFromDiscriminatorValue)
        if err != nil {
            return err
        }
        if val != nil {
            m.SetDomain(val.(Domainable))
        }
        return nil
    }
    res["message"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetMessage(val)
        }
        return nil
    }
    res["success"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetBoolValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetSuccess(val)
        }
        return nil
    }
    return res
}
// GetMessage gets the message property value. Response message.
// returns a *string when successful
func (m *AdminCreateDomainResponse) GetMessage()(*string) {
    return m.message
}
// GetSuccess gets the success property value. Indicates if the request was successful.
// returns a *bool when successful
func (m *AdminCreateDomainResponse) GetSuccess()(*bool) {
    return m.success
}
// Serialize serializes information the current object
func (m *AdminCreateDomainResponse) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter)(error) {
    {
        err := writer.WriteObjectValue("domain", m.GetDomain())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("message", m.GetMessage())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteBoolValue("success", m.GetSuccess())
        if err != nil {
            return err
        }
    }
    return nil
}
// SetDomain sets the domain property value. The domain property
func (m *AdminCreateDomainResponse) SetDomain(value Domainable)() {
    m.domain = value
}
// SetMessage sets the message property value. Response message.
func (m *AdminCreateDomainResponse) SetMessage(value *string)() {
    m.message = value
}
// SetSuccess sets the success property value. Indicates if the request was successful.
func (m *AdminCreateDomainResponse) SetSuccess(value *bool)() {
    m.success = value
}
type AdminCreateDomainResponseable interface {
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    GetDomain()(Domainable)
    GetMessage()(*string)
    GetSuccess()(*bool)
    SetDomain(value Domainable)()
    SetMessage(value *string)()
    SetSuccess(value *bool)()
}
