// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package models

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

type AdminGetDomainVerificationCodeResponse struct {
    // Response message.
    message *string
    // Indicates if the request was successful.
    success *bool
    // Domain verification code.
    verificationCode *string
}
// NewAdminGetDomainVerificationCodeResponse instantiates a new AdminGetDomainVerificationCodeResponse and sets the default values.
func NewAdminGetDomainVerificationCodeResponse()(*AdminGetDomainVerificationCodeResponse) {
    m := &AdminGetDomainVerificationCodeResponse{
    }
    return m
}
// CreateAdminGetDomainVerificationCodeResponseFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateAdminGetDomainVerificationCodeResponseFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewAdminGetDomainVerificationCodeResponse(), nil
}
// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error) when successful
func (m *AdminGetDomainVerificationCodeResponse) GetFieldDeserializers()(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error)) {
    res := make(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error))
    res["message"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetMessage(val)
        }
        return nil
    }
    res["success"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetBoolValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetSuccess(val)
        }
        return nil
    }
    res["verificationCode"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetVerificationCode(val)
        }
        return nil
    }
    return res
}
// GetMessage gets the message property value. Response message.
// returns a *string when successful
func (m *AdminGetDomainVerificationCodeResponse) GetMessage()(*string) {
    return m.message
}
// GetSuccess gets the success property value. Indicates if the request was successful.
// returns a *bool when successful
func (m *AdminGetDomainVerificationCodeResponse) GetSuccess()(*bool) {
    return m.success
}
// GetVerificationCode gets the verificationCode property value. Domain verification code.
// returns a *string when successful
func (m *AdminGetDomainVerificationCodeResponse) GetVerificationCode()(*string) {
    return m.verificationCode
}
// Serialize serializes information the current object
func (m *AdminGetDomainVerificationCodeResponse) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter)(error) {
    {
        err := writer.WriteStringValue("message", m.GetMessage())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteBoolValue("success", m.GetSuccess())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("verificationCode", m.GetVerificationCode())
        if err != nil {
            return err
        }
    }
    return nil
}
// SetMessage sets the message property value. Response message.
func (m *AdminGetDomainVerificationCodeResponse) SetMessage(value *string)() {
    m.message = value
}
// SetSuccess sets the success property value. Indicates if the request was successful.
func (m *AdminGetDomainVerificationCodeResponse) SetSuccess(value *bool)() {
    m.success = value
}
// SetVerificationCode sets the verificationCode property value. Domain verification code.
func (m *AdminGetDomainVerificationCodeResponse) SetVerificationCode(value *string)() {
    m.verificationCode = value
}
type AdminGetDomainVerificationCodeResponseable interface {
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    GetMessage()(*string)
    GetSuccess()(*bool)
    GetVerificationCode()(*string)
    SetMessage(value *string)()
    SetSuccess(value *bool)()
    SetVerificationCode(value *string)()
}
