// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package models

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

type AdminCreateRoleResponse struct {
    // Response message.
    message *string
    // The role property
    role Roleable
    // Indicates if the request was successful.
    success *bool
}
// NewAdminCreateRoleResponse instantiates a new AdminCreateRoleResponse and sets the default values.
func NewAdminCreateRoleResponse()(*AdminCreateRoleResponse) {
    m := &AdminCreateRoleResponse{
    }
    return m
}
// CreateAdminCreateRoleResponseFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateAdminCreateRoleResponseFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewAdminCreateRoleResponse(), nil
}
// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error) when successful
func (m *AdminCreateRoleResponse) GetFieldDeserializers()(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error)) {
    res := make(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error))
    res["message"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetMessage(val)
        }
        return nil
    }
    res["role"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetObjectValue(CreateRoleFromDiscriminatorValue)
        if err != nil {
            return err
        }
        if val != nil {
            m.SetRole(val.(Roleable))
        }
        return nil
    }
    res["success"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetBoolValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetSuccess(val)
        }
        return nil
    }
    return res
}
// GetMessage gets the message property value. Response message.
// returns a *string when successful
func (m *AdminCreateRoleResponse) GetMessage()(*string) {
    return m.message
}
// GetRole gets the role property value. The role property
// returns a Roleable when successful
func (m *AdminCreateRoleResponse) GetRole()(Roleable) {
    return m.role
}
// GetSuccess gets the success property value. Indicates if the request was successful.
// returns a *bool when successful
func (m *AdminCreateRoleResponse) GetSuccess()(*bool) {
    return m.success
}
// Serialize serializes information the current object
func (m *AdminCreateRoleResponse) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter)(error) {
    {
        err := writer.WriteStringValue("message", m.GetMessage())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteObjectValue("role", m.GetRole())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteBoolValue("success", m.GetSuccess())
        if err != nil {
            return err
        }
    }
    return nil
}
// SetMessage sets the message property value. Response message.
func (m *AdminCreateRoleResponse) SetMessage(value *string)() {
    m.message = value
}
// SetRole sets the role property value. The role property
func (m *AdminCreateRoleResponse) SetRole(value Roleable)() {
    m.role = value
}
// SetSuccess sets the success property value. Indicates if the request was successful.
func (m *AdminCreateRoleResponse) SetSuccess(value *bool)() {
    m.success = value
}
type AdminCreateRoleResponseable interface {
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    GetMessage()(*string)
    GetRole()(Roleable)
    GetSuccess()(*bool)
    SetMessage(value *string)()
    SetRole(value Roleable)()
    SetSuccess(value *bool)()
}
