// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package models

import (
    i561e97a8befe7661a44c8f54600992b4207a3a0cf6770e5559949bc276de2e22 "github.com/google/uuid"
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

type AdminUpdateDomainRequest struct {
    // Whether users from this domain can auto-join the organization.
    autoJoin *bool
    // Role ID to assign to users who auto-join via this domain.
    autoJoinRoleId *i561e97a8befe7661a44c8f54600992b4207a3a0cf6770e5559949bc276de2e22.UUID
    // Role name corresponding to the Role ID.
    autoJoinRoleName *string
}
// NewAdminUpdateDomainRequest instantiates a new AdminUpdateDomainRequest and sets the default values.
func NewAdminUpdateDomainRequest()(*AdminUpdateDomainRequest) {
    m := &AdminUpdateDomainRequest{
    }
    return m
}
// CreateAdminUpdateDomainRequestFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateAdminUpdateDomainRequestFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewAdminUpdateDomainRequest(), nil
}
// GetAutoJoin gets the autoJoin property value. Whether users from this domain can auto-join the organization.
// returns a *bool when successful
func (m *AdminUpdateDomainRequest) GetAutoJoin()(*bool) {
    return m.autoJoin
}
// GetAutoJoinRoleId gets the autoJoinRoleId property value. Role ID to assign to users who auto-join via this domain.
// returns a *UUID when successful
func (m *AdminUpdateDomainRequest) GetAutoJoinRoleId()(*i561e97a8befe7661a44c8f54600992b4207a3a0cf6770e5559949bc276de2e22.UUID) {
    return m.autoJoinRoleId
}
// GetAutoJoinRoleName gets the autoJoinRoleName property value. Role name corresponding to the Role ID.
// returns a *string when successful
func (m *AdminUpdateDomainRequest) GetAutoJoinRoleName()(*string) {
    return m.autoJoinRoleName
}
// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error) when successful
func (m *AdminUpdateDomainRequest) GetFieldDeserializers()(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error)) {
    res := make(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error))
    res["autoJoin"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetBoolValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetAutoJoin(val)
        }
        return nil
    }
    res["autoJoinRoleId"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetUUIDValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetAutoJoinRoleId(val)
        }
        return nil
    }
    res["autoJoinRoleName"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetAutoJoinRoleName(val)
        }
        return nil
    }
    return res
}
// Serialize serializes information the current object
func (m *AdminUpdateDomainRequest) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter)(error) {
    {
        err := writer.WriteBoolValue("autoJoin", m.GetAutoJoin())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteUUIDValue("autoJoinRoleId", m.GetAutoJoinRoleId())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("autoJoinRoleName", m.GetAutoJoinRoleName())
        if err != nil {
            return err
        }
    }
    return nil
}
// SetAutoJoin sets the autoJoin property value. Whether users from this domain can auto-join the organization.
func (m *AdminUpdateDomainRequest) SetAutoJoin(value *bool)() {
    m.autoJoin = value
}
// SetAutoJoinRoleId sets the autoJoinRoleId property value. Role ID to assign to users who auto-join via this domain.
func (m *AdminUpdateDomainRequest) SetAutoJoinRoleId(value *i561e97a8befe7661a44c8f54600992b4207a3a0cf6770e5559949bc276de2e22.UUID)() {
    m.autoJoinRoleId = value
}
// SetAutoJoinRoleName sets the autoJoinRoleName property value. Role name corresponding to the Role ID.
func (m *AdminUpdateDomainRequest) SetAutoJoinRoleName(value *string)() {
    m.autoJoinRoleName = value
}
type AdminUpdateDomainRequestable interface {
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    GetAutoJoin()(*bool)
    GetAutoJoinRoleId()(*i561e97a8befe7661a44c8f54600992b4207a3a0cf6770e5559949bc276de2e22.UUID)
    GetAutoJoinRoleName()(*string)
    SetAutoJoin(value *bool)()
    SetAutoJoinRoleId(value *i561e97a8befe7661a44c8f54600992b4207a3a0cf6770e5559949bc276de2e22.UUID)()
    SetAutoJoinRoleName(value *string)()
}
