// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package models

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

type AuthSignupRequest struct {
    // Confirmation of the user's desired password.
    confirmPassword *string
    // User's email address.
    email *string
    // Invitation token for joining an organization (if applicable).
    inviteToken *string
    // User's full name.
    name *string
    // User's desired password.
    password *string
}
// NewAuthSignupRequest instantiates a new AuthSignupRequest and sets the default values.
func NewAuthSignupRequest()(*AuthSignupRequest) {
    m := &AuthSignupRequest{
    }
    return m
}
// CreateAuthSignupRequestFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateAuthSignupRequestFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewAuthSignupRequest(), nil
}
// GetConfirmPassword gets the confirmPassword property value. Confirmation of the user's desired password.
// returns a *string when successful
func (m *AuthSignupRequest) GetConfirmPassword()(*string) {
    return m.confirmPassword
}
// GetEmail gets the email property value. User's email address.
// returns a *string when successful
func (m *AuthSignupRequest) GetEmail()(*string) {
    return m.email
}
// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error) when successful
func (m *AuthSignupRequest) GetFieldDeserializers()(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error)) {
    res := make(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error))
    res["confirmPassword"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetConfirmPassword(val)
        }
        return nil
    }
    res["email"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetEmail(val)
        }
        return nil
    }
    res["inviteToken"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetInviteToken(val)
        }
        return nil
    }
    res["name"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetName(val)
        }
        return nil
    }
    res["password"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetPassword(val)
        }
        return nil
    }
    return res
}
// GetInviteToken gets the inviteToken property value. Invitation token for joining an organization (if applicable).
// returns a *string when successful
func (m *AuthSignupRequest) GetInviteToken()(*string) {
    return m.inviteToken
}
// GetName gets the name property value. User's full name.
// returns a *string when successful
func (m *AuthSignupRequest) GetName()(*string) {
    return m.name
}
// GetPassword gets the password property value. User's desired password.
// returns a *string when successful
func (m *AuthSignupRequest) GetPassword()(*string) {
    return m.password
}
// Serialize serializes information the current object
func (m *AuthSignupRequest) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter)(error) {
    {
        err := writer.WriteStringValue("confirmPassword", m.GetConfirmPassword())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("email", m.GetEmail())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("inviteToken", m.GetInviteToken())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("name", m.GetName())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("password", m.GetPassword())
        if err != nil {
            return err
        }
    }
    return nil
}
// SetConfirmPassword sets the confirmPassword property value. Confirmation of the user's desired password.
func (m *AuthSignupRequest) SetConfirmPassword(value *string)() {
    m.confirmPassword = value
}
// SetEmail sets the email property value. User's email address.
func (m *AuthSignupRequest) SetEmail(value *string)() {
    m.email = value
}
// SetInviteToken sets the inviteToken property value. Invitation token for joining an organization (if applicable).
func (m *AuthSignupRequest) SetInviteToken(value *string)() {
    m.inviteToken = value
}
// SetName sets the name property value. User's full name.
func (m *AuthSignupRequest) SetName(value *string)() {
    m.name = value
}
// SetPassword sets the password property value. User's desired password.
func (m *AuthSignupRequest) SetPassword(value *string)() {
    m.password = value
}
type AuthSignupRequestable interface {
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    GetConfirmPassword()(*string)
    GetEmail()(*string)
    GetInviteToken()(*string)
    GetName()(*string)
    GetPassword()(*string)
    SetConfirmPassword(value *string)()
    SetEmail(value *string)()
    SetInviteToken(value *string)()
    SetName(value *string)()
    SetPassword(value *string)()
}
