// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package models

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

type AuthRefreshResponse struct {
    // Response message.
    message *string
    // Indicates if the request was successful.
    success *bool
    // The tokens property
    tokens AuthTokensable
}
// NewAuthRefreshResponse instantiates a new AuthRefreshResponse and sets the default values.
func NewAuthRefreshResponse()(*AuthRefreshResponse) {
    m := &AuthRefreshResponse{
    }
    return m
}
// CreateAuthRefreshResponseFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateAuthRefreshResponseFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewAuthRefreshResponse(), nil
}
// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error) when successful
func (m *AuthRefreshResponse) GetFieldDeserializers()(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error)) {
    res := make(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error))
    res["message"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetMessage(val)
        }
        return nil
    }
    res["success"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetBoolValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetSuccess(val)
        }
        return nil
    }
    res["tokens"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetObjectValue(CreateAuthTokensFromDiscriminatorValue)
        if err != nil {
            return err
        }
        if val != nil {
            m.SetTokens(val.(AuthTokensable))
        }
        return nil
    }
    return res
}
// GetMessage gets the message property value. Response message.
// returns a *string when successful
func (m *AuthRefreshResponse) GetMessage()(*string) {
    return m.message
}
// GetSuccess gets the success property value. Indicates if the request was successful.
// returns a *bool when successful
func (m *AuthRefreshResponse) GetSuccess()(*bool) {
    return m.success
}
// GetTokens gets the tokens property value. The tokens property
// returns a AuthTokensable when successful
func (m *AuthRefreshResponse) GetTokens()(AuthTokensable) {
    return m.tokens
}
// Serialize serializes information the current object
func (m *AuthRefreshResponse) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter)(error) {
    {
        err := writer.WriteStringValue("message", m.GetMessage())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteBoolValue("success", m.GetSuccess())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteObjectValue("tokens", m.GetTokens())
        if err != nil {
            return err
        }
    }
    return nil
}
// SetMessage sets the message property value. Response message.
func (m *AuthRefreshResponse) SetMessage(value *string)() {
    m.message = value
}
// SetSuccess sets the success property value. Indicates if the request was successful.
func (m *AuthRefreshResponse) SetSuccess(value *bool)() {
    m.success = value
}
// SetTokens sets the tokens property value. The tokens property
func (m *AuthRefreshResponse) SetTokens(value AuthTokensable)() {
    m.tokens = value
}
type AuthRefreshResponseable interface {
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    GetMessage()(*string)
    GetSuccess()(*bool)
    GetTokens()(AuthTokensable)
    SetMessage(value *string)()
    SetSuccess(value *bool)()
    SetTokens(value AuthTokensable)()
}
