// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package models

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

type AuthLogoutRequest struct {
    // Refresh token of the user to be logged out.
    refreshToken *string
    // Session token of the user to be logged out.
    sessionToken *string
}
// NewAuthLogoutRequest instantiates a new AuthLogoutRequest and sets the default values.
func NewAuthLogoutRequest()(*AuthLogoutRequest) {
    m := &AuthLogoutRequest{
    }
    return m
}
// CreateAuthLogoutRequestFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateAuthLogoutRequestFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewAuthLogoutRequest(), nil
}
// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error) when successful
func (m *AuthLogoutRequest) GetFieldDeserializers()(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error)) {
    res := make(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error))
    res["refreshToken"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetRefreshToken(val)
        }
        return nil
    }
    res["sessionToken"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetSessionToken(val)
        }
        return nil
    }
    return res
}
// GetRefreshToken gets the refreshToken property value. Refresh token of the user to be logged out.
// returns a *string when successful
func (m *AuthLogoutRequest) GetRefreshToken()(*string) {
    return m.refreshToken
}
// GetSessionToken gets the sessionToken property value. Session token of the user to be logged out.
// returns a *string when successful
func (m *AuthLogoutRequest) GetSessionToken()(*string) {
    return m.sessionToken
}
// Serialize serializes information the current object
func (m *AuthLogoutRequest) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter)(error) {
    {
        err := writer.WriteStringValue("refreshToken", m.GetRefreshToken())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("sessionToken", m.GetSessionToken())
        if err != nil {
            return err
        }
    }
    return nil
}
// SetRefreshToken sets the refreshToken property value. Refresh token of the user to be logged out.
func (m *AuthLogoutRequest) SetRefreshToken(value *string)() {
    m.refreshToken = value
}
// SetSessionToken sets the sessionToken property value. Session token of the user to be logged out.
func (m *AuthLogoutRequest) SetSessionToken(value *string)() {
    m.sessionToken = value
}
type AuthLogoutRequestable interface {
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    GetRefreshToken()(*string)
    GetSessionToken()(*string)
    SetRefreshToken(value *string)()
    SetSessionToken(value *string)()
}
