// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package models
// Type of authentication flow (e.g., login, change-password).
type AuthFlow_type int

const (
    LOGIN_AUTHFLOW_TYPE AuthFlow_type = iota
    CHANGEPASSWORD_AUTHFLOW_TYPE
)

func (i AuthFlow_type) String() string {
    return []string{"login", "change-password"}[i]
}
func ParseAuthFlow_type(v string) (any, error) {
    result := LOGIN_AUTHFLOW_TYPE
    switch v {
        case "login":
            result = LOGIN_AUTHFLOW_TYPE
        case "change-password":
            result = CHANGEPASSWORD_AUTHFLOW_TYPE
        default:
            return nil, nil
    }
    return &result, nil
}
func SerializeAuthFlow_type(values []AuthFlow_type) []string {
    result := make([]string, len(values))
    for i, v := range values {
        result[i] = v.String()
    }
    return result
}
func (i AuthFlow_type) isMultiValue() bool {
    return false
}
