// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package models

import (
    i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e "time"
    i561e97a8befe7661a44c8f54600992b4207a3a0cf6770e5559949bc276de2e22 "github.com/google/uuid"
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

type AuthFlow struct {
    // Timestamp when the flow was created.
    createdAt *i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time
    // Email associated with the authentication flow.
    email *string
    // Timestamp when the flow expires.
    expiresAt *i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time
    // Unique identifier for the authentication flow.
    id *i561e97a8befe7661a44c8f54600992b4207a3a0cf6770e5559949bc276de2e22.UUID
    // Indicates if MFA is required for this flow.
    mfaRequired *bool
    // Indicates if MFA has been verified in this flow.
    mfaVerified *bool
    // List of organization IDs associated with the flow, if applicable. Mostly used to handle multi-tenant login.
    orgs []Orgable
    // URL to redirect after flow completion.
    returnTo *string
    // Type of authentication flow (e.g., login, change-password).
    typeEscaped *AuthFlow_type
    // User ID associated with the flow, if applicable.
    userId *i561e97a8befe7661a44c8f54600992b4207a3a0cf6770e5559949bc276de2e22.UUID
}
// NewAuthFlow instantiates a new AuthFlow and sets the default values.
func NewAuthFlow()(*AuthFlow) {
    m := &AuthFlow{
    }
    return m
}
// CreateAuthFlowFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateAuthFlowFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewAuthFlow(), nil
}
// GetCreatedAt gets the createdAt property value. Timestamp when the flow was created.
// returns a *Time when successful
func (m *AuthFlow) GetCreatedAt()(*i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time) {
    return m.createdAt
}
// GetEmail gets the email property value. Email associated with the authentication flow.
// returns a *string when successful
func (m *AuthFlow) GetEmail()(*string) {
    return m.email
}
// GetExpiresAt gets the expiresAt property value. Timestamp when the flow expires.
// returns a *Time when successful
func (m *AuthFlow) GetExpiresAt()(*i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time) {
    return m.expiresAt
}
// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error) when successful
func (m *AuthFlow) GetFieldDeserializers()(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error)) {
    res := make(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error))
    res["createdAt"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetTimeValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetCreatedAt(val)
        }
        return nil
    }
    res["email"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetEmail(val)
        }
        return nil
    }
    res["expiresAt"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetTimeValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetExpiresAt(val)
        }
        return nil
    }
    res["id"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetUUIDValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetId(val)
        }
        return nil
    }
    res["mfaRequired"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetBoolValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetMfaRequired(val)
        }
        return nil
    }
    res["mfaVerified"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetBoolValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetMfaVerified(val)
        }
        return nil
    }
    res["orgs"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetCollectionOfObjectValues(CreateOrgFromDiscriminatorValue)
        if err != nil {
            return err
        }
        if val != nil {
            res := make([]Orgable, len(val))
            for i, v := range val {
                if v != nil {
                    res[i] = v.(Orgable)
                }
            }
            m.SetOrgs(res)
        }
        return nil
    }
    res["returnTo"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetReturnTo(val)
        }
        return nil
    }
    res["type"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetEnumValue(ParseAuthFlow_type)
        if err != nil {
            return err
        }
        if val != nil {
            m.SetTypeEscaped(val.(*AuthFlow_type))
        }
        return nil
    }
    res["userId"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetUUIDValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetUserId(val)
        }
        return nil
    }
    return res
}
// GetId gets the id property value. Unique identifier for the authentication flow.
// returns a *UUID when successful
func (m *AuthFlow) GetId()(*i561e97a8befe7661a44c8f54600992b4207a3a0cf6770e5559949bc276de2e22.UUID) {
    return m.id
}
// GetMfaRequired gets the mfaRequired property value. Indicates if MFA is required for this flow.
// returns a *bool when successful
func (m *AuthFlow) GetMfaRequired()(*bool) {
    return m.mfaRequired
}
// GetMfaVerified gets the mfaVerified property value. Indicates if MFA has been verified in this flow.
// returns a *bool when successful
func (m *AuthFlow) GetMfaVerified()(*bool) {
    return m.mfaVerified
}
// GetOrgs gets the orgs property value. List of organization IDs associated with the flow, if applicable. Mostly used to handle multi-tenant login.
// returns a []Orgable when successful
func (m *AuthFlow) GetOrgs()([]Orgable) {
    return m.orgs
}
// GetReturnTo gets the returnTo property value. URL to redirect after flow completion.
// returns a *string when successful
func (m *AuthFlow) GetReturnTo()(*string) {
    return m.returnTo
}
// GetTypeEscaped gets the type property value. Type of authentication flow (e.g., login, change-password).
// returns a *AuthFlow_type when successful
func (m *AuthFlow) GetTypeEscaped()(*AuthFlow_type) {
    return m.typeEscaped
}
// GetUserId gets the userId property value. User ID associated with the flow, if applicable.
// returns a *UUID when successful
func (m *AuthFlow) GetUserId()(*i561e97a8befe7661a44c8f54600992b4207a3a0cf6770e5559949bc276de2e22.UUID) {
    return m.userId
}
// Serialize serializes information the current object
func (m *AuthFlow) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter)(error) {
    {
        err := writer.WriteTimeValue("createdAt", m.GetCreatedAt())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("email", m.GetEmail())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteTimeValue("expiresAt", m.GetExpiresAt())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteUUIDValue("id", m.GetId())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteBoolValue("mfaRequired", m.GetMfaRequired())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteBoolValue("mfaVerified", m.GetMfaVerified())
        if err != nil {
            return err
        }
    }
    if m.GetOrgs() != nil {
        cast := make([]i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, len(m.GetOrgs()))
        for i, v := range m.GetOrgs() {
            if v != nil {
                cast[i] = v.(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable)
            }
        }
        err := writer.WriteCollectionOfObjectValues("orgs", cast)
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("returnTo", m.GetReturnTo())
        if err != nil {
            return err
        }
    }
    if m.GetTypeEscaped() != nil {
        cast := (*m.GetTypeEscaped()).String()
        err := writer.WriteStringValue("type", &cast)
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteUUIDValue("userId", m.GetUserId())
        if err != nil {
            return err
        }
    }
    return nil
}
// SetCreatedAt sets the createdAt property value. Timestamp when the flow was created.
func (m *AuthFlow) SetCreatedAt(value *i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time)() {
    m.createdAt = value
}
// SetEmail sets the email property value. Email associated with the authentication flow.
func (m *AuthFlow) SetEmail(value *string)() {
    m.email = value
}
// SetExpiresAt sets the expiresAt property value. Timestamp when the flow expires.
func (m *AuthFlow) SetExpiresAt(value *i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time)() {
    m.expiresAt = value
}
// SetId sets the id property value. Unique identifier for the authentication flow.
func (m *AuthFlow) SetId(value *i561e97a8befe7661a44c8f54600992b4207a3a0cf6770e5559949bc276de2e22.UUID)() {
    m.id = value
}
// SetMfaRequired sets the mfaRequired property value. Indicates if MFA is required for this flow.
func (m *AuthFlow) SetMfaRequired(value *bool)() {
    m.mfaRequired = value
}
// SetMfaVerified sets the mfaVerified property value. Indicates if MFA has been verified in this flow.
func (m *AuthFlow) SetMfaVerified(value *bool)() {
    m.mfaVerified = value
}
// SetOrgs sets the orgs property value. List of organization IDs associated with the flow, if applicable. Mostly used to handle multi-tenant login.
func (m *AuthFlow) SetOrgs(value []Orgable)() {
    m.orgs = value
}
// SetReturnTo sets the returnTo property value. URL to redirect after flow completion.
func (m *AuthFlow) SetReturnTo(value *string)() {
    m.returnTo = value
}
// SetTypeEscaped sets the type property value. Type of authentication flow (e.g., login, change-password).
func (m *AuthFlow) SetTypeEscaped(value *AuthFlow_type)() {
    m.typeEscaped = value
}
// SetUserId sets the userId property value. User ID associated with the flow, if applicable.
func (m *AuthFlow) SetUserId(value *i561e97a8befe7661a44c8f54600992b4207a3a0cf6770e5559949bc276de2e22.UUID)() {
    m.userId = value
}
type AuthFlowable interface {
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    GetCreatedAt()(*i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time)
    GetEmail()(*string)
    GetExpiresAt()(*i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time)
    GetId()(*i561e97a8befe7661a44c8f54600992b4207a3a0cf6770e5559949bc276de2e22.UUID)
    GetMfaRequired()(*bool)
    GetMfaVerified()(*bool)
    GetOrgs()([]Orgable)
    GetReturnTo()(*string)
    GetTypeEscaped()(*AuthFlow_type)
    GetUserId()(*i561e97a8befe7661a44c8f54600992b4207a3a0cf6770e5559949bc276de2e22.UUID)
    SetCreatedAt(value *i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time)()
    SetEmail(value *string)()
    SetExpiresAt(value *i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time)()
    SetId(value *i561e97a8befe7661a44c8f54600992b4207a3a0cf6770e5559949bc276de2e22.UUID)()
    SetMfaRequired(value *bool)()
    SetMfaVerified(value *bool)()
    SetOrgs(value []Orgable)()
    SetReturnTo(value *string)()
    SetTypeEscaped(value *AuthFlow_type)()
    SetUserId(value *i561e97a8befe7661a44c8f54600992b4207a3a0cf6770e5559949bc276de2e22.UUID)()
}
