// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package models

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

type BackupCode struct {
    // The backup code string.
    code *string
    // Indicates if the backup code has been used.
    used *bool
}
// NewBackupCode instantiates a new BackupCode and sets the default values.
func NewBackupCode()(*BackupCode) {
    m := &BackupCode{
    }
    return m
}
// CreateBackupCodeFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateBackupCodeFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewBackupCode(), nil
}
// GetCode gets the code property value. The backup code string.
// returns a *string when successful
func (m *BackupCode) GetCode()(*string) {
    return m.code
}
// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error) when successful
func (m *BackupCode) GetFieldDeserializers()(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error)) {
    res := make(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error))
    res["code"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetCode(val)
        }
        return nil
    }
    res["used"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetBoolValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetUsed(val)
        }
        return nil
    }
    return res
}
// GetUsed gets the used property value. Indicates if the backup code has been used.
// returns a *bool when successful
func (m *BackupCode) GetUsed()(*bool) {
    return m.used
}
// Serialize serializes information the current object
func (m *BackupCode) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter)(error) {
    {
        err := writer.WriteStringValue("code", m.GetCode())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteBoolValue("used", m.GetUsed())
        if err != nil {
            return err
        }
    }
    return nil
}
// SetCode sets the code property value. The backup code string.
func (m *BackupCode) SetCode(value *string)() {
    m.code = value
}
// SetUsed sets the used property value. Indicates if the backup code has been used.
func (m *BackupCode) SetUsed(value *bool)() {
    m.used = value
}
type BackupCodeable interface {
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    GetCode()(*string)
    GetUsed()(*bool)
    SetCode(value *string)()
    SetUsed(value *bool)()
}
