// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package models

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

type QueryFilterOption struct {
    // Field name to filter on.
    field *string
    // Enum representing query filter operations.
    op *QueryFilterOp
}
// NewQueryFilterOption instantiates a new QueryFilterOption and sets the default values.
func NewQueryFilterOption()(*QueryFilterOption) {
    m := &QueryFilterOption{
    }
    return m
}
// CreateQueryFilterOptionFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateQueryFilterOptionFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewQueryFilterOption(), nil
}
// GetField gets the field property value. Field name to filter on.
// returns a *string when successful
func (m *QueryFilterOption) GetField()(*string) {
    return m.field
}
// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error) when successful
func (m *QueryFilterOption) GetFieldDeserializers()(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error)) {
    res := make(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error))
    res["field"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetField(val)
        }
        return nil
    }
    res["op"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetEnumValue(ParseQueryFilterOp)
        if err != nil {
            return err
        }
        if val != nil {
            m.SetOp(val.(*QueryFilterOp))
        }
        return nil
    }
    return res
}
// GetOp gets the op property value. Enum representing query filter operations.
// returns a *QueryFilterOp when successful
func (m *QueryFilterOption) GetOp()(*QueryFilterOp) {
    return m.op
}
// Serialize serializes information the current object
func (m *QueryFilterOption) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter)(error) {
    {
        err := writer.WriteStringValue("field", m.GetField())
        if err != nil {
            return err
        }
    }
    if m.GetOp() != nil {
        cast := (*m.GetOp()).String()
        err := writer.WriteStringValue("op", &cast)
        if err != nil {
            return err
        }
    }
    return nil
}
// SetField sets the field property value. Field name to filter on.
func (m *QueryFilterOption) SetField(value *string)() {
    m.field = value
}
// SetOp sets the op property value. Enum representing query filter operations.
func (m *QueryFilterOption) SetOp(value *QueryFilterOp)() {
    m.op = value
}
type QueryFilterOptionable interface {
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    GetField()(*string)
    GetOp()(*QueryFilterOp)
    SetField(value *string)()
    SetOp(value *QueryFilterOp)()
}
