// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package models
// Enum representing query filter operations.
type QueryFilterOp int

const (
    EQ_QUERYFILTEROP QueryFilterOp = iota
    NEQ_QUERYFILTEROP
    GT_QUERYFILTEROP
    GTE_QUERYFILTEROP
    LT_QUERYFILTEROP
    LTE_QUERYFILTEROP
    CONTAINS_QUERYFILTEROP
)

func (i QueryFilterOp) String() string {
    return []string{"EQ", "NEQ", "GT", "GTE", "LT", "LTE", "CONTAINS"}[i]
}
func ParseQueryFilterOp(v string) (any, error) {
    result := EQ_QUERYFILTEROP
    switch v {
        case "EQ":
            result = EQ_QUERYFILTEROP
        case "NEQ":
            result = NEQ_QUERYFILTEROP
        case "GT":
            result = GT_QUERYFILTEROP
        case "GTE":
            result = GTE_QUERYFILTEROP
        case "LT":
            result = LT_QUERYFILTEROP
        case "LTE":
            result = LTE_QUERYFILTEROP
        case "CONTAINS":
            result = CONTAINS_QUERYFILTEROP
        default:
            return nil, nil
    }
    return &result, nil
}
func SerializeQueryFilterOp(values []QueryFilterOp) []string {
    result := make([]string, len(values))
    for i, v := range values {
        result[i] = v.String()
    }
    return result
}
func (i QueryFilterOp) isMultiValue() bool {
    return false
}
