// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package models
// Enum representing query filter modes.
type QueryFilterMode int

const (
    AND_QUERYFILTERMODE QueryFilterMode = iota
    OR_QUERYFILTERMODE
)

func (i QueryFilterMode) String() string {
    return []string{"AND", "OR"}[i]
}
func ParseQueryFilterMode(v string) (any, error) {
    result := AND_QUERYFILTERMODE
    switch v {
        case "AND":
            result = AND_QUERYFILTERMODE
        case "OR":
            result = OR_QUERYFILTERMODE
        default:
            return nil, nil
    }
    return &result, nil
}
func SerializeQueryFilterMode(values []QueryFilterMode) []string {
    result := make([]string, len(values))
    for i, v := range values {
        result[i] = v.String()
    }
    return result
}
func (i QueryFilterMode) isMultiValue() bool {
    return false
}
