// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package models

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

type SysAdminGetOrgResponse struct {
    // List of domains associated with the organization.
    domains []Domainable
    // Response message.
    message *string
    // The org property
    org Orgable
    // List of roles associated with the organization.
    roles []MinimalRoleable
    // Indicates if the request was successful.
    success *bool
}
// NewSysAdminGetOrgResponse instantiates a new SysAdminGetOrgResponse and sets the default values.
func NewSysAdminGetOrgResponse()(*SysAdminGetOrgResponse) {
    m := &SysAdminGetOrgResponse{
    }
    return m
}
// CreateSysAdminGetOrgResponseFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateSysAdminGetOrgResponseFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewSysAdminGetOrgResponse(), nil
}
// GetDomains gets the domains property value. List of domains associated with the organization.
// returns a []Domainable when successful
func (m *SysAdminGetOrgResponse) GetDomains()([]Domainable) {
    return m.domains
}
// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error) when successful
func (m *SysAdminGetOrgResponse) GetFieldDeserializers()(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error)) {
    res := make(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error))
    res["domains"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetCollectionOfObjectValues(CreateDomainFromDiscriminatorValue)
        if err != nil {
            return err
        }
        if val != nil {
            res := make([]Domainable, len(val))
            for i, v := range val {
                if v != nil {
                    res[i] = v.(Domainable)
                }
            }
            m.SetDomains(res)
        }
        return nil
    }
    res["message"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetMessage(val)
        }
        return nil
    }
    res["org"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetObjectValue(CreateOrgFromDiscriminatorValue)
        if err != nil {
            return err
        }
        if val != nil {
            m.SetOrg(val.(Orgable))
        }
        return nil
    }
    res["roles"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetCollectionOfObjectValues(CreateMinimalRoleFromDiscriminatorValue)
        if err != nil {
            return err
        }
        if val != nil {
            res := make([]MinimalRoleable, len(val))
            for i, v := range val {
                if v != nil {
                    res[i] = v.(MinimalRoleable)
                }
            }
            m.SetRoles(res)
        }
        return nil
    }
    res["success"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetBoolValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetSuccess(val)
        }
        return nil
    }
    return res
}
// GetMessage gets the message property value. Response message.
// returns a *string when successful
func (m *SysAdminGetOrgResponse) GetMessage()(*string) {
    return m.message
}
// GetOrg gets the org property value. The org property
// returns a Orgable when successful
func (m *SysAdminGetOrgResponse) GetOrg()(Orgable) {
    return m.org
}
// GetRoles gets the roles property value. List of roles associated with the organization.
// returns a []MinimalRoleable when successful
func (m *SysAdminGetOrgResponse) GetRoles()([]MinimalRoleable) {
    return m.roles
}
// GetSuccess gets the success property value. Indicates if the request was successful.
// returns a *bool when successful
func (m *SysAdminGetOrgResponse) GetSuccess()(*bool) {
    return m.success
}
// Serialize serializes information the current object
func (m *SysAdminGetOrgResponse) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter)(error) {
    if m.GetDomains() != nil {
        cast := make([]i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, len(m.GetDomains()))
        for i, v := range m.GetDomains() {
            if v != nil {
                cast[i] = v.(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable)
            }
        }
        err := writer.WriteCollectionOfObjectValues("domains", cast)
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("message", m.GetMessage())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteObjectValue("org", m.GetOrg())
        if err != nil {
            return err
        }
    }
    if m.GetRoles() != nil {
        cast := make([]i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, len(m.GetRoles()))
        for i, v := range m.GetRoles() {
            if v != nil {
                cast[i] = v.(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable)
            }
        }
        err := writer.WriteCollectionOfObjectValues("roles", cast)
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteBoolValue("success", m.GetSuccess())
        if err != nil {
            return err
        }
    }
    return nil
}
// SetDomains sets the domains property value. List of domains associated with the organization.
func (m *SysAdminGetOrgResponse) SetDomains(value []Domainable)() {
    m.domains = value
}
// SetMessage sets the message property value. Response message.
func (m *SysAdminGetOrgResponse) SetMessage(value *string)() {
    m.message = value
}
// SetOrg sets the org property value. The org property
func (m *SysAdminGetOrgResponse) SetOrg(value Orgable)() {
    m.org = value
}
// SetRoles sets the roles property value. List of roles associated with the organization.
func (m *SysAdminGetOrgResponse) SetRoles(value []MinimalRoleable)() {
    m.roles = value
}
// SetSuccess sets the success property value. Indicates if the request was successful.
func (m *SysAdminGetOrgResponse) SetSuccess(value *bool)() {
    m.success = value
}
type SysAdminGetOrgResponseable interface {
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    GetDomains()([]Domainable)
    GetMessage()(*string)
    GetOrg()(Orgable)
    GetRoles()([]MinimalRoleable)
    GetSuccess()(*bool)
    SetDomains(value []Domainable)()
    SetMessage(value *string)()
    SetOrg(value Orgable)()
    SetRoles(value []MinimalRoleable)()
    SetSuccess(value *bool)()
}
