// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package models

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

type SysAdminGetConfigResponse struct {
    // The config property
    config SystemConfigPublicFacingable
    // Response message.
    message *string
    // Indicates if the request was successful.
    success *bool
}
// NewSysAdminGetConfigResponse instantiates a new SysAdminGetConfigResponse and sets the default values.
func NewSysAdminGetConfigResponse()(*SysAdminGetConfigResponse) {
    m := &SysAdminGetConfigResponse{
    }
    return m
}
// CreateSysAdminGetConfigResponseFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateSysAdminGetConfigResponseFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewSysAdminGetConfigResponse(), nil
}
// GetConfig gets the config property value. The config property
// returns a SystemConfigPublicFacingable when successful
func (m *SysAdminGetConfigResponse) GetConfig()(SystemConfigPublicFacingable) {
    return m.config
}
// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error) when successful
func (m *SysAdminGetConfigResponse) GetFieldDeserializers()(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error)) {
    res := make(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error))
    res["config"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetObjectValue(CreateSystemConfigPublicFacingFromDiscriminatorValue)
        if err != nil {
            return err
        }
        if val != nil {
            m.SetConfig(val.(SystemConfigPublicFacingable))
        }
        return nil
    }
    res["message"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetMessage(val)
        }
        return nil
    }
    res["success"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetBoolValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetSuccess(val)
        }
        return nil
    }
    return res
}
// GetMessage gets the message property value. Response message.
// returns a *string when successful
func (m *SysAdminGetConfigResponse) GetMessage()(*string) {
    return m.message
}
// GetSuccess gets the success property value. Indicates if the request was successful.
// returns a *bool when successful
func (m *SysAdminGetConfigResponse) GetSuccess()(*bool) {
    return m.success
}
// Serialize serializes information the current object
func (m *SysAdminGetConfigResponse) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter)(error) {
    {
        err := writer.WriteObjectValue("config", m.GetConfig())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("message", m.GetMessage())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteBoolValue("success", m.GetSuccess())
        if err != nil {
            return err
        }
    }
    return nil
}
// SetConfig sets the config property value. The config property
func (m *SysAdminGetConfigResponse) SetConfig(value SystemConfigPublicFacingable)() {
    m.config = value
}
// SetMessage sets the message property value. Response message.
func (m *SysAdminGetConfigResponse) SetMessage(value *string)() {
    m.message = value
}
// SetSuccess sets the success property value. Indicates if the request was successful.
func (m *SysAdminGetConfigResponse) SetSuccess(value *bool)() {
    m.success = value
}
type SysAdminGetConfigResponseable interface {
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    GetConfig()(SystemConfigPublicFacingable)
    GetMessage()(*string)
    GetSuccess()(*bool)
    SetConfig(value SystemConfigPublicFacingable)()
    SetMessage(value *string)()
    SetSuccess(value *bool)()
}
