// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package models

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

type SysAdminCreateOrgRequest struct {
    // URL of the organization's avatar image. If you wish to upload a new image, use the dedicated avatar upload endpoint. It will automatically update the avatarURL. Uploading an avatar during org creation is not possible, you need to upload it after you create the org.
    avatarURL *string
    // Description of the organization.
    description *string
    // Name of the organization to be created.
    name *string
    // Organization settings schema.
    settings OrgSettingsable
    // Unique slug for the organization.
    slug *string
}
// NewSysAdminCreateOrgRequest instantiates a new SysAdminCreateOrgRequest and sets the default values.
func NewSysAdminCreateOrgRequest()(*SysAdminCreateOrgRequest) {
    m := &SysAdminCreateOrgRequest{
    }
    return m
}
// CreateSysAdminCreateOrgRequestFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateSysAdminCreateOrgRequestFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewSysAdminCreateOrgRequest(), nil
}
// GetAvatarURL gets the avatarURL property value. URL of the organization's avatar image. If you wish to upload a new image, use the dedicated avatar upload endpoint. It will automatically update the avatarURL. Uploading an avatar during org creation is not possible, you need to upload it after you create the org.
// returns a *string when successful
func (m *SysAdminCreateOrgRequest) GetAvatarURL()(*string) {
    return m.avatarURL
}
// GetDescription gets the description property value. Description of the organization.
// returns a *string when successful
func (m *SysAdminCreateOrgRequest) GetDescription()(*string) {
    return m.description
}
// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error) when successful
func (m *SysAdminCreateOrgRequest) GetFieldDeserializers()(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error)) {
    res := make(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error))
    res["avatarURL"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetAvatarURL(val)
        }
        return nil
    }
    res["description"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetDescription(val)
        }
        return nil
    }
    res["name"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetName(val)
        }
        return nil
    }
    res["settings"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetObjectValue(CreateOrgSettingsFromDiscriminatorValue)
        if err != nil {
            return err
        }
        if val != nil {
            m.SetSettings(val.(OrgSettingsable))
        }
        return nil
    }
    res["slug"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetSlug(val)
        }
        return nil
    }
    return res
}
// GetName gets the name property value. Name of the organization to be created.
// returns a *string when successful
func (m *SysAdminCreateOrgRequest) GetName()(*string) {
    return m.name
}
// GetSettings gets the settings property value. Organization settings schema.
// returns a OrgSettingsable when successful
func (m *SysAdminCreateOrgRequest) GetSettings()(OrgSettingsable) {
    return m.settings
}
// GetSlug gets the slug property value. Unique slug for the organization.
// returns a *string when successful
func (m *SysAdminCreateOrgRequest) GetSlug()(*string) {
    return m.slug
}
// Serialize serializes information the current object
func (m *SysAdminCreateOrgRequest) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter)(error) {
    {
        err := writer.WriteStringValue("avatarURL", m.GetAvatarURL())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("description", m.GetDescription())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("name", m.GetName())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteObjectValue("settings", m.GetSettings())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("slug", m.GetSlug())
        if err != nil {
            return err
        }
    }
    return nil
}
// SetAvatarURL sets the avatarURL property value. URL of the organization's avatar image. If you wish to upload a new image, use the dedicated avatar upload endpoint. It will automatically update the avatarURL. Uploading an avatar during org creation is not possible, you need to upload it after you create the org.
func (m *SysAdminCreateOrgRequest) SetAvatarURL(value *string)() {
    m.avatarURL = value
}
// SetDescription sets the description property value. Description of the organization.
func (m *SysAdminCreateOrgRequest) SetDescription(value *string)() {
    m.description = value
}
// SetName sets the name property value. Name of the organization to be created.
func (m *SysAdminCreateOrgRequest) SetName(value *string)() {
    m.name = value
}
// SetSettings sets the settings property value. Organization settings schema.
func (m *SysAdminCreateOrgRequest) SetSettings(value OrgSettingsable)() {
    m.settings = value
}
// SetSlug sets the slug property value. Unique slug for the organization.
func (m *SysAdminCreateOrgRequest) SetSlug(value *string)() {
    m.slug = value
}
type SysAdminCreateOrgRequestable interface {
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    GetAvatarURL()(*string)
    GetDescription()(*string)
    GetName()(*string)
    GetSettings()(OrgSettingsable)
    GetSlug()(*string)
    SetAvatarURL(value *string)()
    SetDescription(value *string)()
    SetName(value *string)()
    SetSettings(value OrgSettingsable)()
    SetSlug(value *string)()
}
