// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package models

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

type SysAdminListOrgsResponse struct {
    // Response message.
    message *string
    // List of organizations.
    orgs []Orgable
    // Pagination details.
    pagination QueryPaginationable
    // Indicates if the request was successful.
    success *bool
    // Total number of organizations matching the query.
    total *int32
}
// NewSysAdminListOrgsResponse instantiates a new SysAdminListOrgsResponse and sets the default values.
func NewSysAdminListOrgsResponse()(*SysAdminListOrgsResponse) {
    m := &SysAdminListOrgsResponse{
    }
    return m
}
// CreateSysAdminListOrgsResponseFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateSysAdminListOrgsResponseFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewSysAdminListOrgsResponse(), nil
}
// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error) when successful
func (m *SysAdminListOrgsResponse) GetFieldDeserializers()(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error)) {
    res := make(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error))
    res["message"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetMessage(val)
        }
        return nil
    }
    res["orgs"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetCollectionOfObjectValues(CreateOrgFromDiscriminatorValue)
        if err != nil {
            return err
        }
        if val != nil {
            res := make([]Orgable, len(val))
            for i, v := range val {
                if v != nil {
                    res[i] = v.(Orgable)
                }
            }
            m.SetOrgs(res)
        }
        return nil
    }
    res["pagination"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetObjectValue(CreateQueryPaginationFromDiscriminatorValue)
        if err != nil {
            return err
        }
        if val != nil {
            m.SetPagination(val.(QueryPaginationable))
        }
        return nil
    }
    res["success"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetBoolValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetSuccess(val)
        }
        return nil
    }
    res["total"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetInt32Value()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetTotal(val)
        }
        return nil
    }
    return res
}
// GetMessage gets the message property value. Response message.
// returns a *string when successful
func (m *SysAdminListOrgsResponse) GetMessage()(*string) {
    return m.message
}
// GetOrgs gets the orgs property value. List of organizations.
// returns a []Orgable when successful
func (m *SysAdminListOrgsResponse) GetOrgs()([]Orgable) {
    return m.orgs
}
// GetPagination gets the pagination property value. Pagination details.
// returns a QueryPaginationable when successful
func (m *SysAdminListOrgsResponse) GetPagination()(QueryPaginationable) {
    return m.pagination
}
// GetSuccess gets the success property value. Indicates if the request was successful.
// returns a *bool when successful
func (m *SysAdminListOrgsResponse) GetSuccess()(*bool) {
    return m.success
}
// GetTotal gets the total property value. Total number of organizations matching the query.
// returns a *int32 when successful
func (m *SysAdminListOrgsResponse) GetTotal()(*int32) {
    return m.total
}
// Serialize serializes information the current object
func (m *SysAdminListOrgsResponse) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter)(error) {
    {
        err := writer.WriteStringValue("message", m.GetMessage())
        if err != nil {
            return err
        }
    }
    if m.GetOrgs() != nil {
        cast := make([]i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, len(m.GetOrgs()))
        for i, v := range m.GetOrgs() {
            if v != nil {
                cast[i] = v.(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable)
            }
        }
        err := writer.WriteCollectionOfObjectValues("orgs", cast)
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteObjectValue("pagination", m.GetPagination())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteBoolValue("success", m.GetSuccess())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteInt32Value("total", m.GetTotal())
        if err != nil {
            return err
        }
    }
    return nil
}
// SetMessage sets the message property value. Response message.
func (m *SysAdminListOrgsResponse) SetMessage(value *string)() {
    m.message = value
}
// SetOrgs sets the orgs property value. List of organizations.
func (m *SysAdminListOrgsResponse) SetOrgs(value []Orgable)() {
    m.orgs = value
}
// SetPagination sets the pagination property value. Pagination details.
func (m *SysAdminListOrgsResponse) SetPagination(value QueryPaginationable)() {
    m.pagination = value
}
// SetSuccess sets the success property value. Indicates if the request was successful.
func (m *SysAdminListOrgsResponse) SetSuccess(value *bool)() {
    m.success = value
}
// SetTotal sets the total property value. Total number of organizations matching the query.
func (m *SysAdminListOrgsResponse) SetTotal(value *int32)() {
    m.total = value
}
type SysAdminListOrgsResponseable interface {
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    GetMessage()(*string)
    GetOrgs()([]Orgable)
    GetPagination()(QueryPaginationable)
    GetSuccess()(*bool)
    GetTotal()(*int32)
    SetMessage(value *string)()
    SetOrgs(value []Orgable)()
    SetPagination(value QueryPaginationable)()
    SetSuccess(value *bool)()
    SetTotal(value *int32)()
}
