// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package models

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

type SysAdminListOrgsRequest struct {
    // The filters property
    filters QueryFiltersable
    // The pagination property
    pagination QueryPaginationable
    // Sorting options.
    sort []QuerySortOptionable
}
// NewSysAdminListOrgsRequest instantiates a new SysAdminListOrgsRequest and sets the default values.
func NewSysAdminListOrgsRequest()(*SysAdminListOrgsRequest) {
    m := &SysAdminListOrgsRequest{
    }
    return m
}
// CreateSysAdminListOrgsRequestFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateSysAdminListOrgsRequestFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewSysAdminListOrgsRequest(), nil
}
// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error) when successful
func (m *SysAdminListOrgsRequest) GetFieldDeserializers()(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error)) {
    res := make(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error))
    res["filters"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetObjectValue(CreateQueryFiltersFromDiscriminatorValue)
        if err != nil {
            return err
        }
        if val != nil {
            m.SetFilters(val.(QueryFiltersable))
        }
        return nil
    }
    res["pagination"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetObjectValue(CreateQueryPaginationFromDiscriminatorValue)
        if err != nil {
            return err
        }
        if val != nil {
            m.SetPagination(val.(QueryPaginationable))
        }
        return nil
    }
    res["sort"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetCollectionOfObjectValues(CreateQuerySortOptionFromDiscriminatorValue)
        if err != nil {
            return err
        }
        if val != nil {
            res := make([]QuerySortOptionable, len(val))
            for i, v := range val {
                if v != nil {
                    res[i] = v.(QuerySortOptionable)
                }
            }
            m.SetSort(res)
        }
        return nil
    }
    return res
}
// GetFilters gets the filters property value. The filters property
// returns a QueryFiltersable when successful
func (m *SysAdminListOrgsRequest) GetFilters()(QueryFiltersable) {
    return m.filters
}
// GetPagination gets the pagination property value. The pagination property
// returns a QueryPaginationable when successful
func (m *SysAdminListOrgsRequest) GetPagination()(QueryPaginationable) {
    return m.pagination
}
// GetSort gets the sort property value. Sorting options.
// returns a []QuerySortOptionable when successful
func (m *SysAdminListOrgsRequest) GetSort()([]QuerySortOptionable) {
    return m.sort
}
// Serialize serializes information the current object
func (m *SysAdminListOrgsRequest) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter)(error) {
    {
        err := writer.WriteObjectValue("filters", m.GetFilters())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteObjectValue("pagination", m.GetPagination())
        if err != nil {
            return err
        }
    }
    if m.GetSort() != nil {
        cast := make([]i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, len(m.GetSort()))
        for i, v := range m.GetSort() {
            if v != nil {
                cast[i] = v.(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable)
            }
        }
        err := writer.WriteCollectionOfObjectValues("sort", cast)
        if err != nil {
            return err
        }
    }
    return nil
}
// SetFilters sets the filters property value. The filters property
func (m *SysAdminListOrgsRequest) SetFilters(value QueryFiltersable)() {
    m.filters = value
}
// SetPagination sets the pagination property value. The pagination property
func (m *SysAdminListOrgsRequest) SetPagination(value QueryPaginationable)() {
    m.pagination = value
}
// SetSort sets the sort property value. Sorting options.
func (m *SysAdminListOrgsRequest) SetSort(value []QuerySortOptionable)() {
    m.sort = value
}
type SysAdminListOrgsRequestable interface {
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    GetFilters()(QueryFiltersable)
    GetPagination()(QueryPaginationable)
    GetSort()([]QuerySortOptionable)
    SetFilters(value QueryFiltersable)()
    SetPagination(value QueryPaginationable)()
    SetSort(value []QuerySortOptionable)()
}
