// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package models

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

type SystemConfigPublicFacing struct {
    // Indicates if the system is in debug mode.
    debug *bool
}
// NewSystemConfigPublicFacing instantiates a new SystemConfigPublicFacing and sets the default values.
func NewSystemConfigPublicFacing()(*SystemConfigPublicFacing) {
    m := &SystemConfigPublicFacing{
    }
    return m
}
// CreateSystemConfigPublicFacingFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateSystemConfigPublicFacingFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewSystemConfigPublicFacing(), nil
}
// GetDebug gets the debug property value. Indicates if the system is in debug mode.
// returns a *bool when successful
func (m *SystemConfigPublicFacing) GetDebug()(*bool) {
    return m.debug
}
// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error) when successful
func (m *SystemConfigPublicFacing) GetFieldDeserializers()(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error)) {
    res := make(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error))
    res["debug"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetBoolValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetDebug(val)
        }
        return nil
    }
    return res
}
// Serialize serializes information the current object
func (m *SystemConfigPublicFacing) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter)(error) {
    {
        err := writer.WriteBoolValue("debug", m.GetDebug())
        if err != nil {
            return err
        }
    }
    return nil
}
// SetDebug sets the debug property value. Indicates if the system is in debug mode.
func (m *SystemConfigPublicFacing) SetDebug(value *bool)() {
    m.debug = value
}
type SystemConfigPublicFacingable interface {
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    GetDebug()(*bool)
    SetDebug(value *bool)()
}
