// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package admin

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
    i33b313a9f66fb27124acf027b067204a8f878cf88c95cc5ebd551e89642f948d "github.com/nbrglm/nexeres/sdks/nexeres-go/models/models"
)

type AdminUpdateOrgRequest struct {
    // Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
    additionalData map[string]any
    // The description property
    description *string
    // The name property
    name *string
    // The settings property
    settings i33b313a9f66fb27124acf027b067204a8f878cf88c95cc5ebd551e89642f948d.OrgSettingsable
}
// NewAdminUpdateOrgRequest instantiates a new AdminUpdateOrgRequest and sets the default values.
func NewAdminUpdateOrgRequest()(*AdminUpdateOrgRequest) {
    m := &AdminUpdateOrgRequest{
    }
    m.SetAdditionalData(make(map[string]any))
    return m
}
// CreateAdminUpdateOrgRequestFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateAdminUpdateOrgRequestFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewAdminUpdateOrgRequest(), nil
}
// GetAdditionalData gets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
// returns a map[string]any when successful
func (m *AdminUpdateOrgRequest) GetAdditionalData()(map[string]any) {
    return m.additionalData
}
// GetDescription gets the description property value. The description property
// returns a *string when successful
func (m *AdminUpdateOrgRequest) GetDescription()(*string) {
    return m.description
}
// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error) when successful
func (m *AdminUpdateOrgRequest) GetFieldDeserializers()(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error)) {
    res := make(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error))
    res["description"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetDescription(val)
        }
        return nil
    }
    res["name"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetName(val)
        }
        return nil
    }
    res["settings"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetObjectValue(i33b313a9f66fb27124acf027b067204a8f878cf88c95cc5ebd551e89642f948d.CreateOrgSettingsFromDiscriminatorValue)
        if err != nil {
            return err
        }
        if val != nil {
            m.SetSettings(val.(i33b313a9f66fb27124acf027b067204a8f878cf88c95cc5ebd551e89642f948d.OrgSettingsable))
        }
        return nil
    }
    return res
}
// GetName gets the name property value. The name property
// returns a *string when successful
func (m *AdminUpdateOrgRequest) GetName()(*string) {
    return m.name
}
// GetSettings gets the settings property value. The settings property
// returns a OrgSettingsable when successful
func (m *AdminUpdateOrgRequest) GetSettings()(i33b313a9f66fb27124acf027b067204a8f878cf88c95cc5ebd551e89642f948d.OrgSettingsable) {
    return m.settings
}
// Serialize serializes information the current object
func (m *AdminUpdateOrgRequest) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter)(error) {
    {
        err := writer.WriteStringValue("description", m.GetDescription())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("name", m.GetName())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteObjectValue("settings", m.GetSettings())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteAdditionalData(m.GetAdditionalData())
        if err != nil {
            return err
        }
    }
    return nil
}
// SetAdditionalData sets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
func (m *AdminUpdateOrgRequest) SetAdditionalData(value map[string]any)() {
    m.additionalData = value
}
// SetDescription sets the description property value. The description property
func (m *AdminUpdateOrgRequest) SetDescription(value *string)() {
    m.description = value
}
// SetName sets the name property value. The name property
func (m *AdminUpdateOrgRequest) SetName(value *string)() {
    m.name = value
}
// SetSettings sets the settings property value. The settings property
func (m *AdminUpdateOrgRequest) SetSettings(value i33b313a9f66fb27124acf027b067204a8f878cf88c95cc5ebd551e89642f948d.OrgSettingsable)() {
    m.settings = value
}
type AdminUpdateOrgRequestable interface {
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.AdditionalDataHolder
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    GetDescription()(*string)
    GetName()(*string)
    GetSettings()(i33b313a9f66fb27124acf027b067204a8f878cf88c95cc5ebd551e89642f948d.OrgSettingsable)
    SetDescription(value *string)()
    SetName(value *string)()
    SetSettings(value i33b313a9f66fb27124acf027b067204a8f878cf88c95cc5ebd551e89642f948d.OrgSettingsable)()
}
