/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createOrgFromDiscriminatorValue, serializeOrg, type Org } from '../db/index.js';
// @ts-ignore
import { type AdditionalDataHolder, type Parsable, type ParseNode, type SerializationWriter } from '@microsoft/kiota-abstractions';

/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {FlowData}
 */
// @ts-ignore
export function createFlowDataFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoFlowData;
}
/**
 * The deserialization information for the current model
 * @param FlowData The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoFlowData(flowData: Partial<FlowData> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "createdAt": n => { flowData.createdAt = n.getStringValue(); },
        "email": n => { flowData.email = n.getStringValue(); },
        "expiresAt": n => { flowData.expiresAt = n.getStringValue(); },
        "id": n => { flowData.id = n.getStringValue(); },
        "mfaRequired": n => { flowData.mfaRequired = n.getBooleanValue(); },
        "mfaVerified": n => { flowData.mfaVerified = n.getBooleanValue(); },
        "orgs": n => { flowData.orgs = n.getCollectionOfObjectValues<Org>(createOrgFromDiscriminatorValue); },
        "returnTo": n => { flowData.returnTo = n.getStringValue(); },
        "type": n => { flowData.type = n.getStringValue(); },
        "userId": n => { flowData.userId = n.getStringValue(); },
    }
}
export interface FlowData extends AdditionalDataHolder, Parsable {
    /**
     * The createdAt property
     */
    createdAt?: string | null;
    /**
     * The email property
     */
    email?: string | null;
    /**
     * The expiresAt property
     */
    expiresAt?: string | null;
    /**
     * The id property
     */
    id?: string | null;
    /**
     * The mfaRequired property
     */
    mfaRequired?: boolean | null;
    /**
     * The mfaVerified property
     */
    mfaVerified?: boolean | null;
    /**
     * The orgs property
     */
    orgs?: Org[] | null;
    /**
     * URL to redirect after flow completion
     */
    returnTo?: string | null;
    /**
     * The type property
     */
    type?: string | null;
    /**
     * The userId property
     */
    userId?: string | null;
}
/**
 * Serializes information the current object
 * @param FlowData The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeFlowData(writer: SerializationWriter, flowData: Partial<FlowData> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!flowData || isSerializingDerivedType) { return; }
    writer.writeStringValue("createdAt", flowData.createdAt);
    writer.writeStringValue("email", flowData.email);
    writer.writeStringValue("expiresAt", flowData.expiresAt);
    writer.writeStringValue("id", flowData.id);
    writer.writeBooleanValue("mfaRequired", flowData.mfaRequired);
    writer.writeBooleanValue("mfaVerified", flowData.mfaVerified);
    writer.writeCollectionOfObjectValues<Org>("orgs", flowData.orgs, serializeOrg);
    writer.writeStringValue("returnTo", flowData.returnTo);
    writer.writeStringValue("type", flowData.type);
    writer.writeStringValue("userId", flowData.userId);
    writer.writeAdditionalData(flowData.additionalData);
}
/* tslint:enable */
/* eslint-enable */
