services:
  nexeres-db:
    image: postgres:17
    container_name: nexeres-db
    hostname: nexeres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: nexeres
    volumes:
      - ./data/nexeres-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  nexeres-pgadmin:
    image: dpage/pgadmin4:latest
    container_name: nexeres-pgadmin
    hostname: nexeres-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    volumes:
      - ./data/nexeres-pgadmin-data:/var/lib/pgadmin

  nexeres-mailpit:
    image: axllent/mailpit
    container_name: nexeres-mailpit
    hostname: nexeres-mailpit
    ports:
      - "8025:8025"
      - "1025:1025"
    volumes:
      - ./data/nexeres-mailpit-data:/data
    environment:
      MP_MAX_MESSAGES: 5000
      MP_DATABASE: /data/mailpit.db
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1

  nexeres-redis:
    image: redis:8
    container_name: nexeres-redis
    hostname: nexeres-redis
    ports:
      - "6379:6379"
    volumes:
      - ./data/nexeres-redis-data:/data
    command: redis-server --requirepass nexeres-redis-password --appendonly yes

  nexeres-seaweedfs-master:
    image: chrislusf/seaweedfs:latest
    container_name: nexeres-seaweedfs-master
    hostname: nexeres-seaweedfs-master
    command: master
    ports:
      - 9333:9333
  
  nexeres-seaweedfs-filer:
    image: chrislusf/seaweedfs:latest
    container_name: nexeres-seaweedfs-filer
    hostname: nexeres-seaweedfs-filer
    command: filer -master=nexeres-seaweedfs-master:9333 -s3
    ports:
      - "8333:8333"
      - "8888:8888"
    depends_on:
      - nexeres-seaweedfs-master
  
  nexeres-seaweedfs-volume1:
    image: chrislusf/seaweedfs:latest
    container_name: nexeres-seaweedfs-volume1
    hostname: nexeres-seaweedfs-volume1
    command: volume -max=5 -dir=/data -master=nexeres-seaweedfs-master:9333 -port=8989
    volumes:
      - ./data/nexeres-seaweedfs-volume1-data:/data
    depends_on:
      - nexeres-seaweedfs-master
    ports:
      - "8989:8989"
  
  nexeres-seaweedfs-volume2:
    image: chrislusf/seaweedfs:latest
    container_name: nexeres-seaweedfs-volume2
    hostname: nexeres-seaweedfs-volume2
    command: volume -max=5 -dir=/data -master=nexeres-seaweedfs-master:9333 -port=8990
    volumes:
      - ./data/nexeres-seaweedfs-volume2-data:/data
    depends_on:
      - nexeres-seaweedfs-master
    ports:
      - "8990:8990"

  nexeres-minio:
    image: quay.io/minio/minio:latest
    container_name: nexeres-minio
    hostname: nexeres-minio
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./data/nexeres-minio-data:/data
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio-admin
      MINIO_REGION_NAME: ind-south-c1
  
  nexeres-alloy:
    image: grafana/alloy:latest
    container_name: nexeres-alloy
    hostname: nexeres-alloy
    ports:
      - 12345:12345
      - 4318:4318
    command: ["run", "--server.http.listen-addr=0.0.0.0:12345", "--storage.path=/var/lib/alloy/data", "/etc/alloy/config.alloy"]
    volumes:
      - ./data/config.alloy:/etc/alloy/config.alloy