// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package api

import (
    "context"
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f "github.com/microsoft/kiota-abstractions-go"
    i8905b30da6c1d2a87a239cfc7fb4da19fec8b7c521471730fa009da8140d0df4 "github.com/nbrglm/nexeres/sdks/nexeres-go/models"
)

// AdminOrgsItemDomainsItemVerifyRequestBuilder builds and executes requests for operations under \api\admin\orgs\{orgId}\domains\{domain}\verify
type AdminOrgsItemDomainsItemVerifyRequestBuilder struct {
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.BaseRequestBuilder
}
// AdminOrgsItemDomainsItemVerifyRequestBuilderPostRequestConfiguration configuration for the request such as headers, query parameters, and middleware options.
type AdminOrgsItemDomainsItemVerifyRequestBuilderPostRequestConfiguration struct {
    // Request headers
    Headers *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestHeaders
    // Request options
    Options []i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestOption
}
// Code the code property
// returns a *AdminOrgsItemDomainsItemVerifyCodeRequestBuilder when successful
func (m *AdminOrgsItemDomainsItemVerifyRequestBuilder) Code()(*AdminOrgsItemDomainsItemVerifyCodeRequestBuilder) {
    return NewAdminOrgsItemDomainsItemVerifyCodeRequestBuilderInternal(m.BaseRequestBuilder.PathParameters, m.BaseRequestBuilder.RequestAdapter)
}
// NewAdminOrgsItemDomainsItemVerifyRequestBuilderInternal instantiates a new AdminOrgsItemDomainsItemVerifyRequestBuilder and sets the default values.
func NewAdminOrgsItemDomainsItemVerifyRequestBuilderInternal(pathParameters map[string]string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter)(*AdminOrgsItemDomainsItemVerifyRequestBuilder) {
    m := &AdminOrgsItemDomainsItemVerifyRequestBuilder{
        BaseRequestBuilder: *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewBaseRequestBuilder(requestAdapter, "{+baseurl}/api/admin/orgs/{orgId}/domains/{domain}/verify", pathParameters),
    }
    return m
}
// NewAdminOrgsItemDomainsItemVerifyRequestBuilder instantiates a new AdminOrgsItemDomainsItemVerifyRequestBuilder and sets the default values.
func NewAdminOrgsItemDomainsItemVerifyRequestBuilder(rawUrl string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter)(*AdminOrgsItemDomainsItemVerifyRequestBuilder) {
    urlParams := make(map[string]string)
    urlParams["request-raw-url"] = rawUrl
    return NewAdminOrgsItemDomainsItemVerifyRequestBuilderInternal(urlParams, requestAdapter)
}
// Post trigger domain verification for an organization and domain.
// returns a AdminVerifyDomainResponseable when successful
// returns a ErrorResponse error when the service returns a 400 status code
// returns a ErrorResponse error when the service returns a 401 status code
// returns a ErrorResponse error when the service returns a 404 status code
// returns a ErrorResponse error when the service returns a 500 status code
func (m *AdminOrgsItemDomainsItemVerifyRequestBuilder) Post(ctx context.Context, requestConfiguration *AdminOrgsItemDomainsItemVerifyRequestBuilderPostRequestConfiguration)(i8905b30da6c1d2a87a239cfc7fb4da19fec8b7c521471730fa009da8140d0df4.AdminVerifyDomainResponseable, error) {
    requestInfo, err := m.ToPostRequestInformation(ctx, requestConfiguration);
    if err != nil {
        return nil, err
    }
    errorMapping := i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.ErrorMappings {
        "400": i8905b30da6c1d2a87a239cfc7fb4da19fec8b7c521471730fa009da8140d0df4.CreateErrorResponseFromDiscriminatorValue,
        "401": i8905b30da6c1d2a87a239cfc7fb4da19fec8b7c521471730fa009da8140d0df4.CreateErrorResponseFromDiscriminatorValue,
        "404": i8905b30da6c1d2a87a239cfc7fb4da19fec8b7c521471730fa009da8140d0df4.CreateErrorResponseFromDiscriminatorValue,
        "500": i8905b30da6c1d2a87a239cfc7fb4da19fec8b7c521471730fa009da8140d0df4.CreateErrorResponseFromDiscriminatorValue,
    }
    res, err := m.BaseRequestBuilder.RequestAdapter.Send(ctx, requestInfo, i8905b30da6c1d2a87a239cfc7fb4da19fec8b7c521471730fa009da8140d0df4.CreateAdminVerifyDomainResponseFromDiscriminatorValue, errorMapping)
    if err != nil {
        return nil, err
    }
    if res == nil {
        return nil, nil
    }
    return res.(i8905b30da6c1d2a87a239cfc7fb4da19fec8b7c521471730fa009da8140d0df4.AdminVerifyDomainResponseable), nil
}
// ToPostRequestInformation trigger domain verification for an organization and domain.
// returns a *RequestInformation when successful
func (m *AdminOrgsItemDomainsItemVerifyRequestBuilder) ToPostRequestInformation(ctx context.Context, requestConfiguration *AdminOrgsItemDomainsItemVerifyRequestBuilderPostRequestConfiguration)(*i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestInformation, error) {
    requestInfo := i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewRequestInformationWithMethodAndUrlTemplateAndPathParameters(i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.POST, m.BaseRequestBuilder.UrlTemplate, m.BaseRequestBuilder.PathParameters)
    if requestConfiguration != nil {
        requestInfo.Headers.AddAll(requestConfiguration.Headers)
        requestInfo.AddRequestOptions(requestConfiguration.Options)
    }
    requestInfo.Headers.TryAdd("Accept", "application/json")
    return requestInfo, nil
}
// WithUrl returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
// returns a *AdminOrgsItemDomainsItemVerifyRequestBuilder when successful
func (m *AdminOrgsItemDomainsItemVerifyRequestBuilder) WithUrl(rawUrl string)(*AdminOrgsItemDomainsItemVerifyRequestBuilder) {
    return NewAdminOrgsItemDomainsItemVerifyRequestBuilder(rawUrl, m.BaseRequestBuilder.RequestAdapter);
}
