// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package api

import (
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f "github.com/microsoft/kiota-abstractions-go"
    i561e97a8befe7661a44c8f54600992b4207a3a0cf6770e5559949bc276de2e22 "github.com/google/uuid"
)

// AdminOrgsRequestBuilder builds and executes requests for operations under \api\admin\orgs
type AdminOrgsRequestBuilder struct {
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.BaseRequestBuilder
}
// ByOrgId gets an item from the github.com/nbrglm/nexeres/sdks/nexeres-go.api.admin.orgs.item collection
// Deprecated: This indexer is deprecated and will be removed in the next major version. Use the one with the typed parameter instead.
// returns a *AdminOrgsWithOrgItemRequestBuilder when successful
func (m *AdminOrgsRequestBuilder) ByOrgId(orgId string)(*AdminOrgsWithOrgItemRequestBuilder) {
    urlTplParams := make(map[string]string)
    for idx, item := range m.BaseRequestBuilder.PathParameters {
        urlTplParams[idx] = item
    }
    if orgId != "" {
        urlTplParams["orgId"] = orgId
    }
    return NewAdminOrgsWithOrgItemRequestBuilderInternal(urlTplParams, m.BaseRequestBuilder.RequestAdapter)
}
// ByOrgIdGuid gets an item from the github.com/nbrglm/nexeres/sdks/nexeres-go.api.admin.orgs.item collection
// returns a *AdminOrgsWithOrgItemRequestBuilder when successful
func (m *AdminOrgsRequestBuilder) ByOrgIdGuid(orgId i561e97a8befe7661a44c8f54600992b4207a3a0cf6770e5559949bc276de2e22.UUID)(*AdminOrgsWithOrgItemRequestBuilder) {
    urlTplParams := make(map[string]string)
    for idx, item := range m.BaseRequestBuilder.PathParameters {
        urlTplParams[idx] = item
    }
    urlTplParams["orgId"] = orgId.String()
    return NewAdminOrgsWithOrgItemRequestBuilderInternal(urlTplParams, m.BaseRequestBuilder.RequestAdapter)
}
// NewAdminOrgsRequestBuilderInternal instantiates a new AdminOrgsRequestBuilder and sets the default values.
func NewAdminOrgsRequestBuilderInternal(pathParameters map[string]string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter)(*AdminOrgsRequestBuilder) {
    m := &AdminOrgsRequestBuilder{
        BaseRequestBuilder: *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewBaseRequestBuilder(requestAdapter, "{+baseurl}/api/admin/orgs", pathParameters),
    }
    return m
}
// NewAdminOrgsRequestBuilder instantiates a new AdminOrgsRequestBuilder and sets the default values.
func NewAdminOrgsRequestBuilder(rawUrl string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter)(*AdminOrgsRequestBuilder) {
    urlParams := make(map[string]string)
    urlParams["request-raw-url"] = rawUrl
    return NewAdminOrgsRequestBuilderInternal(urlParams, requestAdapter)
}
