// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package api

import (
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f "github.com/microsoft/kiota-abstractions-go"
)

// AdminOrgsOrgIdDomainsRequestBuilder builds and executes requests for operations under \api\admin\orgs\:orgId\domains
type AdminOrgsOrgIdDomainsRequestBuilder struct {
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.BaseRequestBuilder
}
// NewAdminOrgsOrgIdDomainsRequestBuilderInternal instantiates a new AdminOrgsOrgIdDomainsRequestBuilder and sets the default values.
func NewAdminOrgsOrgIdDomainsRequestBuilderInternal(pathParameters map[string]string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter)(*AdminOrgsOrgIdDomainsRequestBuilder) {
    m := &AdminOrgsOrgIdDomainsRequestBuilder{
        BaseRequestBuilder: *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewBaseRequestBuilder(requestAdapter, "{+baseurl}/api/admin/orgs/:orgId/domains", pathParameters),
    }
    return m
}
// NewAdminOrgsOrgIdDomainsRequestBuilder instantiates a new AdminOrgsOrgIdDomainsRequestBuilder and sets the default values.
func NewAdminOrgsOrgIdDomainsRequestBuilder(rawUrl string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter)(*AdminOrgsOrgIdDomainsRequestBuilder) {
    urlParams := make(map[string]string)
    urlParams["request-raw-url"] = rawUrl
    return NewAdminOrgsOrgIdDomainsRequestBuilderInternal(urlParams, requestAdapter)
}
// Domain the Domain property
// returns a *AdminOrgsOrgIdDomainsDomainRequestBuilder when successful
func (m *AdminOrgsOrgIdDomainsRequestBuilder) Domain()(*AdminOrgsOrgIdDomainsDomainRequestBuilder) {
    return NewAdminOrgsOrgIdDomainsDomainRequestBuilderInternal(m.BaseRequestBuilder.PathParameters, m.BaseRequestBuilder.RequestAdapter)
}
