// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package api

import (
    "context"
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f "github.com/microsoft/kiota-abstractions-go"
    i561e97a8befe7661a44c8f54600992b4207a3a0cf6770e5559949bc276de2e22 "github.com/google/uuid"
    i8905b30da6c1d2a87a239cfc7fb4da19fec8b7c521471730fa009da8140d0df4 "github.com/nbrglm/nexeres/sdks/nexeres-go/models"
)

// AdminOrgsItemRolesRequestBuilder builds and executes requests for operations under \api\admin\orgs\{orgId}\roles
type AdminOrgsItemRolesRequestBuilder struct {
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.BaseRequestBuilder
}
// AdminOrgsItemRolesRequestBuilderPostRequestConfiguration configuration for the request such as headers, query parameters, and middleware options.
type AdminOrgsItemRolesRequestBuilderPostRequestConfiguration struct {
    // Request headers
    Headers *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestHeaders
    // Request options
    Options []i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestOption
}
// ByRoleId gets an item from the github.com/nbrglm/nexeres/sdks/nexeres-go.api.admin.orgs.item.roles.item collection
// Deprecated: This indexer is deprecated and will be removed in the next major version. Use the one with the typed parameter instead.
// returns a *AdminOrgsItemRolesWithRoleItemRequestBuilder when successful
func (m *AdminOrgsItemRolesRequestBuilder) ByRoleId(roleId string)(*AdminOrgsItemRolesWithRoleItemRequestBuilder) {
    urlTplParams := make(map[string]string)
    for idx, item := range m.BaseRequestBuilder.PathParameters {
        urlTplParams[idx] = item
    }
    if roleId != "" {
        urlTplParams["roleId"] = roleId
    }
    return NewAdminOrgsItemRolesWithRoleItemRequestBuilderInternal(urlTplParams, m.BaseRequestBuilder.RequestAdapter)
}
// ByRoleIdGuid gets an item from the github.com/nbrglm/nexeres/sdks/nexeres-go.api.admin.orgs.item.roles.item collection
// returns a *AdminOrgsItemRolesWithRoleItemRequestBuilder when successful
func (m *AdminOrgsItemRolesRequestBuilder) ByRoleIdGuid(roleId i561e97a8befe7661a44c8f54600992b4207a3a0cf6770e5559949bc276de2e22.UUID)(*AdminOrgsItemRolesWithRoleItemRequestBuilder) {
    urlTplParams := make(map[string]string)
    for idx, item := range m.BaseRequestBuilder.PathParameters {
        urlTplParams[idx] = item
    }
    urlTplParams["roleId"] = roleId.String()
    return NewAdminOrgsItemRolesWithRoleItemRequestBuilderInternal(urlTplParams, m.BaseRequestBuilder.RequestAdapter)
}
// NewAdminOrgsItemRolesRequestBuilderInternal instantiates a new AdminOrgsItemRolesRequestBuilder and sets the default values.
func NewAdminOrgsItemRolesRequestBuilderInternal(pathParameters map[string]string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter)(*AdminOrgsItemRolesRequestBuilder) {
    m := &AdminOrgsItemRolesRequestBuilder{
        BaseRequestBuilder: *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewBaseRequestBuilder(requestAdapter, "{+baseurl}/api/admin/orgs/{orgId}/roles", pathParameters),
    }
    return m
}
// NewAdminOrgsItemRolesRequestBuilder instantiates a new AdminOrgsItemRolesRequestBuilder and sets the default values.
func NewAdminOrgsItemRolesRequestBuilder(rawUrl string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter)(*AdminOrgsItemRolesRequestBuilder) {
    urlParams := make(map[string]string)
    urlParams["request-raw-url"] = rawUrl
    return NewAdminOrgsItemRolesRequestBuilderInternal(urlParams, requestAdapter)
}
// Post create a new role for an organization.
// returns a AdminCreateRoleResponseable when successful
// returns a ErrorResponse error when the service returns a 400 status code
// returns a ErrorResponse error when the service returns a 401 status code
// returns a ErrorResponse error when the service returns a 404 status code
// returns a ErrorResponse error when the service returns a 500 status code
func (m *AdminOrgsItemRolesRequestBuilder) Post(ctx context.Context, body i8905b30da6c1d2a87a239cfc7fb4da19fec8b7c521471730fa009da8140d0df4.AdminCreateRoleRequestable, requestConfiguration *AdminOrgsItemRolesRequestBuilderPostRequestConfiguration)(i8905b30da6c1d2a87a239cfc7fb4da19fec8b7c521471730fa009da8140d0df4.AdminCreateRoleResponseable, error) {
    requestInfo, err := m.ToPostRequestInformation(ctx, body, requestConfiguration);
    if err != nil {
        return nil, err
    }
    errorMapping := i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.ErrorMappings {
        "400": i8905b30da6c1d2a87a239cfc7fb4da19fec8b7c521471730fa009da8140d0df4.CreateErrorResponseFromDiscriminatorValue,
        "401": i8905b30da6c1d2a87a239cfc7fb4da19fec8b7c521471730fa009da8140d0df4.CreateErrorResponseFromDiscriminatorValue,
        "404": i8905b30da6c1d2a87a239cfc7fb4da19fec8b7c521471730fa009da8140d0df4.CreateErrorResponseFromDiscriminatorValue,
        "500": i8905b30da6c1d2a87a239cfc7fb4da19fec8b7c521471730fa009da8140d0df4.CreateErrorResponseFromDiscriminatorValue,
    }
    res, err := m.BaseRequestBuilder.RequestAdapter.Send(ctx, requestInfo, i8905b30da6c1d2a87a239cfc7fb4da19fec8b7c521471730fa009da8140d0df4.CreateAdminCreateRoleResponseFromDiscriminatorValue, errorMapping)
    if err != nil {
        return nil, err
    }
    if res == nil {
        return nil, nil
    }
    return res.(i8905b30da6c1d2a87a239cfc7fb4da19fec8b7c521471730fa009da8140d0df4.AdminCreateRoleResponseable), nil
}
// ToPostRequestInformation create a new role for an organization.
// returns a *RequestInformation when successful
func (m *AdminOrgsItemRolesRequestBuilder) ToPostRequestInformation(ctx context.Context, body i8905b30da6c1d2a87a239cfc7fb4da19fec8b7c521471730fa009da8140d0df4.AdminCreateRoleRequestable, requestConfiguration *AdminOrgsItemRolesRequestBuilderPostRequestConfiguration)(*i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestInformation, error) {
    requestInfo := i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewRequestInformationWithMethodAndUrlTemplateAndPathParameters(i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.POST, m.BaseRequestBuilder.UrlTemplate, m.BaseRequestBuilder.PathParameters)
    if requestConfiguration != nil {
        requestInfo.Headers.AddAll(requestConfiguration.Headers)
        requestInfo.AddRequestOptions(requestConfiguration.Options)
    }
    requestInfo.Headers.TryAdd("Accept", "application/json")
    err := requestInfo.SetContentFromParsable(ctx, m.BaseRequestBuilder.RequestAdapter, "application/json", body)
    if err != nil {
        return nil, err
    }
    return requestInfo, nil
}
// WithUrl returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
// returns a *AdminOrgsItemRolesRequestBuilder when successful
func (m *AdminOrgsItemRolesRequestBuilder) WithUrl(rawUrl string)(*AdminOrgsItemRolesRequestBuilder) {
    return NewAdminOrgsItemRolesRequestBuilder(rawUrl, m.BaseRequestBuilder.RequestAdapter);
}
