// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package api

import (
    "context"
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f "github.com/microsoft/kiota-abstractions-go"
    i8905b30da6c1d2a87a239cfc7fb4da19fec8b7c521471730fa009da8140d0df4 "github.com/nbrglm/nexeres/sdks/nexeres-go/models"
)

// AuthFlowWithFlowItemRequestBuilder builds and executes requests for operations under \api\auth\flow\{flowId}
type AuthFlowWithFlowItemRequestBuilder struct {
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.BaseRequestBuilder
}
// AuthFlowWithFlowItemRequestBuilderGetRequestConfiguration configuration for the request such as headers, query parameters, and middleware options.
type AuthFlowWithFlowItemRequestBuilderGetRequestConfiguration struct {
    // Request headers
    Headers *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestHeaders
    // Request options
    Options []i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestOption
}
// NewAuthFlowWithFlowItemRequestBuilderInternal instantiates a new AuthFlowWithFlowItemRequestBuilder and sets the default values.
func NewAuthFlowWithFlowItemRequestBuilderInternal(pathParameters map[string]string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter)(*AuthFlowWithFlowItemRequestBuilder) {
    m := &AuthFlowWithFlowItemRequestBuilder{
        BaseRequestBuilder: *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewBaseRequestBuilder(requestAdapter, "{+baseurl}/api/auth/flow/{flowId}", pathParameters),
    }
    return m
}
// NewAuthFlowWithFlowItemRequestBuilder instantiates a new AuthFlowWithFlowItemRequestBuilder and sets the default values.
func NewAuthFlowWithFlowItemRequestBuilder(rawUrl string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter)(*AuthFlowWithFlowItemRequestBuilder) {
    urlParams := make(map[string]string)
    urlParams["request-raw-url"] = rawUrl
    return NewAuthFlowWithFlowItemRequestBuilderInternal(urlParams, requestAdapter)
}
// Get retrieve authentication flow details by flow ID.
// returns a AuthGetFlowResponseable when successful
// returns a ErrorResponse error when the service returns a 400 status code
// returns a ErrorResponse error when the service returns a 401 status code
// returns a ErrorResponse error when the service returns a 404 status code
// returns a ErrorResponse error when the service returns a 500 status code
func (m *AuthFlowWithFlowItemRequestBuilder) Get(ctx context.Context, requestConfiguration *AuthFlowWithFlowItemRequestBuilderGetRequestConfiguration)(i8905b30da6c1d2a87a239cfc7fb4da19fec8b7c521471730fa009da8140d0df4.AuthGetFlowResponseable, error) {
    requestInfo, err := m.ToGetRequestInformation(ctx, requestConfiguration);
    if err != nil {
        return nil, err
    }
    errorMapping := i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.ErrorMappings {
        "400": i8905b30da6c1d2a87a239cfc7fb4da19fec8b7c521471730fa009da8140d0df4.CreateErrorResponseFromDiscriminatorValue,
        "401": i8905b30da6c1d2a87a239cfc7fb4da19fec8b7c521471730fa009da8140d0df4.CreateErrorResponseFromDiscriminatorValue,
        "404": i8905b30da6c1d2a87a239cfc7fb4da19fec8b7c521471730fa009da8140d0df4.CreateErrorResponseFromDiscriminatorValue,
        "500": i8905b30da6c1d2a87a239cfc7fb4da19fec8b7c521471730fa009da8140d0df4.CreateErrorResponseFromDiscriminatorValue,
    }
    res, err := m.BaseRequestBuilder.RequestAdapter.Send(ctx, requestInfo, i8905b30da6c1d2a87a239cfc7fb4da19fec8b7c521471730fa009da8140d0df4.CreateAuthGetFlowResponseFromDiscriminatorValue, errorMapping)
    if err != nil {
        return nil, err
    }
    if res == nil {
        return nil, nil
    }
    return res.(i8905b30da6c1d2a87a239cfc7fb4da19fec8b7c521471730fa009da8140d0df4.AuthGetFlowResponseable), nil
}
// ToGetRequestInformation retrieve authentication flow details by flow ID.
// returns a *RequestInformation when successful
func (m *AuthFlowWithFlowItemRequestBuilder) ToGetRequestInformation(ctx context.Context, requestConfiguration *AuthFlowWithFlowItemRequestBuilderGetRequestConfiguration)(*i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestInformation, error) {
    requestInfo := i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewRequestInformationWithMethodAndUrlTemplateAndPathParameters(i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.GET, m.BaseRequestBuilder.UrlTemplate, m.BaseRequestBuilder.PathParameters)
    if requestConfiguration != nil {
        requestInfo.Headers.AddAll(requestConfiguration.Headers)
        requestInfo.AddRequestOptions(requestConfiguration.Options)
    }
    requestInfo.Headers.TryAdd("Accept", "application/json")
    return requestInfo, nil
}
// WithUrl returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
// returns a *AuthFlowWithFlowItemRequestBuilder when successful
func (m *AuthFlowWithFlowItemRequestBuilder) WithUrl(rawUrl string)(*AuthFlowWithFlowItemRequestBuilder) {
    return NewAuthFlowWithFlowItemRequestBuilder(rawUrl, m.BaseRequestBuilder.RequestAdapter);
}
