// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package api

import (
    "context"
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f "github.com/microsoft/kiota-abstractions-go"
    i8905b30da6c1d2a87a239cfc7fb4da19fec8b7c521471730fa009da8140d0df4 "github.com/nbrglm/nexeres/sdks/nexeres-go/models"
)

// AuthRefreshRequestBuilder builds and executes requests for operations under \api\auth\refresh
type AuthRefreshRequestBuilder struct {
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.BaseRequestBuilder
}
// AuthRefreshRequestBuilderPostRequestConfiguration configuration for the request such as headers, query parameters, and middleware options.
type AuthRefreshRequestBuilderPostRequestConfiguration struct {
    // Request headers
    Headers *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestHeaders
    // Request options
    Options []i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestOption
}
// NewAuthRefreshRequestBuilderInternal instantiates a new AuthRefreshRequestBuilder and sets the default values.
func NewAuthRefreshRequestBuilderInternal(pathParameters map[string]string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter)(*AuthRefreshRequestBuilder) {
    m := &AuthRefreshRequestBuilder{
        BaseRequestBuilder: *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewBaseRequestBuilder(requestAdapter, "{+baseurl}/api/auth/refresh", pathParameters),
    }
    return m
}
// NewAuthRefreshRequestBuilder instantiates a new AuthRefreshRequestBuilder and sets the default values.
func NewAuthRefreshRequestBuilder(rawUrl string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter)(*AuthRefreshRequestBuilder) {
    urlParams := make(map[string]string)
    urlParams["request-raw-url"] = rawUrl
    return NewAuthRefreshRequestBuilderInternal(urlParams, requestAdapter)
}
// Post refresh authentication tokens.
// returns a AuthRefreshResponseable when successful
// returns a ErrorResponse error when the service returns a 400 status code
// returns a ErrorResponse error when the service returns a 401 status code
// returns a ErrorResponse error when the service returns a 500 status code
func (m *AuthRefreshRequestBuilder) Post(ctx context.Context, body i8905b30da6c1d2a87a239cfc7fb4da19fec8b7c521471730fa009da8140d0df4.AuthRefreshRequestable, requestConfiguration *AuthRefreshRequestBuilderPostRequestConfiguration)(i8905b30da6c1d2a87a239cfc7fb4da19fec8b7c521471730fa009da8140d0df4.AuthRefreshResponseable, error) {
    requestInfo, err := m.ToPostRequestInformation(ctx, body, requestConfiguration);
    if err != nil {
        return nil, err
    }
    errorMapping := i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.ErrorMappings {
        "400": i8905b30da6c1d2a87a239cfc7fb4da19fec8b7c521471730fa009da8140d0df4.CreateErrorResponseFromDiscriminatorValue,
        "401": i8905b30da6c1d2a87a239cfc7fb4da19fec8b7c521471730fa009da8140d0df4.CreateErrorResponseFromDiscriminatorValue,
        "500": i8905b30da6c1d2a87a239cfc7fb4da19fec8b7c521471730fa009da8140d0df4.CreateErrorResponseFromDiscriminatorValue,
    }
    res, err := m.BaseRequestBuilder.RequestAdapter.Send(ctx, requestInfo, i8905b30da6c1d2a87a239cfc7fb4da19fec8b7c521471730fa009da8140d0df4.CreateAuthRefreshResponseFromDiscriminatorValue, errorMapping)
    if err != nil {
        return nil, err
    }
    if res == nil {
        return nil, nil
    }
    return res.(i8905b30da6c1d2a87a239cfc7fb4da19fec8b7c521471730fa009da8140d0df4.AuthRefreshResponseable), nil
}
// ToPostRequestInformation refresh authentication tokens.
// returns a *RequestInformation when successful
func (m *AuthRefreshRequestBuilder) ToPostRequestInformation(ctx context.Context, body i8905b30da6c1d2a87a239cfc7fb4da19fec8b7c521471730fa009da8140d0df4.AuthRefreshRequestable, requestConfiguration *AuthRefreshRequestBuilderPostRequestConfiguration)(*i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestInformation, error) {
    requestInfo := i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewRequestInformationWithMethodAndUrlTemplateAndPathParameters(i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.POST, m.BaseRequestBuilder.UrlTemplate, m.BaseRequestBuilder.PathParameters)
    if requestConfiguration != nil {
        requestInfo.Headers.AddAll(requestConfiguration.Headers)
        requestInfo.AddRequestOptions(requestConfiguration.Options)
    }
    requestInfo.Headers.TryAdd("Accept", "application/json")
    err := requestInfo.SetContentFromParsable(ctx, m.BaseRequestBuilder.RequestAdapter, "application/json", body)
    if err != nil {
        return nil, err
    }
    return requestInfo, nil
}
// WithUrl returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
// returns a *AuthRefreshRequestBuilder when successful
func (m *AuthRefreshRequestBuilder) WithUrl(rawUrl string)(*AuthRefreshRequestBuilder) {
    return NewAuthRefreshRequestBuilder(rawUrl, m.BaseRequestBuilder.RequestAdapter);
}
