// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package api

import (
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f "github.com/microsoft/kiota-abstractions-go"
)

// AuthVerifyEmailRequestBuilder builds and executes requests for operations under \api\auth\verify-email
type AuthVerifyEmailRequestBuilder struct {
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.BaseRequestBuilder
}
// NewAuthVerifyEmailRequestBuilderInternal instantiates a new AuthVerifyEmailRequestBuilder and sets the default values.
func NewAuthVerifyEmailRequestBuilderInternal(pathParameters map[string]string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter)(*AuthVerifyEmailRequestBuilder) {
    m := &AuthVerifyEmailRequestBuilder{
        BaseRequestBuilder: *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewBaseRequestBuilder(requestAdapter, "{+baseurl}/api/auth/verify-email", pathParameters),
    }
    return m
}
// NewAuthVerifyEmailRequestBuilder instantiates a new AuthVerifyEmailRequestBuilder and sets the default values.
func NewAuthVerifyEmailRequestBuilder(rawUrl string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter)(*AuthVerifyEmailRequestBuilder) {
    urlParams := make(map[string]string)
    urlParams["request-raw-url"] = rawUrl
    return NewAuthVerifyEmailRequestBuilderInternal(urlParams, requestAdapter)
}
// Send the send property
// returns a *AuthVerifyEmailSendRequestBuilder when successful
func (m *AuthVerifyEmailRequestBuilder) Send()(*AuthVerifyEmailSendRequestBuilder) {
    return NewAuthVerifyEmailSendRequestBuilderInternal(m.BaseRequestBuilder.PathParameters, m.BaseRequestBuilder.RequestAdapter)
}
// Verify the verify property
// returns a *AuthVerifyEmailVerifyRequestBuilder when successful
func (m *AuthVerifyEmailRequestBuilder) Verify()(*AuthVerifyEmailVerifyRequestBuilder) {
    return NewAuthVerifyEmailVerifyRequestBuilderInternal(m.BaseRequestBuilder.PathParameters, m.BaseRequestBuilder.RequestAdapter)
}
