// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package api

import (
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f "github.com/microsoft/kiota-abstractions-go"
    i561e97a8befe7661a44c8f54600992b4207a3a0cf6770e5559949bc276de2e22 "github.com/google/uuid"
)

// AuthFlowRequestBuilder builds and executes requests for operations under \api\auth\flow
type AuthFlowRequestBuilder struct {
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.BaseRequestBuilder
}
// ByFlowId gets an item from the github.com/nbrglm/nexeres/sdks/nexeres-go.api.auth.flow.item collection
// Deprecated: This indexer is deprecated and will be removed in the next major version. Use the one with the typed parameter instead.
// returns a *AuthFlowWithFlowItemRequestBuilder when successful
func (m *AuthFlowRequestBuilder) ByFlowId(flowId string)(*AuthFlowWithFlowItemRequestBuilder) {
    urlTplParams := make(map[string]string)
    for idx, item := range m.BaseRequestBuilder.PathParameters {
        urlTplParams[idx] = item
    }
    if flowId != "" {
        urlTplParams["flowId"] = flowId
    }
    return NewAuthFlowWithFlowItemRequestBuilderInternal(urlTplParams, m.BaseRequestBuilder.RequestAdapter)
}
// ByFlowIdGuid gets an item from the github.com/nbrglm/nexeres/sdks/nexeres-go.api.auth.flow.item collection
// returns a *AuthFlowWithFlowItemRequestBuilder when successful
func (m *AuthFlowRequestBuilder) ByFlowIdGuid(flowId i561e97a8befe7661a44c8f54600992b4207a3a0cf6770e5559949bc276de2e22.UUID)(*AuthFlowWithFlowItemRequestBuilder) {
    urlTplParams := make(map[string]string)
    for idx, item := range m.BaseRequestBuilder.PathParameters {
        urlTplParams[idx] = item
    }
    urlTplParams["flowId"] = flowId.String()
    return NewAuthFlowWithFlowItemRequestBuilderInternal(urlTplParams, m.BaseRequestBuilder.RequestAdapter)
}
// NewAuthFlowRequestBuilderInternal instantiates a new AuthFlowRequestBuilder and sets the default values.
func NewAuthFlowRequestBuilderInternal(pathParameters map[string]string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter)(*AuthFlowRequestBuilder) {
    m := &AuthFlowRequestBuilder{
        BaseRequestBuilder: *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewBaseRequestBuilder(requestAdapter, "{+baseurl}/api/auth/flow", pathParameters),
    }
    return m
}
// NewAuthFlowRequestBuilder instantiates a new AuthFlowRequestBuilder and sets the default values.
func NewAuthFlowRequestBuilder(rawUrl string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter)(*AuthFlowRequestBuilder) {
    urlParams := make(map[string]string)
    urlParams["request-raw-url"] = rawUrl
    return NewAuthFlowRequestBuilderInternal(urlParams, requestAdapter)
}
