// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package api

import (
    "context"
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f "github.com/microsoft/kiota-abstractions-go"
    i8905b30da6c1d2a87a239cfc7fb4da19fec8b7c521471730fa009da8140d0df4 "github.com/nbrglm/nexeres/sdks/nexeres-go/models"
)

// AuthVerifyEmailSendRequestBuilder builds and executes requests for operations under \api\auth\verify-email\send
type AuthVerifyEmailSendRequestBuilder struct {
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.BaseRequestBuilder
}
// AuthVerifyEmailSendRequestBuilderPostRequestConfiguration configuration for the request such as headers, query parameters, and middleware options.
type AuthVerifyEmailSendRequestBuilderPostRequestConfiguration struct {
    // Request headers
    Headers *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestHeaders
    // Request options
    Options []i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestOption
}
// NewAuthVerifyEmailSendRequestBuilderInternal instantiates a new AuthVerifyEmailSendRequestBuilder and sets the default values.
func NewAuthVerifyEmailSendRequestBuilderInternal(pathParameters map[string]string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter)(*AuthVerifyEmailSendRequestBuilder) {
    m := &AuthVerifyEmailSendRequestBuilder{
        BaseRequestBuilder: *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewBaseRequestBuilder(requestAdapter, "{+baseurl}/api/auth/verify-email/send", pathParameters),
    }
    return m
}
// NewAuthVerifyEmailSendRequestBuilder instantiates a new AuthVerifyEmailSendRequestBuilder and sets the default values.
func NewAuthVerifyEmailSendRequestBuilder(rawUrl string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter)(*AuthVerifyEmailSendRequestBuilder) {
    urlParams := make(map[string]string)
    urlParams["request-raw-url"] = rawUrl
    return NewAuthVerifyEmailSendRequestBuilderInternal(urlParams, requestAdapter)
}
// Post send a verification email to user.
// returns a AuthSendVerificationEmailResponseable when successful
// returns a ErrorResponse error when the service returns a 400 status code
// returns a ErrorResponse error when the service returns a 401 status code
// returns a ErrorResponse error when the service returns a 500 status code
func (m *AuthVerifyEmailSendRequestBuilder) Post(ctx context.Context, body i8905b30da6c1d2a87a239cfc7fb4da19fec8b7c521471730fa009da8140d0df4.AuthSendVerificationEmailRequestable, requestConfiguration *AuthVerifyEmailSendRequestBuilderPostRequestConfiguration)(i8905b30da6c1d2a87a239cfc7fb4da19fec8b7c521471730fa009da8140d0df4.AuthSendVerificationEmailResponseable, error) {
    requestInfo, err := m.ToPostRequestInformation(ctx, body, requestConfiguration);
    if err != nil {
        return nil, err
    }
    errorMapping := i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.ErrorMappings {
        "400": i8905b30da6c1d2a87a239cfc7fb4da19fec8b7c521471730fa009da8140d0df4.CreateErrorResponseFromDiscriminatorValue,
        "401": i8905b30da6c1d2a87a239cfc7fb4da19fec8b7c521471730fa009da8140d0df4.CreateErrorResponseFromDiscriminatorValue,
        "500": i8905b30da6c1d2a87a239cfc7fb4da19fec8b7c521471730fa009da8140d0df4.CreateErrorResponseFromDiscriminatorValue,
    }
    res, err := m.BaseRequestBuilder.RequestAdapter.Send(ctx, requestInfo, i8905b30da6c1d2a87a239cfc7fb4da19fec8b7c521471730fa009da8140d0df4.CreateAuthSendVerificationEmailResponseFromDiscriminatorValue, errorMapping)
    if err != nil {
        return nil, err
    }
    if res == nil {
        return nil, nil
    }
    return res.(i8905b30da6c1d2a87a239cfc7fb4da19fec8b7c521471730fa009da8140d0df4.AuthSendVerificationEmailResponseable), nil
}
// ToPostRequestInformation send a verification email to user.
// returns a *RequestInformation when successful
func (m *AuthVerifyEmailSendRequestBuilder) ToPostRequestInformation(ctx context.Context, body i8905b30da6c1d2a87a239cfc7fb4da19fec8b7c521471730fa009da8140d0df4.AuthSendVerificationEmailRequestable, requestConfiguration *AuthVerifyEmailSendRequestBuilderPostRequestConfiguration)(*i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestInformation, error) {
    requestInfo := i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewRequestInformationWithMethodAndUrlTemplateAndPathParameters(i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.POST, m.BaseRequestBuilder.UrlTemplate, m.BaseRequestBuilder.PathParameters)
    if requestConfiguration != nil {
        requestInfo.Headers.AddAll(requestConfiguration.Headers)
        requestInfo.AddRequestOptions(requestConfiguration.Options)
    }
    requestInfo.Headers.TryAdd("Accept", "application/json")
    err := requestInfo.SetContentFromParsable(ctx, m.BaseRequestBuilder.RequestAdapter, "application/json", body)
    if err != nil {
        return nil, err
    }
    return requestInfo, nil
}
// WithUrl returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
// returns a *AuthVerifyEmailSendRequestBuilder when successful
func (m *AuthVerifyEmailSendRequestBuilder) WithUrl(rawUrl string)(*AuthVerifyEmailSendRequestBuilder) {
    return NewAuthVerifyEmailSendRequestBuilder(rawUrl, m.BaseRequestBuilder.RequestAdapter);
}
