// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package api

import (
    "context"
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f "github.com/microsoft/kiota-abstractions-go"
    i8905b30da6c1d2a87a239cfc7fb4da19fec8b7c521471730fa009da8140d0df4 "github.com/nbrglm/nexeres/sdks/nexeres-go/models"
)

// SysAdminOrgsWithOrgItemRequestBuilder builds and executes requests for operations under \api\sys\admin\orgs\{orgId}
type SysAdminOrgsWithOrgItemRequestBuilder struct {
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.BaseRequestBuilder
}
// SysAdminOrgsWithOrgItemRequestBuilderDeleteRequestConfiguration configuration for the request such as headers, query parameters, and middleware options.
type SysAdminOrgsWithOrgItemRequestBuilderDeleteRequestConfiguration struct {
    // Request headers
    Headers *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestHeaders
    // Request options
    Options []i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestOption
}
// SysAdminOrgsWithOrgItemRequestBuilderGetRequestConfiguration configuration for the request such as headers, query parameters, and middleware options.
type SysAdminOrgsWithOrgItemRequestBuilderGetRequestConfiguration struct {
    // Request headers
    Headers *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestHeaders
    // Request options
    Options []i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestOption
}
// NewSysAdminOrgsWithOrgItemRequestBuilderInternal instantiates a new SysAdminOrgsWithOrgItemRequestBuilder and sets the default values.
func NewSysAdminOrgsWithOrgItemRequestBuilderInternal(pathParameters map[string]string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter)(*SysAdminOrgsWithOrgItemRequestBuilder) {
    m := &SysAdminOrgsWithOrgItemRequestBuilder{
        BaseRequestBuilder: *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewBaseRequestBuilder(requestAdapter, "{+baseurl}/api/sys/admin/orgs/{orgId}", pathParameters),
    }
    return m
}
// NewSysAdminOrgsWithOrgItemRequestBuilder instantiates a new SysAdminOrgsWithOrgItemRequestBuilder and sets the default values.
func NewSysAdminOrgsWithOrgItemRequestBuilder(rawUrl string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter)(*SysAdminOrgsWithOrgItemRequestBuilder) {
    urlParams := make(map[string]string)
    urlParams["request-raw-url"] = rawUrl
    return NewSysAdminOrgsWithOrgItemRequestBuilderInternal(urlParams, requestAdapter)
}
// Delete deletes an organization.
// returns a SysAdminDeleteOrgResponseable when successful
// returns a ErrorResponse error when the service returns a 400 status code
// returns a ErrorResponse error when the service returns a 401 status code
// returns a ErrorResponse error when the service returns a 404 status code
// returns a ErrorResponse error when the service returns a 500 status code
func (m *SysAdminOrgsWithOrgItemRequestBuilder) Delete(ctx context.Context, requestConfiguration *SysAdminOrgsWithOrgItemRequestBuilderDeleteRequestConfiguration)(i8905b30da6c1d2a87a239cfc7fb4da19fec8b7c521471730fa009da8140d0df4.SysAdminDeleteOrgResponseable, error) {
    requestInfo, err := m.ToDeleteRequestInformation(ctx, requestConfiguration);
    if err != nil {
        return nil, err
    }
    errorMapping := i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.ErrorMappings {
        "400": i8905b30da6c1d2a87a239cfc7fb4da19fec8b7c521471730fa009da8140d0df4.CreateErrorResponseFromDiscriminatorValue,
        "401": i8905b30da6c1d2a87a239cfc7fb4da19fec8b7c521471730fa009da8140d0df4.CreateErrorResponseFromDiscriminatorValue,
        "404": i8905b30da6c1d2a87a239cfc7fb4da19fec8b7c521471730fa009da8140d0df4.CreateErrorResponseFromDiscriminatorValue,
        "500": i8905b30da6c1d2a87a239cfc7fb4da19fec8b7c521471730fa009da8140d0df4.CreateErrorResponseFromDiscriminatorValue,
    }
    res, err := m.BaseRequestBuilder.RequestAdapter.Send(ctx, requestInfo, i8905b30da6c1d2a87a239cfc7fb4da19fec8b7c521471730fa009da8140d0df4.CreateSysAdminDeleteOrgResponseFromDiscriminatorValue, errorMapping)
    if err != nil {
        return nil, err
    }
    if res == nil {
        return nil, nil
    }
    return res.(i8905b30da6c1d2a87a239cfc7fb4da19fec8b7c521471730fa009da8140d0df4.SysAdminDeleteOrgResponseable), nil
}
// Get retrieve an organization by ID.
// returns a SysAdminGetOrgResponseable when successful
// returns a ErrorResponse error when the service returns a 400 status code
// returns a ErrorResponse error when the service returns a 401 status code
// returns a ErrorResponse error when the service returns a 404 status code
// returns a ErrorResponse error when the service returns a 500 status code
func (m *SysAdminOrgsWithOrgItemRequestBuilder) Get(ctx context.Context, requestConfiguration *SysAdminOrgsWithOrgItemRequestBuilderGetRequestConfiguration)(i8905b30da6c1d2a87a239cfc7fb4da19fec8b7c521471730fa009da8140d0df4.SysAdminGetOrgResponseable, error) {
    requestInfo, err := m.ToGetRequestInformation(ctx, requestConfiguration);
    if err != nil {
        return nil, err
    }
    errorMapping := i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.ErrorMappings {
        "400": i8905b30da6c1d2a87a239cfc7fb4da19fec8b7c521471730fa009da8140d0df4.CreateErrorResponseFromDiscriminatorValue,
        "401": i8905b30da6c1d2a87a239cfc7fb4da19fec8b7c521471730fa009da8140d0df4.CreateErrorResponseFromDiscriminatorValue,
        "404": i8905b30da6c1d2a87a239cfc7fb4da19fec8b7c521471730fa009da8140d0df4.CreateErrorResponseFromDiscriminatorValue,
        "500": i8905b30da6c1d2a87a239cfc7fb4da19fec8b7c521471730fa009da8140d0df4.CreateErrorResponseFromDiscriminatorValue,
    }
    res, err := m.BaseRequestBuilder.RequestAdapter.Send(ctx, requestInfo, i8905b30da6c1d2a87a239cfc7fb4da19fec8b7c521471730fa009da8140d0df4.CreateSysAdminGetOrgResponseFromDiscriminatorValue, errorMapping)
    if err != nil {
        return nil, err
    }
    if res == nil {
        return nil, nil
    }
    return res.(i8905b30da6c1d2a87a239cfc7fb4da19fec8b7c521471730fa009da8140d0df4.SysAdminGetOrgResponseable), nil
}
// ToDeleteRequestInformation deletes an organization.
// returns a *RequestInformation when successful
func (m *SysAdminOrgsWithOrgItemRequestBuilder) ToDeleteRequestInformation(ctx context.Context, requestConfiguration *SysAdminOrgsWithOrgItemRequestBuilderDeleteRequestConfiguration)(*i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestInformation, error) {
    requestInfo := i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewRequestInformationWithMethodAndUrlTemplateAndPathParameters(i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.DELETE, m.BaseRequestBuilder.UrlTemplate, m.BaseRequestBuilder.PathParameters)
    if requestConfiguration != nil {
        requestInfo.Headers.AddAll(requestConfiguration.Headers)
        requestInfo.AddRequestOptions(requestConfiguration.Options)
    }
    requestInfo.Headers.TryAdd("Accept", "application/json")
    return requestInfo, nil
}
// ToGetRequestInformation retrieve an organization by ID.
// returns a *RequestInformation when successful
func (m *SysAdminOrgsWithOrgItemRequestBuilder) ToGetRequestInformation(ctx context.Context, requestConfiguration *SysAdminOrgsWithOrgItemRequestBuilderGetRequestConfiguration)(*i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestInformation, error) {
    requestInfo := i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewRequestInformationWithMethodAndUrlTemplateAndPathParameters(i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.GET, m.BaseRequestBuilder.UrlTemplate, m.BaseRequestBuilder.PathParameters)
    if requestConfiguration != nil {
        requestInfo.Headers.AddAll(requestConfiguration.Headers)
        requestInfo.AddRequestOptions(requestConfiguration.Options)
    }
    requestInfo.Headers.TryAdd("Accept", "application/json")
    return requestInfo, nil
}
// WithUrl returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
// returns a *SysAdminOrgsWithOrgItemRequestBuilder when successful
func (m *SysAdminOrgsWithOrgItemRequestBuilder) WithUrl(rawUrl string)(*SysAdminOrgsWithOrgItemRequestBuilder) {
    return NewSysAdminOrgsWithOrgItemRequestBuilder(rawUrl, m.BaseRequestBuilder.RequestAdapter);
}
