// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package api

import (
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f "github.com/microsoft/kiota-abstractions-go"
)

// SysAdminRequestBuilder builds and executes requests for operations under \api\sys\admin
type SysAdminRequestBuilder struct {
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.BaseRequestBuilder
}
// Config the config property
// returns a *SysAdminConfigRequestBuilder when successful
func (m *SysAdminRequestBuilder) Config()(*SysAdminConfigRequestBuilder) {
    return NewSysAdminConfigRequestBuilderInternal(m.BaseRequestBuilder.PathParameters, m.BaseRequestBuilder.RequestAdapter)
}
// NewSysAdminRequestBuilderInternal instantiates a new SysAdminRequestBuilder and sets the default values.
func NewSysAdminRequestBuilderInternal(pathParameters map[string]string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter)(*SysAdminRequestBuilder) {
    m := &SysAdminRequestBuilder{
        BaseRequestBuilder: *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewBaseRequestBuilder(requestAdapter, "{+baseurl}/api/sys/admin", pathParameters),
    }
    return m
}
// NewSysAdminRequestBuilder instantiates a new SysAdminRequestBuilder and sets the default values.
func NewSysAdminRequestBuilder(rawUrl string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter)(*SysAdminRequestBuilder) {
    urlParams := make(map[string]string)
    urlParams["request-raw-url"] = rawUrl
    return NewSysAdminRequestBuilderInternal(urlParams, requestAdapter)
}
// Orgs the orgs property
// returns a *SysAdminOrgsRequestBuilder when successful
func (m *SysAdminRequestBuilder) Orgs()(*SysAdminOrgsRequestBuilder) {
    return NewSysAdminOrgsRequestBuilderInternal(m.BaseRequestBuilder.PathParameters, m.BaseRequestBuilder.RequestAdapter)
}
