/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { type AdditionalDataHolder, type ApiError, type Parsable, type ParseNode, type SerializationWriter } from '@microsoft/kiota-abstractions';

/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {ErrorResponse}
 */
// @ts-ignore
export function createErrorResponseFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoErrorResponse;
}
/**
 * The deserialization information for the current model
 * @param ErrorResponse The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoErrorResponse(errorResponse: Partial<ErrorResponse> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "debug": n => { errorResponse.debug = n.getStringValue(); },
        "message": n => { errorResponse.messageEscaped = n.getStringValue(); },
    }
}
export interface ErrorResponse extends AdditionalDataHolder, ApiError, Parsable {
    /**
     * DebugMessage is a technical message that can be used for debugging.
     */
    debug?: string | null;
    /**
     * Message is a user-friendly message that can be displayed to the end user.
     */
    messageEscaped?: string | null;
}
/**
 * Serializes information the current object
 * @param ErrorResponse The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeErrorResponse(writer: SerializationWriter, errorResponse: Partial<ErrorResponse> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!errorResponse || isSerializingDerivedType) { return; }
    writer.writeStringValue("debug", errorResponse.debug);
    writer.writeStringValue("message", errorResponse.messageEscaped);
    writer.writeAdditionalData(errorResponse.additionalData);
}
/* tslint:enable */
/* eslint-enable */
