/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { type WithFlowItemRequestBuilder, WithFlowItemRequestBuilderRequestsMetadata } from './item/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Guid, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/auth/flow
 */
export interface FlowRequestBuilder extends BaseRequestBuilder<FlowRequestBuilder> {
    /**
     * Gets an item from the ApiSdk.api.auth.flow.item collection
     * @param flowId Flow ID
     * @returns {WithFlowItemRequestBuilder}
     */
     byFlowId(flowId: Guid) : WithFlowItemRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const FlowRequestBuilderUriTemplate = "{+baseurl}/api/auth/flow";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const FlowRequestBuilderNavigationMetadata: Record<Exclude<keyof FlowRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    byFlowId: {
        requestsMetadata: WithFlowItemRequestBuilderRequestsMetadata,
        pathParametersMappings: ["flowId"],
    },
};
/* tslint:enable */
/* eslint-enable */
