/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { FlowRequestBuilderNavigationMetadata, type FlowRequestBuilder } from './flow/index.js';
// @ts-ignore
import { LoginRequestBuilderRequestsMetadata, type LoginRequestBuilder } from './login/index.js';
// @ts-ignore
import { LogoutRequestBuilderRequestsMetadata, type LogoutRequestBuilder } from './logout/index.js';
// @ts-ignore
import { RefreshRequestBuilderRequestsMetadata, type RefreshRequestBuilder } from './refresh/index.js';
// @ts-ignore
import { SignupRequestBuilderRequestsMetadata, type SignupRequestBuilder } from './signup/index.js';
// @ts-ignore
import { type VerifyEmailRequestBuilder, VerifyEmailRequestBuilderNavigationMetadata } from './verifyEmail/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/auth
 */
export interface AuthRequestBuilder extends BaseRequestBuilder<AuthRequestBuilder> {
    /**
     * The flow property
     */
    get flow(): FlowRequestBuilder;
    /**
     * The login property
     */
    get login(): LoginRequestBuilder;
    /**
     * The logout property
     */
    get logout(): LogoutRequestBuilder;
    /**
     * The refresh property
     */
    get refresh(): RefreshRequestBuilder;
    /**
     * The signup property
     */
    get signup(): SignupRequestBuilder;
    /**
     * The verifyEmail property
     */
    get verifyEmail(): VerifyEmailRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const AuthRequestBuilderUriTemplate = "{+baseurl}/api/auth";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const AuthRequestBuilderNavigationMetadata: Record<Exclude<keyof AuthRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    flow: {
        navigationMetadata: FlowRequestBuilderNavigationMetadata,
    },
    login: {
        requestsMetadata: LoginRequestBuilderRequestsMetadata,
    },
    logout: {
        requestsMetadata: LogoutRequestBuilderRequestsMetadata,
    },
    refresh: {
        requestsMetadata: RefreshRequestBuilderRequestsMetadata,
    },
    signup: {
        requestsMetadata: SignupRequestBuilderRequestsMetadata,
    },
    verifyEmail: {
        navigationMetadata: VerifyEmailRequestBuilderNavigationMetadata,
    },
};
/* tslint:enable */
/* eslint-enable */
