/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { SendRequestBuilderRequestsMetadata, type SendRequestBuilder } from './send/index.js';
// @ts-ignore
import { type VerifyRequestBuilder, VerifyRequestBuilderRequestsMetadata } from './verify/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/auth/verify-email
 */
export interface VerifyEmailRequestBuilder extends BaseRequestBuilder<VerifyEmailRequestBuilder> {
    /**
     * The send property
     */
    get send(): SendRequestBuilder;
    /**
     * The verify property
     */
    get verify(): VerifyRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const VerifyEmailRequestBuilderUriTemplate = "{+baseurl}/api/auth/verify-email";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const VerifyEmailRequestBuilderNavigationMetadata: Record<Exclude<keyof VerifyEmailRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    send: {
        requestsMetadata: SendRequestBuilderRequestsMetadata,
    },
    verify: {
        requestsMetadata: VerifyRequestBuilderRequestsMetadata,
    },
};
/* tslint:enable */
/* eslint-enable */
