// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package resquery
type FilterMode int

const (
    AND_FILTERMODE FilterMode = iota
    OR_FILTERMODE
)

func (i FilterMode) String() string {
    return []string{"AND", "OR"}[i]
}
func ParseFilterMode(v string) (any, error) {
    result := AND_FILTERMODE
    switch v {
        case "AND":
            result = AND_FILTERMODE
        case "OR":
            result = OR_FILTERMODE
        default:
            return nil, nil
    }
    return &result, nil
}
func SerializeFilterMode(values []FilterMode) []string {
    result := make([]string, len(values))
    for i, v := range values {
        result[i] = v.String()
    }
    return result
}
func (i FilterMode) isMultiValue() bool {
    return false
}
