// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package systemconfigpublicfacing

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// PublicFacingMultitenancyConfig multitenancy configuration for the public-facing Nexeres system.
type PublicFacingMultitenancyConfig struct {
    // Indicates if multitenancy is enabled.
    enabled *bool
}
// NewPublicFacingMultitenancyConfig instantiates a new PublicFacingMultitenancyConfig and sets the default values.
func NewPublicFacingMultitenancyConfig()(*PublicFacingMultitenancyConfig) {
    m := &PublicFacingMultitenancyConfig{
    }
    return m
}
// CreatePublicFacingMultitenancyConfigFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreatePublicFacingMultitenancyConfigFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewPublicFacingMultitenancyConfig(), nil
}
// GetEnabled gets the enabled property value. Indicates if multitenancy is enabled.
// returns a *bool when successful
func (m *PublicFacingMultitenancyConfig) GetEnabled()(*bool) {
    return m.enabled
}
// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error) when successful
func (m *PublicFacingMultitenancyConfig) GetFieldDeserializers()(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error)) {
    res := make(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error))
    res["enabled"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetBoolValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetEnabled(val)
        }
        return nil
    }
    return res
}
// Serialize serializes information the current object
func (m *PublicFacingMultitenancyConfig) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter)(error) {
    {
        err := writer.WriteBoolValue("enabled", m.GetEnabled())
        if err != nil {
            return err
        }
    }
    return nil
}
// SetEnabled sets the enabled property value. Indicates if multitenancy is enabled.
func (m *PublicFacingMultitenancyConfig) SetEnabled(value *bool)() {
    m.enabled = value
}
type PublicFacingMultitenancyConfigable interface {
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    GetEnabled()(*bool)
    SetEnabled(value *bool)()
}
