// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package systemconfigpublicfacing

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// PublicFacingNotificationsEmailConfigEndpoints endpoints configuration for email notifications.
type PublicFacingNotificationsEmailConfigEndpoints struct {
    // Your app's UI Endpoint URL to be included in the password reset emails.
    passwordReset *string
    // Your app's UI Endpoint URL to be included in the email verification messages.
    verification *string
}
// NewPublicFacingNotificationsEmailConfigEndpoints instantiates a new PublicFacingNotificationsEmailConfigEndpoints and sets the default values.
func NewPublicFacingNotificationsEmailConfigEndpoints()(*PublicFacingNotificationsEmailConfigEndpoints) {
    m := &PublicFacingNotificationsEmailConfigEndpoints{
    }
    return m
}
// CreatePublicFacingNotificationsEmailConfigEndpointsFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreatePublicFacingNotificationsEmailConfigEndpointsFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewPublicFacingNotificationsEmailConfigEndpoints(), nil
}
// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error) when successful
func (m *PublicFacingNotificationsEmailConfigEndpoints) GetFieldDeserializers()(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error)) {
    res := make(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error))
    res["passwordReset"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetPasswordReset(val)
        }
        return nil
    }
    res["verification"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetVerification(val)
        }
        return nil
    }
    return res
}
// GetPasswordReset gets the passwordReset property value. Your app's UI Endpoint URL to be included in the password reset emails.
// returns a *string when successful
func (m *PublicFacingNotificationsEmailConfigEndpoints) GetPasswordReset()(*string) {
    return m.passwordReset
}
// GetVerification gets the verification property value. Your app's UI Endpoint URL to be included in the email verification messages.
// returns a *string when successful
func (m *PublicFacingNotificationsEmailConfigEndpoints) GetVerification()(*string) {
    return m.verification
}
// Serialize serializes information the current object
func (m *PublicFacingNotificationsEmailConfigEndpoints) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter)(error) {
    {
        err := writer.WriteStringValue("passwordReset", m.GetPasswordReset())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("verification", m.GetVerification())
        if err != nil {
            return err
        }
    }
    return nil
}
// SetPasswordReset sets the passwordReset property value. Your app's UI Endpoint URL to be included in the password reset emails.
func (m *PublicFacingNotificationsEmailConfigEndpoints) SetPasswordReset(value *string)() {
    m.passwordReset = value
}
// SetVerification sets the verification property value. Your app's UI Endpoint URL to be included in the email verification messages.
func (m *PublicFacingNotificationsEmailConfigEndpoints) SetVerification(value *string)() {
    m.verification = value
}
type PublicFacingNotificationsEmailConfigEndpointsable interface {
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    GetPasswordReset()(*string)
    GetVerification()(*string)
    SetPasswordReset(value *string)()
    SetVerification(value *string)()
}
