// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package systemconfigpublicfacing

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// PublicFacingJWTConfig jWT configuration for the Nexeres system.
type PublicFacingJWTConfig struct {
    // The number of seconds in which an issued refresh token expires.
    refreshTokenExpirySeconds *int32
    // The number of seconds in which an issued session token/session expires.
    sessionTokenExpirySeconds *int32
}
// NewPublicFacingJWTConfig instantiates a new PublicFacingJWTConfig and sets the default values.
func NewPublicFacingJWTConfig()(*PublicFacingJWTConfig) {
    m := &PublicFacingJWTConfig{
    }
    return m
}
// CreatePublicFacingJWTConfigFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreatePublicFacingJWTConfigFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewPublicFacingJWTConfig(), nil
}
// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error) when successful
func (m *PublicFacingJWTConfig) GetFieldDeserializers()(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error)) {
    res := make(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error))
    res["refreshTokenExpirySeconds"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetInt32Value()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetRefreshTokenExpirySeconds(val)
        }
        return nil
    }
    res["sessionTokenExpirySeconds"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetInt32Value()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetSessionTokenExpirySeconds(val)
        }
        return nil
    }
    return res
}
// GetRefreshTokenExpirySeconds gets the refreshTokenExpirySeconds property value. The number of seconds in which an issued refresh token expires.
// returns a *int32 when successful
func (m *PublicFacingJWTConfig) GetRefreshTokenExpirySeconds()(*int32) {
    return m.refreshTokenExpirySeconds
}
// GetSessionTokenExpirySeconds gets the sessionTokenExpirySeconds property value. The number of seconds in which an issued session token/session expires.
// returns a *int32 when successful
func (m *PublicFacingJWTConfig) GetSessionTokenExpirySeconds()(*int32) {
    return m.sessionTokenExpirySeconds
}
// Serialize serializes information the current object
func (m *PublicFacingJWTConfig) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter)(error) {
    {
        err := writer.WriteInt32Value("refreshTokenExpirySeconds", m.GetRefreshTokenExpirySeconds())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteInt32Value("sessionTokenExpirySeconds", m.GetSessionTokenExpirySeconds())
        if err != nil {
            return err
        }
    }
    return nil
}
// SetRefreshTokenExpirySeconds sets the refreshTokenExpirySeconds property value. The number of seconds in which an issued refresh token expires.
func (m *PublicFacingJWTConfig) SetRefreshTokenExpirySeconds(value *int32)() {
    m.refreshTokenExpirySeconds = value
}
// SetSessionTokenExpirySeconds sets the sessionTokenExpirySeconds property value. The number of seconds in which an issued session token/session expires.
func (m *PublicFacingJWTConfig) SetSessionTokenExpirySeconds(value *int32)() {
    m.sessionTokenExpirySeconds = value
}
type PublicFacingJWTConfigable interface {
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    GetRefreshTokenExpirySeconds()(*int32)
    GetSessionTokenExpirySeconds()(*int32)
    SetRefreshTokenExpirySeconds(value *int32)()
    SetSessionTokenExpirySeconds(value *int32)()
}
