// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package systemconfigpublicfacing

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// PublicFacingPublicEndpointConfig public endpoint configuration for the Nexeres system.
type PublicFacingPublicEndpointConfig struct {
    // Base URL used for debugging purposes.
    debugBaseURL *string
    // Domain name for the public endpoint.
    domain *string
    // URL scheme (e.g., http, https) for the public endpoint.
    scheme *string
    // Subdomain for the public endpoint.
    subdomain *string
}
// NewPublicFacingPublicEndpointConfig instantiates a new PublicFacingPublicEndpointConfig and sets the default values.
func NewPublicFacingPublicEndpointConfig()(*PublicFacingPublicEndpointConfig) {
    m := &PublicFacingPublicEndpointConfig{
    }
    return m
}
// CreatePublicFacingPublicEndpointConfigFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreatePublicFacingPublicEndpointConfigFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewPublicFacingPublicEndpointConfig(), nil
}
// GetDebugBaseURL gets the debugBaseURL property value. Base URL used for debugging purposes.
// returns a *string when successful
func (m *PublicFacingPublicEndpointConfig) GetDebugBaseURL()(*string) {
    return m.debugBaseURL
}
// GetDomain gets the domain property value. Domain name for the public endpoint.
// returns a *string when successful
func (m *PublicFacingPublicEndpointConfig) GetDomain()(*string) {
    return m.domain
}
// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error) when successful
func (m *PublicFacingPublicEndpointConfig) GetFieldDeserializers()(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error)) {
    res := make(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error))
    res["debugBaseURL"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetDebugBaseURL(val)
        }
        return nil
    }
    res["domain"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetDomain(val)
        }
        return nil
    }
    res["scheme"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetScheme(val)
        }
        return nil
    }
    res["subdomain"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetSubdomain(val)
        }
        return nil
    }
    return res
}
// GetScheme gets the scheme property value. URL scheme (e.g., http, https) for the public endpoint.
// returns a *string when successful
func (m *PublicFacingPublicEndpointConfig) GetScheme()(*string) {
    return m.scheme
}
// GetSubdomain gets the subdomain property value. Subdomain for the public endpoint.
// returns a *string when successful
func (m *PublicFacingPublicEndpointConfig) GetSubdomain()(*string) {
    return m.subdomain
}
// Serialize serializes information the current object
func (m *PublicFacingPublicEndpointConfig) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter)(error) {
    {
        err := writer.WriteStringValue("debugBaseURL", m.GetDebugBaseURL())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("domain", m.GetDomain())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("scheme", m.GetScheme())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("subdomain", m.GetSubdomain())
        if err != nil {
            return err
        }
    }
    return nil
}
// SetDebugBaseURL sets the debugBaseURL property value. Base URL used for debugging purposes.
func (m *PublicFacingPublicEndpointConfig) SetDebugBaseURL(value *string)() {
    m.debugBaseURL = value
}
// SetDomain sets the domain property value. Domain name for the public endpoint.
func (m *PublicFacingPublicEndpointConfig) SetDomain(value *string)() {
    m.domain = value
}
// SetScheme sets the scheme property value. URL scheme (e.g., http, https) for the public endpoint.
func (m *PublicFacingPublicEndpointConfig) SetScheme(value *string)() {
    m.scheme = value
}
// SetSubdomain sets the subdomain property value. Subdomain for the public endpoint.
func (m *PublicFacingPublicEndpointConfig) SetSubdomain(value *string)() {
    m.subdomain = value
}
type PublicFacingPublicEndpointConfigable interface {
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    GetDebugBaseURL()(*string)
    GetDomain()(*string)
    GetScheme()(*string)
    GetSubdomain()(*string)
    SetDebugBaseURL(value *string)()
    SetDomain(value *string)()
    SetScheme(value *string)()
    SetSubdomain(value *string)()
}
