// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package handlers

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

type LoginRequest struct {
    // Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
    additionalData map[string]any
    // The email property
    email *string
    // Optional field to store in the flow data which can be fetched by the client after loginThis can be used to redirect the user to a specific page after loginor to maintain the state of the application.It is recommended to validate this field on the client side to prevent open redirect vulnerabilities.
    flowReturnTo *string
    // The password property
    password *string
    // The userAgent property
    userAgent *string
    // Metadata, required to issue tokens
    userIp *string
}
// NewLoginRequest instantiates a new LoginRequest and sets the default values.
func NewLoginRequest()(*LoginRequest) {
    m := &LoginRequest{
    }
    m.SetAdditionalData(make(map[string]any))
    return m
}
// CreateLoginRequestFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateLoginRequestFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewLoginRequest(), nil
}
// GetAdditionalData gets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
// returns a map[string]any when successful
func (m *LoginRequest) GetAdditionalData()(map[string]any) {
    return m.additionalData
}
// GetEmail gets the email property value. The email property
// returns a *string when successful
func (m *LoginRequest) GetEmail()(*string) {
    return m.email
}
// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error) when successful
func (m *LoginRequest) GetFieldDeserializers()(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error)) {
    res := make(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error))
    res["email"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetEmail(val)
        }
        return nil
    }
    res["flowReturnTo"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetFlowReturnTo(val)
        }
        return nil
    }
    res["password"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetPassword(val)
        }
        return nil
    }
    res["userAgent"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetUserAgent(val)
        }
        return nil
    }
    res["userIp"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetUserIp(val)
        }
        return nil
    }
    return res
}
// GetFlowReturnTo gets the flowReturnTo property value. Optional field to store in the flow data which can be fetched by the client after loginThis can be used to redirect the user to a specific page after loginor to maintain the state of the application.It is recommended to validate this field on the client side to prevent open redirect vulnerabilities.
// returns a *string when successful
func (m *LoginRequest) GetFlowReturnTo()(*string) {
    return m.flowReturnTo
}
// GetPassword gets the password property value. The password property
// returns a *string when successful
func (m *LoginRequest) GetPassword()(*string) {
    return m.password
}
// GetUserAgent gets the userAgent property value. The userAgent property
// returns a *string when successful
func (m *LoginRequest) GetUserAgent()(*string) {
    return m.userAgent
}
// GetUserIp gets the userIp property value. Metadata, required to issue tokens
// returns a *string when successful
func (m *LoginRequest) GetUserIp()(*string) {
    return m.userIp
}
// Serialize serializes information the current object
func (m *LoginRequest) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter)(error) {
    {
        err := writer.WriteStringValue("email", m.GetEmail())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("flowReturnTo", m.GetFlowReturnTo())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("password", m.GetPassword())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("userAgent", m.GetUserAgent())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("userIp", m.GetUserIp())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteAdditionalData(m.GetAdditionalData())
        if err != nil {
            return err
        }
    }
    return nil
}
// SetAdditionalData sets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
func (m *LoginRequest) SetAdditionalData(value map[string]any)() {
    m.additionalData = value
}
// SetEmail sets the email property value. The email property
func (m *LoginRequest) SetEmail(value *string)() {
    m.email = value
}
// SetFlowReturnTo sets the flowReturnTo property value. Optional field to store in the flow data which can be fetched by the client after loginThis can be used to redirect the user to a specific page after loginor to maintain the state of the application.It is recommended to validate this field on the client side to prevent open redirect vulnerabilities.
func (m *LoginRequest) SetFlowReturnTo(value *string)() {
    m.flowReturnTo = value
}
// SetPassword sets the password property value. The password property
func (m *LoginRequest) SetPassword(value *string)() {
    m.password = value
}
// SetUserAgent sets the userAgent property value. The userAgent property
func (m *LoginRequest) SetUserAgent(value *string)() {
    m.userAgent = value
}
// SetUserIp sets the userIp property value. Metadata, required to issue tokens
func (m *LoginRequest) SetUserIp(value *string)() {
    m.userIp = value
}
type LoginRequestable interface {
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.AdditionalDataHolder
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    GetEmail()(*string)
    GetFlowReturnTo()(*string)
    GetPassword()(*string)
    GetUserAgent()(*string)
    GetUserIp()(*string)
    SetEmail(value *string)()
    SetFlowReturnTo(value *string)()
    SetPassword(value *string)()
    SetUserAgent(value *string)()
    SetUserIp(value *string)()
}
