// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package config

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

type AdminsConfig struct {
    // Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
    additionalData map[string]any
    // The emails property
    emails []string
    // The sessionTimeoutSeconds property
    sessionTimeoutSeconds *int32
}
// NewAdminsConfig instantiates a new AdminsConfig and sets the default values.
func NewAdminsConfig()(*AdminsConfig) {
    m := &AdminsConfig{
    }
    m.SetAdditionalData(make(map[string]any))
    return m
}
// CreateAdminsConfigFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateAdminsConfigFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewAdminsConfig(), nil
}
// GetAdditionalData gets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
// returns a map[string]any when successful
func (m *AdminsConfig) GetAdditionalData()(map[string]any) {
    return m.additionalData
}
// GetEmails gets the emails property value. The emails property
// returns a []string when successful
func (m *AdminsConfig) GetEmails()([]string) {
    return m.emails
}
// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error) when successful
func (m *AdminsConfig) GetFieldDeserializers()(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error)) {
    res := make(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error))
    res["emails"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetCollectionOfPrimitiveValues("string")
        if err != nil {
            return err
        }
        if val != nil {
            res := make([]string, len(val))
            for i, v := range val {
                if v != nil {
                    res[i] = *(v.(*string))
                }
            }
            m.SetEmails(res)
        }
        return nil
    }
    res["sessionTimeoutSeconds"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetInt32Value()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetSessionTimeoutSeconds(val)
        }
        return nil
    }
    return res
}
// GetSessionTimeoutSeconds gets the sessionTimeoutSeconds property value. The sessionTimeoutSeconds property
// returns a *int32 when successful
func (m *AdminsConfig) GetSessionTimeoutSeconds()(*int32) {
    return m.sessionTimeoutSeconds
}
// Serialize serializes information the current object
func (m *AdminsConfig) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter)(error) {
    if m.GetEmails() != nil {
        err := writer.WriteCollectionOfStringValues("emails", m.GetEmails())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteInt32Value("sessionTimeoutSeconds", m.GetSessionTimeoutSeconds())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteAdditionalData(m.GetAdditionalData())
        if err != nil {
            return err
        }
    }
    return nil
}
// SetAdditionalData sets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
func (m *AdminsConfig) SetAdditionalData(value map[string]any)() {
    m.additionalData = value
}
// SetEmails sets the emails property value. The emails property
func (m *AdminsConfig) SetEmails(value []string)() {
    m.emails = value
}
// SetSessionTimeoutSeconds sets the sessionTimeoutSeconds property value. The sessionTimeoutSeconds property
func (m *AdminsConfig) SetSessionTimeoutSeconds(value *int32)() {
    m.sessionTimeoutSeconds = value
}
type AdminsConfigable interface {
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.AdditionalDataHolder
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    GetEmails()([]string)
    GetSessionTimeoutSeconds()(*int32)
    SetEmails(value []string)()
    SetSessionTimeoutSeconds(value *int32)()
}
