// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package config

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

type CORSConfig struct {
    // Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
    additionalData map[string]any
    // Allowed origins for CORS requests.Note: Using "*" WILL NOT work.The following origins are allowed by default:In debug mode, you can set the public.debugBaseURL to allow any url.In production mode, this is allowed:- https://{public.domain}- https://{public.subdomain}.{public.domain}Any other domains, even other subdomains of {public.domain} will not be allowed by default.Allowing a domain WOULD NOT allow all its subdomains.You need to explicitly allow subdomains by specifying them here.The following formats work:allowedOrigins:- "https://*.example.com"- "https://xyz.example.com"- "https://example.com"
    allowedOrigins []string
}
// NewCORSConfig instantiates a new CORSConfig and sets the default values.
func NewCORSConfig()(*CORSConfig) {
    m := &CORSConfig{
    }
    m.SetAdditionalData(make(map[string]any))
    return m
}
// CreateCORSConfigFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateCORSConfigFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewCORSConfig(), nil
}
// GetAdditionalData gets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
// returns a map[string]any when successful
func (m *CORSConfig) GetAdditionalData()(map[string]any) {
    return m.additionalData
}
// GetAllowedOrigins gets the allowedOrigins property value. Allowed origins for CORS requests.Note: Using "*" WILL NOT work.The following origins are allowed by default:In debug mode, you can set the public.debugBaseURL to allow any url.In production mode, this is allowed:- https://{public.domain}- https://{public.subdomain}.{public.domain}Any other domains, even other subdomains of {public.domain} will not be allowed by default.Allowing a domain WOULD NOT allow all its subdomains.You need to explicitly allow subdomains by specifying them here.The following formats work:allowedOrigins:- "https://*.example.com"- "https://xyz.example.com"- "https://example.com"
// returns a []string when successful
func (m *CORSConfig) GetAllowedOrigins()([]string) {
    return m.allowedOrigins
}
// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error) when successful
func (m *CORSConfig) GetFieldDeserializers()(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error)) {
    res := make(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error))
    res["allowedOrigins"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetCollectionOfPrimitiveValues("string")
        if err != nil {
            return err
        }
        if val != nil {
            res := make([]string, len(val))
            for i, v := range val {
                if v != nil {
                    res[i] = *(v.(*string))
                }
            }
            m.SetAllowedOrigins(res)
        }
        return nil
    }
    return res
}
// Serialize serializes information the current object
func (m *CORSConfig) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter)(error) {
    if m.GetAllowedOrigins() != nil {
        err := writer.WriteCollectionOfStringValues("allowedOrigins", m.GetAllowedOrigins())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteAdditionalData(m.GetAdditionalData())
        if err != nil {
            return err
        }
    }
    return nil
}
// SetAdditionalData sets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
func (m *CORSConfig) SetAdditionalData(value map[string]any)() {
    m.additionalData = value
}
// SetAllowedOrigins sets the allowedOrigins property value. Allowed origins for CORS requests.Note: Using "*" WILL NOT work.The following origins are allowed by default:In debug mode, you can set the public.debugBaseURL to allow any url.In production mode, this is allowed:- https://{public.domain}- https://{public.subdomain}.{public.domain}Any other domains, even other subdomains of {public.domain} will not be allowed by default.Allowing a domain WOULD NOT allow all its subdomains.You need to explicitly allow subdomains by specifying them here.The following formats work:allowedOrigins:- "https://*.example.com"- "https://xyz.example.com"- "https://example.com"
func (m *CORSConfig) SetAllowedOrigins(value []string)() {
    m.allowedOrigins = value
}
type CORSConfigable interface {
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.AdditionalDataHolder
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    GetAllowedOrigins()([]string)
    SetAllowedOrigins(value []string)()
}
