// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package config

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

type EmailConfig struct {
    // Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
    additionalData map[string]any
    // Endpoints used in email templates
    endpoints EmailTemplateEndpointsable
    // One of "smtp", "sendgrid", "ses"
    provider *string
    // SendGrid specific settings
    sendGrid SendGridConfigable
    // AWS SES specific settings
    ses SESConfigable
    // SMTP specific settings
    smtp SMTPConfigable
}
// NewEmailConfig instantiates a new EmailConfig and sets the default values.
func NewEmailConfig()(*EmailConfig) {
    m := &EmailConfig{
    }
    m.SetAdditionalData(make(map[string]any))
    return m
}
// CreateEmailConfigFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateEmailConfigFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewEmailConfig(), nil
}
// GetAdditionalData gets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
// returns a map[string]any when successful
func (m *EmailConfig) GetAdditionalData()(map[string]any) {
    return m.additionalData
}
// GetEndpoints gets the endpoints property value. Endpoints used in email templates
// returns a EmailTemplateEndpointsable when successful
func (m *EmailConfig) GetEndpoints()(EmailTemplateEndpointsable) {
    return m.endpoints
}
// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error) when successful
func (m *EmailConfig) GetFieldDeserializers()(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error)) {
    res := make(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error))
    res["endpoints"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetObjectValue(CreateEmailTemplateEndpointsFromDiscriminatorValue)
        if err != nil {
            return err
        }
        if val != nil {
            m.SetEndpoints(val.(EmailTemplateEndpointsable))
        }
        return nil
    }
    res["provider"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetProvider(val)
        }
        return nil
    }
    res["sendGrid"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetObjectValue(CreateSendGridConfigFromDiscriminatorValue)
        if err != nil {
            return err
        }
        if val != nil {
            m.SetSendGrid(val.(SendGridConfigable))
        }
        return nil
    }
    res["ses"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetObjectValue(CreateSESConfigFromDiscriminatorValue)
        if err != nil {
            return err
        }
        if val != nil {
            m.SetSes(val.(SESConfigable))
        }
        return nil
    }
    res["smtp"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetObjectValue(CreateSMTPConfigFromDiscriminatorValue)
        if err != nil {
            return err
        }
        if val != nil {
            m.SetSmtp(val.(SMTPConfigable))
        }
        return nil
    }
    return res
}
// GetProvider gets the provider property value. One of "smtp", "sendgrid", "ses"
// returns a *string when successful
func (m *EmailConfig) GetProvider()(*string) {
    return m.provider
}
// GetSendGrid gets the sendGrid property value. SendGrid specific settings
// returns a SendGridConfigable when successful
func (m *EmailConfig) GetSendGrid()(SendGridConfigable) {
    return m.sendGrid
}
// GetSes gets the ses property value. AWS SES specific settings
// returns a SESConfigable when successful
func (m *EmailConfig) GetSes()(SESConfigable) {
    return m.ses
}
// GetSmtp gets the smtp property value. SMTP specific settings
// returns a SMTPConfigable when successful
func (m *EmailConfig) GetSmtp()(SMTPConfigable) {
    return m.smtp
}
// Serialize serializes information the current object
func (m *EmailConfig) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter)(error) {
    {
        err := writer.WriteObjectValue("endpoints", m.GetEndpoints())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("provider", m.GetProvider())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteObjectValue("sendGrid", m.GetSendGrid())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteObjectValue("ses", m.GetSes())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteObjectValue("smtp", m.GetSmtp())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteAdditionalData(m.GetAdditionalData())
        if err != nil {
            return err
        }
    }
    return nil
}
// SetAdditionalData sets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
func (m *EmailConfig) SetAdditionalData(value map[string]any)() {
    m.additionalData = value
}
// SetEndpoints sets the endpoints property value. Endpoints used in email templates
func (m *EmailConfig) SetEndpoints(value EmailTemplateEndpointsable)() {
    m.endpoints = value
}
// SetProvider sets the provider property value. One of "smtp", "sendgrid", "ses"
func (m *EmailConfig) SetProvider(value *string)() {
    m.provider = value
}
// SetSendGrid sets the sendGrid property value. SendGrid specific settings
func (m *EmailConfig) SetSendGrid(value SendGridConfigable)() {
    m.sendGrid = value
}
// SetSes sets the ses property value. AWS SES specific settings
func (m *EmailConfig) SetSes(value SESConfigable)() {
    m.ses = value
}
// SetSmtp sets the smtp property value. SMTP specific settings
func (m *EmailConfig) SetSmtp(value SMTPConfigable)() {
    m.smtp = value
}
type EmailConfigable interface {
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.AdditionalDataHolder
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    GetEndpoints()(EmailTemplateEndpointsable)
    GetProvider()(*string)
    GetSendGrid()(SendGridConfigable)
    GetSes()(SESConfigable)
    GetSmtp()(SMTPConfigable)
    SetEndpoints(value EmailTemplateEndpointsable)()
    SetProvider(value *string)()
    SetSendGrid(value SendGridConfigable)()
    SetSes(value SESConfigable)()
    SetSmtp(value SMTPConfigable)()
}
