// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package config

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

type JWTConfig struct {
    // Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
    additionalData map[string]any
    // NOTE: Do not add the subdomain or domain you added in PublicConfig here.This is only for additional audiences.
    audiences []string
    // The refreshTokenExpirySeconds property
    refreshTokenExpirySeconds *int32
    // The sessionTokenExpirySeconds property
    sessionTokenExpirySeconds *int32
}
// NewJWTConfig instantiates a new JWTConfig and sets the default values.
func NewJWTConfig()(*JWTConfig) {
    m := &JWTConfig{
    }
    m.SetAdditionalData(make(map[string]any))
    return m
}
// CreateJWTConfigFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateJWTConfigFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewJWTConfig(), nil
}
// GetAdditionalData gets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
// returns a map[string]any when successful
func (m *JWTConfig) GetAdditionalData()(map[string]any) {
    return m.additionalData
}
// GetAudiences gets the audiences property value. NOTE: Do not add the subdomain or domain you added in PublicConfig here.This is only for additional audiences.
// returns a []string when successful
func (m *JWTConfig) GetAudiences()([]string) {
    return m.audiences
}
// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error) when successful
func (m *JWTConfig) GetFieldDeserializers()(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error)) {
    res := make(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error))
    res["audiences"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetCollectionOfPrimitiveValues("string")
        if err != nil {
            return err
        }
        if val != nil {
            res := make([]string, len(val))
            for i, v := range val {
                if v != nil {
                    res[i] = *(v.(*string))
                }
            }
            m.SetAudiences(res)
        }
        return nil
    }
    res["refreshTokenExpirySeconds"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetInt32Value()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetRefreshTokenExpirySeconds(val)
        }
        return nil
    }
    res["sessionTokenExpirySeconds"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetInt32Value()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetSessionTokenExpirySeconds(val)
        }
        return nil
    }
    return res
}
// GetRefreshTokenExpirySeconds gets the refreshTokenExpirySeconds property value. The refreshTokenExpirySeconds property
// returns a *int32 when successful
func (m *JWTConfig) GetRefreshTokenExpirySeconds()(*int32) {
    return m.refreshTokenExpirySeconds
}
// GetSessionTokenExpirySeconds gets the sessionTokenExpirySeconds property value. The sessionTokenExpirySeconds property
// returns a *int32 when successful
func (m *JWTConfig) GetSessionTokenExpirySeconds()(*int32) {
    return m.sessionTokenExpirySeconds
}
// Serialize serializes information the current object
func (m *JWTConfig) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter)(error) {
    if m.GetAudiences() != nil {
        err := writer.WriteCollectionOfStringValues("audiences", m.GetAudiences())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteInt32Value("refreshTokenExpirySeconds", m.GetRefreshTokenExpirySeconds())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteInt32Value("sessionTokenExpirySeconds", m.GetSessionTokenExpirySeconds())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteAdditionalData(m.GetAdditionalData())
        if err != nil {
            return err
        }
    }
    return nil
}
// SetAdditionalData sets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
func (m *JWTConfig) SetAdditionalData(value map[string]any)() {
    m.additionalData = value
}
// SetAudiences sets the audiences property value. NOTE: Do not add the subdomain or domain you added in PublicConfig here.This is only for additional audiences.
func (m *JWTConfig) SetAudiences(value []string)() {
    m.audiences = value
}
// SetRefreshTokenExpirySeconds sets the refreshTokenExpirySeconds property value. The refreshTokenExpirySeconds property
func (m *JWTConfig) SetRefreshTokenExpirySeconds(value *int32)() {
    m.refreshTokenExpirySeconds = value
}
// SetSessionTokenExpirySeconds sets the sessionTokenExpirySeconds property value. The sessionTokenExpirySeconds property
func (m *JWTConfig) SetSessionTokenExpirySeconds(value *int32)() {
    m.sessionTokenExpirySeconds = value
}
type JWTConfigable interface {
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.AdditionalDataHolder
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    GetAudiences()([]string)
    GetRefreshTokenExpirySeconds()(*int32)
    GetSessionTokenExpirySeconds()(*int32)
    SetAudiences(value []string)()
    SetRefreshTokenExpirySeconds(value *int32)()
    SetSessionTokenExpirySeconds(value *int32)()
}
