// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package config

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

type NexeresConfig struct {
    // Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
    additionalData map[string]any
    // The admins property
    admins AdminsConfigable
    // The branding property
    branding BrandingConfigable
    // The debug property
    debug *bool
    // The jwt property
    jwt JWTConfigable
    // The multitenancy property
    multitenancy MultitenancyConfigable
    // The notifications property
    notifications NotificationsConfigable
    // The observability property
    observability ObservabilityConfigable
    // The password property
    password PasswordConfigable
    // The publicEndpoint property
    publicEndpoint PublicEndpointConfigable
    // The security property
    security SecurityConfigable
    // The server property
    server ServerConfigable
    // The stores property
    stores StoresConfigable
}
// NewNexeresConfig instantiates a new NexeresConfig and sets the default values.
func NewNexeresConfig()(*NexeresConfig) {
    m := &NexeresConfig{
    }
    m.SetAdditionalData(make(map[string]any))
    return m
}
// CreateNexeresConfigFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateNexeresConfigFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewNexeresConfig(), nil
}
// GetAdditionalData gets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
// returns a map[string]any when successful
func (m *NexeresConfig) GetAdditionalData()(map[string]any) {
    return m.additionalData
}
// GetAdmins gets the admins property value. The admins property
// returns a AdminsConfigable when successful
func (m *NexeresConfig) GetAdmins()(AdminsConfigable) {
    return m.admins
}
// GetBranding gets the branding property value. The branding property
// returns a BrandingConfigable when successful
func (m *NexeresConfig) GetBranding()(BrandingConfigable) {
    return m.branding
}
// GetDebug gets the debug property value. The debug property
// returns a *bool when successful
func (m *NexeresConfig) GetDebug()(*bool) {
    return m.debug
}
// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error) when successful
func (m *NexeresConfig) GetFieldDeserializers()(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error)) {
    res := make(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error))
    res["admins"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetObjectValue(CreateAdminsConfigFromDiscriminatorValue)
        if err != nil {
            return err
        }
        if val != nil {
            m.SetAdmins(val.(AdminsConfigable))
        }
        return nil
    }
    res["branding"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetObjectValue(CreateBrandingConfigFromDiscriminatorValue)
        if err != nil {
            return err
        }
        if val != nil {
            m.SetBranding(val.(BrandingConfigable))
        }
        return nil
    }
    res["debug"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetBoolValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetDebug(val)
        }
        return nil
    }
    res["jwt"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetObjectValue(CreateJWTConfigFromDiscriminatorValue)
        if err != nil {
            return err
        }
        if val != nil {
            m.SetJwt(val.(JWTConfigable))
        }
        return nil
    }
    res["multitenancy"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetObjectValue(CreateMultitenancyConfigFromDiscriminatorValue)
        if err != nil {
            return err
        }
        if val != nil {
            m.SetMultitenancy(val.(MultitenancyConfigable))
        }
        return nil
    }
    res["notifications"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetObjectValue(CreateNotificationsConfigFromDiscriminatorValue)
        if err != nil {
            return err
        }
        if val != nil {
            m.SetNotifications(val.(NotificationsConfigable))
        }
        return nil
    }
    res["observability"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetObjectValue(CreateObservabilityConfigFromDiscriminatorValue)
        if err != nil {
            return err
        }
        if val != nil {
            m.SetObservability(val.(ObservabilityConfigable))
        }
        return nil
    }
    res["password"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetObjectValue(CreatePasswordConfigFromDiscriminatorValue)
        if err != nil {
            return err
        }
        if val != nil {
            m.SetPassword(val.(PasswordConfigable))
        }
        return nil
    }
    res["publicEndpoint"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetObjectValue(CreatePublicEndpointConfigFromDiscriminatorValue)
        if err != nil {
            return err
        }
        if val != nil {
            m.SetPublicEndpoint(val.(PublicEndpointConfigable))
        }
        return nil
    }
    res["security"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetObjectValue(CreateSecurityConfigFromDiscriminatorValue)
        if err != nil {
            return err
        }
        if val != nil {
            m.SetSecurity(val.(SecurityConfigable))
        }
        return nil
    }
    res["server"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetObjectValue(CreateServerConfigFromDiscriminatorValue)
        if err != nil {
            return err
        }
        if val != nil {
            m.SetServer(val.(ServerConfigable))
        }
        return nil
    }
    res["stores"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetObjectValue(CreateStoresConfigFromDiscriminatorValue)
        if err != nil {
            return err
        }
        if val != nil {
            m.SetStores(val.(StoresConfigable))
        }
        return nil
    }
    return res
}
// GetJwt gets the jwt property value. The jwt property
// returns a JWTConfigable when successful
func (m *NexeresConfig) GetJwt()(JWTConfigable) {
    return m.jwt
}
// GetMultitenancy gets the multitenancy property value. The multitenancy property
// returns a MultitenancyConfigable when successful
func (m *NexeresConfig) GetMultitenancy()(MultitenancyConfigable) {
    return m.multitenancy
}
// GetNotifications gets the notifications property value. The notifications property
// returns a NotificationsConfigable when successful
func (m *NexeresConfig) GetNotifications()(NotificationsConfigable) {
    return m.notifications
}
// GetObservability gets the observability property value. The observability property
// returns a ObservabilityConfigable when successful
func (m *NexeresConfig) GetObservability()(ObservabilityConfigable) {
    return m.observability
}
// GetPassword gets the password property value. The password property
// returns a PasswordConfigable when successful
func (m *NexeresConfig) GetPassword()(PasswordConfigable) {
    return m.password
}
// GetPublicEndpoint gets the publicEndpoint property value. The publicEndpoint property
// returns a PublicEndpointConfigable when successful
func (m *NexeresConfig) GetPublicEndpoint()(PublicEndpointConfigable) {
    return m.publicEndpoint
}
// GetSecurity gets the security property value. The security property
// returns a SecurityConfigable when successful
func (m *NexeresConfig) GetSecurity()(SecurityConfigable) {
    return m.security
}
// GetServer gets the server property value. The server property
// returns a ServerConfigable when successful
func (m *NexeresConfig) GetServer()(ServerConfigable) {
    return m.server
}
// GetStores gets the stores property value. The stores property
// returns a StoresConfigable when successful
func (m *NexeresConfig) GetStores()(StoresConfigable) {
    return m.stores
}
// Serialize serializes information the current object
func (m *NexeresConfig) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter)(error) {
    {
        err := writer.WriteObjectValue("admins", m.GetAdmins())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteObjectValue("branding", m.GetBranding())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteBoolValue("debug", m.GetDebug())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteObjectValue("jwt", m.GetJwt())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteObjectValue("multitenancy", m.GetMultitenancy())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteObjectValue("notifications", m.GetNotifications())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteObjectValue("observability", m.GetObservability())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteObjectValue("password", m.GetPassword())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteObjectValue("publicEndpoint", m.GetPublicEndpoint())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteObjectValue("security", m.GetSecurity())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteObjectValue("server", m.GetServer())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteObjectValue("stores", m.GetStores())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteAdditionalData(m.GetAdditionalData())
        if err != nil {
            return err
        }
    }
    return nil
}
// SetAdditionalData sets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
func (m *NexeresConfig) SetAdditionalData(value map[string]any)() {
    m.additionalData = value
}
// SetAdmins sets the admins property value. The admins property
func (m *NexeresConfig) SetAdmins(value AdminsConfigable)() {
    m.admins = value
}
// SetBranding sets the branding property value. The branding property
func (m *NexeresConfig) SetBranding(value BrandingConfigable)() {
    m.branding = value
}
// SetDebug sets the debug property value. The debug property
func (m *NexeresConfig) SetDebug(value *bool)() {
    m.debug = value
}
// SetJwt sets the jwt property value. The jwt property
func (m *NexeresConfig) SetJwt(value JWTConfigable)() {
    m.jwt = value
}
// SetMultitenancy sets the multitenancy property value. The multitenancy property
func (m *NexeresConfig) SetMultitenancy(value MultitenancyConfigable)() {
    m.multitenancy = value
}
// SetNotifications sets the notifications property value. The notifications property
func (m *NexeresConfig) SetNotifications(value NotificationsConfigable)() {
    m.notifications = value
}
// SetObservability sets the observability property value. The observability property
func (m *NexeresConfig) SetObservability(value ObservabilityConfigable)() {
    m.observability = value
}
// SetPassword sets the password property value. The password property
func (m *NexeresConfig) SetPassword(value PasswordConfigable)() {
    m.password = value
}
// SetPublicEndpoint sets the publicEndpoint property value. The publicEndpoint property
func (m *NexeresConfig) SetPublicEndpoint(value PublicEndpointConfigable)() {
    m.publicEndpoint = value
}
// SetSecurity sets the security property value. The security property
func (m *NexeresConfig) SetSecurity(value SecurityConfigable)() {
    m.security = value
}
// SetServer sets the server property value. The server property
func (m *NexeresConfig) SetServer(value ServerConfigable)() {
    m.server = value
}
// SetStores sets the stores property value. The stores property
func (m *NexeresConfig) SetStores(value StoresConfigable)() {
    m.stores = value
}
type NexeresConfigable interface {
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.AdditionalDataHolder
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    GetAdmins()(AdminsConfigable)
    GetBranding()(BrandingConfigable)
    GetDebug()(*bool)
    GetJwt()(JWTConfigable)
    GetMultitenancy()(MultitenancyConfigable)
    GetNotifications()(NotificationsConfigable)
    GetObservability()(ObservabilityConfigable)
    GetPassword()(PasswordConfigable)
    GetPublicEndpoint()(PublicEndpointConfigable)
    GetSecurity()(SecurityConfigable)
    GetServer()(ServerConfigable)
    GetStores()(StoresConfigable)
    SetAdmins(value AdminsConfigable)()
    SetBranding(value BrandingConfigable)()
    SetDebug(value *bool)()
    SetJwt(value JWTConfigable)()
    SetMultitenancy(value MultitenancyConfigable)()
    SetNotifications(value NotificationsConfigable)()
    SetObservability(value ObservabilityConfigable)()
    SetPassword(value PasswordConfigable)()
    SetPublicEndpoint(value PublicEndpointConfigable)()
    SetSecurity(value SecurityConfigable)()
    SetServer(value ServerConfigable)()
    SetStores(value StoresConfigable)()
}
