// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package config

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

type ObsCommonConfig struct {
    // Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
    additionalData map[string]any
    // The endpoint property
    endpoint *string
    // The headers property
    headers ObsCommonConfig_headersable
    // The path property
    path *string
    // must be one of "http/protobuf", "grpc", "stdout"stdout means no exporter, just log to stdout
    protocol *string
    // The withInsecure property
    withInsecure *bool
}
// NewObsCommonConfig instantiates a new ObsCommonConfig and sets the default values.
func NewObsCommonConfig()(*ObsCommonConfig) {
    m := &ObsCommonConfig{
    }
    m.SetAdditionalData(make(map[string]any))
    return m
}
// CreateObsCommonConfigFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateObsCommonConfigFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewObsCommonConfig(), nil
}
// GetAdditionalData gets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
// returns a map[string]any when successful
func (m *ObsCommonConfig) GetAdditionalData()(map[string]any) {
    return m.additionalData
}
// GetEndpoint gets the endpoint property value. The endpoint property
// returns a *string when successful
func (m *ObsCommonConfig) GetEndpoint()(*string) {
    return m.endpoint
}
// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error) when successful
func (m *ObsCommonConfig) GetFieldDeserializers()(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error)) {
    res := make(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error))
    res["endpoint"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetEndpoint(val)
        }
        return nil
    }
    res["headers"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetObjectValue(CreateObsCommonConfig_headersFromDiscriminatorValue)
        if err != nil {
            return err
        }
        if val != nil {
            m.SetHeaders(val.(ObsCommonConfig_headersable))
        }
        return nil
    }
    res["path"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetPath(val)
        }
        return nil
    }
    res["protocol"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetProtocol(val)
        }
        return nil
    }
    res["withInsecure"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetBoolValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetWithInsecure(val)
        }
        return nil
    }
    return res
}
// GetHeaders gets the headers property value. The headers property
// returns a ObsCommonConfig_headersable when successful
func (m *ObsCommonConfig) GetHeaders()(ObsCommonConfig_headersable) {
    return m.headers
}
// GetPath gets the path property value. The path property
// returns a *string when successful
func (m *ObsCommonConfig) GetPath()(*string) {
    return m.path
}
// GetProtocol gets the protocol property value. must be one of "http/protobuf", "grpc", "stdout"stdout means no exporter, just log to stdout
// returns a *string when successful
func (m *ObsCommonConfig) GetProtocol()(*string) {
    return m.protocol
}
// GetWithInsecure gets the withInsecure property value. The withInsecure property
// returns a *bool when successful
func (m *ObsCommonConfig) GetWithInsecure()(*bool) {
    return m.withInsecure
}
// Serialize serializes information the current object
func (m *ObsCommonConfig) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter)(error) {
    {
        err := writer.WriteStringValue("endpoint", m.GetEndpoint())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteObjectValue("headers", m.GetHeaders())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("path", m.GetPath())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("protocol", m.GetProtocol())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteBoolValue("withInsecure", m.GetWithInsecure())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteAdditionalData(m.GetAdditionalData())
        if err != nil {
            return err
        }
    }
    return nil
}
// SetAdditionalData sets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
func (m *ObsCommonConfig) SetAdditionalData(value map[string]any)() {
    m.additionalData = value
}
// SetEndpoint sets the endpoint property value. The endpoint property
func (m *ObsCommonConfig) SetEndpoint(value *string)() {
    m.endpoint = value
}
// SetHeaders sets the headers property value. The headers property
func (m *ObsCommonConfig) SetHeaders(value ObsCommonConfig_headersable)() {
    m.headers = value
}
// SetPath sets the path property value. The path property
func (m *ObsCommonConfig) SetPath(value *string)() {
    m.path = value
}
// SetProtocol sets the protocol property value. must be one of "http/protobuf", "grpc", "stdout"stdout means no exporter, just log to stdout
func (m *ObsCommonConfig) SetProtocol(value *string)() {
    m.protocol = value
}
// SetWithInsecure sets the withInsecure property value. The withInsecure property
func (m *ObsCommonConfig) SetWithInsecure(value *bool)() {
    m.withInsecure = value
}
type ObsCommonConfigable interface {
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.AdditionalDataHolder
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    GetEndpoint()(*string)
    GetHeaders()(ObsCommonConfig_headersable)
    GetPath()(*string)
    GetProtocol()(*string)
    GetWithInsecure()(*bool)
    SetEndpoint(value *string)()
    SetHeaders(value ObsCommonConfig_headersable)()
    SetPath(value *string)()
    SetProtocol(value *string)()
    SetWithInsecure(value *bool)()
}
