// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package config

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

type ObservabilityConfig struct {
    // Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
    additionalData map[string]any
    // The logs property
    logs LogsConfigable
    // The metrics property
    metrics MetricsConfigable
    // The tracing property
    tracing ObsCommonConfigable
}
// NewObservabilityConfig instantiates a new ObservabilityConfig and sets the default values.
func NewObservabilityConfig()(*ObservabilityConfig) {
    m := &ObservabilityConfig{
    }
    m.SetAdditionalData(make(map[string]any))
    return m
}
// CreateObservabilityConfigFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateObservabilityConfigFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewObservabilityConfig(), nil
}
// GetAdditionalData gets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
// returns a map[string]any when successful
func (m *ObservabilityConfig) GetAdditionalData()(map[string]any) {
    return m.additionalData
}
// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error) when successful
func (m *ObservabilityConfig) GetFieldDeserializers()(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error)) {
    res := make(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error))
    res["logs"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetObjectValue(CreateLogsConfigFromDiscriminatorValue)
        if err != nil {
            return err
        }
        if val != nil {
            m.SetLogs(val.(LogsConfigable))
        }
        return nil
    }
    res["metrics"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetObjectValue(CreateMetricsConfigFromDiscriminatorValue)
        if err != nil {
            return err
        }
        if val != nil {
            m.SetMetrics(val.(MetricsConfigable))
        }
        return nil
    }
    res["tracing"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetObjectValue(CreateObsCommonConfigFromDiscriminatorValue)
        if err != nil {
            return err
        }
        if val != nil {
            m.SetTracing(val.(ObsCommonConfigable))
        }
        return nil
    }
    return res
}
// GetLogs gets the logs property value. The logs property
// returns a LogsConfigable when successful
func (m *ObservabilityConfig) GetLogs()(LogsConfigable) {
    return m.logs
}
// GetMetrics gets the metrics property value. The metrics property
// returns a MetricsConfigable when successful
func (m *ObservabilityConfig) GetMetrics()(MetricsConfigable) {
    return m.metrics
}
// GetTracing gets the tracing property value. The tracing property
// returns a ObsCommonConfigable when successful
func (m *ObservabilityConfig) GetTracing()(ObsCommonConfigable) {
    return m.tracing
}
// Serialize serializes information the current object
func (m *ObservabilityConfig) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter)(error) {
    {
        err := writer.WriteObjectValue("logs", m.GetLogs())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteObjectValue("metrics", m.GetMetrics())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteObjectValue("tracing", m.GetTracing())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteAdditionalData(m.GetAdditionalData())
        if err != nil {
            return err
        }
    }
    return nil
}
// SetAdditionalData sets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
func (m *ObservabilityConfig) SetAdditionalData(value map[string]any)() {
    m.additionalData = value
}
// SetLogs sets the logs property value. The logs property
func (m *ObservabilityConfig) SetLogs(value LogsConfigable)() {
    m.logs = value
}
// SetMetrics sets the metrics property value. The metrics property
func (m *ObservabilityConfig) SetMetrics(value MetricsConfigable)() {
    m.metrics = value
}
// SetTracing sets the tracing property value. The tracing property
func (m *ObservabilityConfig) SetTracing(value ObsCommonConfigable)() {
    m.tracing = value
}
type ObservabilityConfigable interface {
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.AdditionalDataHolder
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    GetLogs()(LogsConfigable)
    GetMetrics()(MetricsConfigable)
    GetTracing()(ObsCommonConfigable)
    SetLogs(value LogsConfigable)()
    SetMetrics(value MetricsConfigable)()
    SetTracing(value ObsCommonConfigable)()
}
