// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package config

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

type PasswordConfig struct {
    // Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
    additionalData map[string]any
    // One of "argon2id", "bcrypt"
    algorithm *PasswordHashingAlgorithm
    // Parameters for Argon2id
    argon2idParams Argon2idParamsable
    // Cost for bcrypt
    bcryptCost *int32
}
// NewPasswordConfig instantiates a new PasswordConfig and sets the default values.
func NewPasswordConfig()(*PasswordConfig) {
    m := &PasswordConfig{
    }
    m.SetAdditionalData(make(map[string]any))
    return m
}
// CreatePasswordConfigFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreatePasswordConfigFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewPasswordConfig(), nil
}
// GetAdditionalData gets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
// returns a map[string]any when successful
func (m *PasswordConfig) GetAdditionalData()(map[string]any) {
    return m.additionalData
}
// GetAlgorithm gets the algorithm property value. One of "argon2id", "bcrypt"
// returns a *PasswordHashingAlgorithm when successful
func (m *PasswordConfig) GetAlgorithm()(*PasswordHashingAlgorithm) {
    return m.algorithm
}
// GetArgon2idParams gets the argon2idParams property value. Parameters for Argon2id
// returns a Argon2idParamsable when successful
func (m *PasswordConfig) GetArgon2idParams()(Argon2idParamsable) {
    return m.argon2idParams
}
// GetBcryptCost gets the bcryptCost property value. Cost for bcrypt
// returns a *int32 when successful
func (m *PasswordConfig) GetBcryptCost()(*int32) {
    return m.bcryptCost
}
// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error) when successful
func (m *PasswordConfig) GetFieldDeserializers()(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error)) {
    res := make(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error))
    res["algorithm"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetEnumValue(ParsePasswordHashingAlgorithm)
        if err != nil {
            return err
        }
        if val != nil {
            m.SetAlgorithm(val.(*PasswordHashingAlgorithm))
        }
        return nil
    }
    res["argon2idParams"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetObjectValue(CreateArgon2idParamsFromDiscriminatorValue)
        if err != nil {
            return err
        }
        if val != nil {
            m.SetArgon2idParams(val.(Argon2idParamsable))
        }
        return nil
    }
    res["bcryptCost"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetInt32Value()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetBcryptCost(val)
        }
        return nil
    }
    return res
}
// Serialize serializes information the current object
func (m *PasswordConfig) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter)(error) {
    if m.GetAlgorithm() != nil {
        cast := (*m.GetAlgorithm()).String()
        err := writer.WriteStringValue("algorithm", &cast)
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteObjectValue("argon2idParams", m.GetArgon2idParams())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteInt32Value("bcryptCost", m.GetBcryptCost())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteAdditionalData(m.GetAdditionalData())
        if err != nil {
            return err
        }
    }
    return nil
}
// SetAdditionalData sets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
func (m *PasswordConfig) SetAdditionalData(value map[string]any)() {
    m.additionalData = value
}
// SetAlgorithm sets the algorithm property value. One of "argon2id", "bcrypt"
func (m *PasswordConfig) SetAlgorithm(value *PasswordHashingAlgorithm)() {
    m.algorithm = value
}
// SetArgon2idParams sets the argon2idParams property value. Parameters for Argon2id
func (m *PasswordConfig) SetArgon2idParams(value Argon2idParamsable)() {
    m.argon2idParams = value
}
// SetBcryptCost sets the bcryptCost property value. Cost for bcrypt
func (m *PasswordConfig) SetBcryptCost(value *int32)() {
    m.bcryptCost = value
}
type PasswordConfigable interface {
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.AdditionalDataHolder
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    GetAlgorithm()(*PasswordHashingAlgorithm)
    GetArgon2idParams()(Argon2idParamsable)
    GetBcryptCost()(*int32)
    SetAlgorithm(value *PasswordHashingAlgorithm)()
    SetArgon2idParams(value Argon2idParamsable)()
    SetBcryptCost(value *int32)()
}
