// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package config
type PasswordHashingAlgorithm int

const (
    ARGON2ID_PASSWORDHASHINGALGORITHM PasswordHashingAlgorithm = iota
    BCRYPT_PASSWORDHASHINGALGORITHM
)

func (i PasswordHashingAlgorithm) String() string {
    return []string{"argon2id", "bcrypt"}[i]
}
func ParsePasswordHashingAlgorithm(v string) (any, error) {
    result := ARGON2ID_PASSWORDHASHINGALGORITHM
    switch v {
        case "argon2id":
            result = ARGON2ID_PASSWORDHASHINGALGORITHM
        case "bcrypt":
            result = BCRYPT_PASSWORDHASHINGALGORITHM
        default:
            return nil, nil
    }
    return &result, nil
}
func SerializePasswordHashingAlgorithm(values []PasswordHashingAlgorithm) []string {
    result := make([]string, len(values))
    for i, v := range values {
        result[i] = v.String()
    }
    return result
}
func (i PasswordHashingAlgorithm) isMultiValue() bool {
    return false
}
