// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package config

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

type RateLimitingConfig struct {
    // Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
    additionalData map[string]any
    // Default: 120-mFormat: <number>-<unit> where unit is one of "s" (second), "m" (minute), "h" (hour), "d" (day)
    rate *string
}
// NewRateLimitingConfig instantiates a new RateLimitingConfig and sets the default values.
func NewRateLimitingConfig()(*RateLimitingConfig) {
    m := &RateLimitingConfig{
    }
    m.SetAdditionalData(make(map[string]any))
    return m
}
// CreateRateLimitingConfigFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateRateLimitingConfigFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewRateLimitingConfig(), nil
}
// GetAdditionalData gets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
// returns a map[string]any when successful
func (m *RateLimitingConfig) GetAdditionalData()(map[string]any) {
    return m.additionalData
}
// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error) when successful
func (m *RateLimitingConfig) GetFieldDeserializers()(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error)) {
    res := make(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error))
    res["rate"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetRate(val)
        }
        return nil
    }
    return res
}
// GetRate gets the rate property value. Default: 120-mFormat: <number>-<unit> where unit is one of "s" (second), "m" (minute), "h" (hour), "d" (day)
// returns a *string when successful
func (m *RateLimitingConfig) GetRate()(*string) {
    return m.rate
}
// Serialize serializes information the current object
func (m *RateLimitingConfig) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter)(error) {
    {
        err := writer.WriteStringValue("rate", m.GetRate())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteAdditionalData(m.GetAdditionalData())
        if err != nil {
            return err
        }
    }
    return nil
}
// SetAdditionalData sets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
func (m *RateLimitingConfig) SetAdditionalData(value map[string]any)() {
    m.additionalData = value
}
// SetRate sets the rate property value. Default: 120-mFormat: <number>-<unit> where unit is one of "s" (second), "m" (minute), "h" (hour), "d" (day)
func (m *RateLimitingConfig) SetRate(value *string)() {
    m.rate = value
}
type RateLimitingConfigable interface {
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.AdditionalDataHolder
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    GetRate()(*string)
    SetRate(value *string)()
}
