// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package config

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

type ServerConfig struct {
    // Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
    additionalData map[string]any
    // The enableTLS property
    enableTLS *bool
    // The host property
    host *string
    // The instanceId property
    instanceId *string
    // The port property
    port *int32
}
// NewServerConfig instantiates a new ServerConfig and sets the default values.
func NewServerConfig()(*ServerConfig) {
    m := &ServerConfig{
    }
    m.SetAdditionalData(make(map[string]any))
    return m
}
// CreateServerConfigFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateServerConfigFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewServerConfig(), nil
}
// GetAdditionalData gets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
// returns a map[string]any when successful
func (m *ServerConfig) GetAdditionalData()(map[string]any) {
    return m.additionalData
}
// GetEnableTLS gets the enableTLS property value. The enableTLS property
// returns a *bool when successful
func (m *ServerConfig) GetEnableTLS()(*bool) {
    return m.enableTLS
}
// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error) when successful
func (m *ServerConfig) GetFieldDeserializers()(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error)) {
    res := make(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error))
    res["enableTLS"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetBoolValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetEnableTLS(val)
        }
        return nil
    }
    res["host"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetHost(val)
        }
        return nil
    }
    res["instanceId"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetInstanceId(val)
        }
        return nil
    }
    res["port"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetInt32Value()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetPort(val)
        }
        return nil
    }
    return res
}
// GetHost gets the host property value. The host property
// returns a *string when successful
func (m *ServerConfig) GetHost()(*string) {
    return m.host
}
// GetInstanceId gets the instanceId property value. The instanceId property
// returns a *string when successful
func (m *ServerConfig) GetInstanceId()(*string) {
    return m.instanceId
}
// GetPort gets the port property value. The port property
// returns a *int32 when successful
func (m *ServerConfig) GetPort()(*int32) {
    return m.port
}
// Serialize serializes information the current object
func (m *ServerConfig) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter)(error) {
    {
        err := writer.WriteBoolValue("enableTLS", m.GetEnableTLS())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("host", m.GetHost())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("instanceId", m.GetInstanceId())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteInt32Value("port", m.GetPort())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteAdditionalData(m.GetAdditionalData())
        if err != nil {
            return err
        }
    }
    return nil
}
// SetAdditionalData sets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
func (m *ServerConfig) SetAdditionalData(value map[string]any)() {
    m.additionalData = value
}
// SetEnableTLS sets the enableTLS property value. The enableTLS property
func (m *ServerConfig) SetEnableTLS(value *bool)() {
    m.enableTLS = value
}
// SetHost sets the host property value. The host property
func (m *ServerConfig) SetHost(value *string)() {
    m.host = value
}
// SetInstanceId sets the instanceId property value. The instanceId property
func (m *ServerConfig) SetInstanceId(value *string)() {
    m.instanceId = value
}
// SetPort sets the port property value. The port property
func (m *ServerConfig) SetPort(value *int32)() {
    m.port = value
}
type ServerConfigable interface {
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.AdditionalDataHolder
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    GetEnableTLS()(*bool)
    GetHost()(*string)
    GetInstanceId()(*string)
    GetPort()(*int32)
    SetEnableTLS(value *bool)()
    SetHost(value *string)()
    SetInstanceId(value *string)()
    SetPort(value *int32)()
}
