// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package config

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

type StoresConfig struct {
    // Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
    additionalData map[string]any
    // The postgresDSN property
    postgresDSN *string
    // The redis property
    redis RedisConfigable
    // The s3 property
    s3 S3Configable
}
// NewStoresConfig instantiates a new StoresConfig and sets the default values.
func NewStoresConfig()(*StoresConfig) {
    m := &StoresConfig{
    }
    m.SetAdditionalData(make(map[string]any))
    return m
}
// CreateStoresConfigFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateStoresConfigFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewStoresConfig(), nil
}
// GetAdditionalData gets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
// returns a map[string]any when successful
func (m *StoresConfig) GetAdditionalData()(map[string]any) {
    return m.additionalData
}
// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error) when successful
func (m *StoresConfig) GetFieldDeserializers()(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error)) {
    res := make(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error))
    res["postgresDSN"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetPostgresDSN(val)
        }
        return nil
    }
    res["redis"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetObjectValue(CreateRedisConfigFromDiscriminatorValue)
        if err != nil {
            return err
        }
        if val != nil {
            m.SetRedis(val.(RedisConfigable))
        }
        return nil
    }
    res["s3"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetObjectValue(CreateS3ConfigFromDiscriminatorValue)
        if err != nil {
            return err
        }
        if val != nil {
            m.SetS3(val.(S3Configable))
        }
        return nil
    }
    return res
}
// GetPostgresDSN gets the postgresDSN property value. The postgresDSN property
// returns a *string when successful
func (m *StoresConfig) GetPostgresDSN()(*string) {
    return m.postgresDSN
}
// GetRedis gets the redis property value. The redis property
// returns a RedisConfigable when successful
func (m *StoresConfig) GetRedis()(RedisConfigable) {
    return m.redis
}
// GetS3 gets the s3 property value. The s3 property
// returns a S3Configable when successful
func (m *StoresConfig) GetS3()(S3Configable) {
    return m.s3
}
// Serialize serializes information the current object
func (m *StoresConfig) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter)(error) {
    {
        err := writer.WriteStringValue("postgresDSN", m.GetPostgresDSN())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteObjectValue("redis", m.GetRedis())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteObjectValue("s3", m.GetS3())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteAdditionalData(m.GetAdditionalData())
        if err != nil {
            return err
        }
    }
    return nil
}
// SetAdditionalData sets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
func (m *StoresConfig) SetAdditionalData(value map[string]any)() {
    m.additionalData = value
}
// SetPostgresDSN sets the postgresDSN property value. The postgresDSN property
func (m *StoresConfig) SetPostgresDSN(value *string)() {
    m.postgresDSN = value
}
// SetRedis sets the redis property value. The redis property
func (m *StoresConfig) SetRedis(value RedisConfigable)() {
    m.redis = value
}
// SetS3 sets the s3 property value. The s3 property
func (m *StoresConfig) SetS3(value S3Configable)() {
    m.s3 = value
}
type StoresConfigable interface {
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.AdditionalDataHolder
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    GetPostgresDSN()(*string)
    GetRedis()(RedisConfigable)
    GetS3()(S3Configable)
    SetPostgresDSN(value *string)()
    SetRedis(value RedisConfigable)()
    SetS3(value S3Configable)()
}
