/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { type WithOrgItemRequestBuilder, WithOrgItemRequestBuilderNavigationMetadata, WithOrgItemRequestBuilderRequestsMetadata } from './item/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Guid, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/admin/orgs
 */
export interface OrgsRequestBuilder extends BaseRequestBuilder<OrgsRequestBuilder> {
    /**
     * Gets an item from the ApiSdk.api.admin.orgs.item collection
     * @param orgId Organization ID
     * @returns {WithOrgItemRequestBuilder}
     */
     byOrgId(orgId: Guid) : WithOrgItemRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const OrgsRequestBuilderUriTemplate = "{+baseurl}/api/admin/orgs";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const OrgsRequestBuilderNavigationMetadata: Record<Exclude<keyof OrgsRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    byOrgId: {
        requestsMetadata: WithOrgItemRequestBuilderRequestsMetadata,
        navigationMetadata: WithOrgItemRequestBuilderNavigationMetadata,
        pathParametersMappings: ["orgId"],
    },
};
/* tslint:enable */
/* eslint-enable */
