/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createAuthLogoutResponseFromDiscriminatorValue, createErrorResponseFromDiscriminatorValue, type AuthLogoutResponse, type ErrorResponse } from '../../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/auth/logout
 */
export interface LogoutRequestBuilder extends BaseRequestBuilder<LogoutRequestBuilder> {
    /**
     * Log out the current user. One of session or refresh token must be provided.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<AuthLogoutResponse>}
     * @throws {ErrorResponse} error when the service returns a 400 status code
     * @throws {ErrorResponse} error when the service returns a 401 status code
     * @throws {ErrorResponse} error when the service returns a 500 status code
     */
     post(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<AuthLogoutResponse | undefined>;
    /**
     * Log out the current user. One of session or refresh token must be provided.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const LogoutRequestBuilderUriTemplate = "{+baseurl}/api/auth/logout";
/**
 * Metadata for all the requests in the request builder.
 */
export const LogoutRequestBuilderRequestsMetadata: RequestsMetadata = {
    post: {
        uriTemplate: LogoutRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createErrorResponseFromDiscriminatorValue as ParsableFactory<Parsable>,
            401: createErrorResponseFromDiscriminatorValue as ParsableFactory<Parsable>,
            500: createErrorResponseFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createAuthLogoutResponseFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
