// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package db

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

type GetMinimalRolesForOrgRow struct {
    // Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
    additionalData map[string]any
    // The createdAt property
    createdAt *string
    // The id property
    id *string
    // The roleDesc property
    roleDesc *string
    // The roleName property
    roleName *string
    // The updatedAt property
    updatedAt *string
}
// NewGetMinimalRolesForOrgRow instantiates a new GetMinimalRolesForOrgRow and sets the default values.
func NewGetMinimalRolesForOrgRow()(*GetMinimalRolesForOrgRow) {
    m := &GetMinimalRolesForOrgRow{
    }
    m.SetAdditionalData(make(map[string]any))
    return m
}
// CreateGetMinimalRolesForOrgRowFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateGetMinimalRolesForOrgRowFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewGetMinimalRolesForOrgRow(), nil
}
// GetAdditionalData gets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
// returns a map[string]any when successful
func (m *GetMinimalRolesForOrgRow) GetAdditionalData()(map[string]any) {
    return m.additionalData
}
// GetCreatedAt gets the createdAt property value. The createdAt property
// returns a *string when successful
func (m *GetMinimalRolesForOrgRow) GetCreatedAt()(*string) {
    return m.createdAt
}
// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error) when successful
func (m *GetMinimalRolesForOrgRow) GetFieldDeserializers()(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error)) {
    res := make(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error))
    res["createdAt"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetCreatedAt(val)
        }
        return nil
    }
    res["id"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetId(val)
        }
        return nil
    }
    res["roleDesc"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetRoleDesc(val)
        }
        return nil
    }
    res["roleName"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetRoleName(val)
        }
        return nil
    }
    res["updatedAt"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetUpdatedAt(val)
        }
        return nil
    }
    return res
}
// GetId gets the id property value. The id property
// returns a *string when successful
func (m *GetMinimalRolesForOrgRow) GetId()(*string) {
    return m.id
}
// GetRoleDesc gets the roleDesc property value. The roleDesc property
// returns a *string when successful
func (m *GetMinimalRolesForOrgRow) GetRoleDesc()(*string) {
    return m.roleDesc
}
// GetRoleName gets the roleName property value. The roleName property
// returns a *string when successful
func (m *GetMinimalRolesForOrgRow) GetRoleName()(*string) {
    return m.roleName
}
// GetUpdatedAt gets the updatedAt property value. The updatedAt property
// returns a *string when successful
func (m *GetMinimalRolesForOrgRow) GetUpdatedAt()(*string) {
    return m.updatedAt
}
// Serialize serializes information the current object
func (m *GetMinimalRolesForOrgRow) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter)(error) {
    {
        err := writer.WriteStringValue("createdAt", m.GetCreatedAt())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("id", m.GetId())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("roleDesc", m.GetRoleDesc())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("roleName", m.GetRoleName())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("updatedAt", m.GetUpdatedAt())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteAdditionalData(m.GetAdditionalData())
        if err != nil {
            return err
        }
    }
    return nil
}
// SetAdditionalData sets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
func (m *GetMinimalRolesForOrgRow) SetAdditionalData(value map[string]any)() {
    m.additionalData = value
}
// SetCreatedAt sets the createdAt property value. The createdAt property
func (m *GetMinimalRolesForOrgRow) SetCreatedAt(value *string)() {
    m.createdAt = value
}
// SetId sets the id property value. The id property
func (m *GetMinimalRolesForOrgRow) SetId(value *string)() {
    m.id = value
}
// SetRoleDesc sets the roleDesc property value. The roleDesc property
func (m *GetMinimalRolesForOrgRow) SetRoleDesc(value *string)() {
    m.roleDesc = value
}
// SetRoleName sets the roleName property value. The roleName property
func (m *GetMinimalRolesForOrgRow) SetRoleName(value *string)() {
    m.roleName = value
}
// SetUpdatedAt sets the updatedAt property value. The updatedAt property
func (m *GetMinimalRolesForOrgRow) SetUpdatedAt(value *string)() {
    m.updatedAt = value
}
type GetMinimalRolesForOrgRowable interface {
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.AdditionalDataHolder
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    GetCreatedAt()(*string)
    GetId()(*string)
    GetRoleDesc()(*string)
    GetRoleName()(*string)
    GetUpdatedAt()(*string)
    SetCreatedAt(value *string)()
    SetId(value *string)()
    SetRoleDesc(value *string)()
    SetRoleName(value *string)()
    SetUpdatedAt(value *string)()
}
