// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package db

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

type OrgDomain struct {
    // Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
    additionalData map[string]any
    // The autoJoin property
    autoJoin *bool
    // The autoJoinRoleId property
    autoJoinRoleId *string
    // The autoJoinRoleName property
    autoJoinRoleName *string
    // The createdAt property
    createdAt *string
    // The domain property
    domain *string
    // The orgId property
    orgId *string
    // The updatedAt property
    updatedAt *string
    // The verified property
    verified *bool
    // The verifiedAt property
    verifiedAt *string
}
// NewOrgDomain instantiates a new OrgDomain and sets the default values.
func NewOrgDomain()(*OrgDomain) {
    m := &OrgDomain{
    }
    m.SetAdditionalData(make(map[string]any))
    return m
}
// CreateOrgDomainFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateOrgDomainFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewOrgDomain(), nil
}
// GetAdditionalData gets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
// returns a map[string]any when successful
func (m *OrgDomain) GetAdditionalData()(map[string]any) {
    return m.additionalData
}
// GetAutoJoin gets the autoJoin property value. The autoJoin property
// returns a *bool when successful
func (m *OrgDomain) GetAutoJoin()(*bool) {
    return m.autoJoin
}
// GetAutoJoinRoleId gets the autoJoinRoleId property value. The autoJoinRoleId property
// returns a *string when successful
func (m *OrgDomain) GetAutoJoinRoleId()(*string) {
    return m.autoJoinRoleId
}
// GetAutoJoinRoleName gets the autoJoinRoleName property value. The autoJoinRoleName property
// returns a *string when successful
func (m *OrgDomain) GetAutoJoinRoleName()(*string) {
    return m.autoJoinRoleName
}
// GetCreatedAt gets the createdAt property value. The createdAt property
// returns a *string when successful
func (m *OrgDomain) GetCreatedAt()(*string) {
    return m.createdAt
}
// GetDomain gets the domain property value. The domain property
// returns a *string when successful
func (m *OrgDomain) GetDomain()(*string) {
    return m.domain
}
// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error) when successful
func (m *OrgDomain) GetFieldDeserializers()(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error)) {
    res := make(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error))
    res["autoJoin"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetBoolValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetAutoJoin(val)
        }
        return nil
    }
    res["autoJoinRoleId"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetAutoJoinRoleId(val)
        }
        return nil
    }
    res["autoJoinRoleName"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetAutoJoinRoleName(val)
        }
        return nil
    }
    res["createdAt"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetCreatedAt(val)
        }
        return nil
    }
    res["domain"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetDomain(val)
        }
        return nil
    }
    res["orgId"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetOrgId(val)
        }
        return nil
    }
    res["updatedAt"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetUpdatedAt(val)
        }
        return nil
    }
    res["verified"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetBoolValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetVerified(val)
        }
        return nil
    }
    res["verifiedAt"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetVerifiedAt(val)
        }
        return nil
    }
    return res
}
// GetOrgId gets the orgId property value. The orgId property
// returns a *string when successful
func (m *OrgDomain) GetOrgId()(*string) {
    return m.orgId
}
// GetUpdatedAt gets the updatedAt property value. The updatedAt property
// returns a *string when successful
func (m *OrgDomain) GetUpdatedAt()(*string) {
    return m.updatedAt
}
// GetVerified gets the verified property value. The verified property
// returns a *bool when successful
func (m *OrgDomain) GetVerified()(*bool) {
    return m.verified
}
// GetVerifiedAt gets the verifiedAt property value. The verifiedAt property
// returns a *string when successful
func (m *OrgDomain) GetVerifiedAt()(*string) {
    return m.verifiedAt
}
// Serialize serializes information the current object
func (m *OrgDomain) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter)(error) {
    {
        err := writer.WriteBoolValue("autoJoin", m.GetAutoJoin())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("autoJoinRoleId", m.GetAutoJoinRoleId())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("autoJoinRoleName", m.GetAutoJoinRoleName())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("createdAt", m.GetCreatedAt())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("domain", m.GetDomain())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("orgId", m.GetOrgId())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("updatedAt", m.GetUpdatedAt())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteBoolValue("verified", m.GetVerified())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("verifiedAt", m.GetVerifiedAt())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteAdditionalData(m.GetAdditionalData())
        if err != nil {
            return err
        }
    }
    return nil
}
// SetAdditionalData sets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
func (m *OrgDomain) SetAdditionalData(value map[string]any)() {
    m.additionalData = value
}
// SetAutoJoin sets the autoJoin property value. The autoJoin property
func (m *OrgDomain) SetAutoJoin(value *bool)() {
    m.autoJoin = value
}
// SetAutoJoinRoleId sets the autoJoinRoleId property value. The autoJoinRoleId property
func (m *OrgDomain) SetAutoJoinRoleId(value *string)() {
    m.autoJoinRoleId = value
}
// SetAutoJoinRoleName sets the autoJoinRoleName property value. The autoJoinRoleName property
func (m *OrgDomain) SetAutoJoinRoleName(value *string)() {
    m.autoJoinRoleName = value
}
// SetCreatedAt sets the createdAt property value. The createdAt property
func (m *OrgDomain) SetCreatedAt(value *string)() {
    m.createdAt = value
}
// SetDomain sets the domain property value. The domain property
func (m *OrgDomain) SetDomain(value *string)() {
    m.domain = value
}
// SetOrgId sets the orgId property value. The orgId property
func (m *OrgDomain) SetOrgId(value *string)() {
    m.orgId = value
}
// SetUpdatedAt sets the updatedAt property value. The updatedAt property
func (m *OrgDomain) SetUpdatedAt(value *string)() {
    m.updatedAt = value
}
// SetVerified sets the verified property value. The verified property
func (m *OrgDomain) SetVerified(value *bool)() {
    m.verified = value
}
// SetVerifiedAt sets the verifiedAt property value. The verifiedAt property
func (m *OrgDomain) SetVerifiedAt(value *string)() {
    m.verifiedAt = value
}
type OrgDomainable interface {
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.AdditionalDataHolder
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    GetAutoJoin()(*bool)
    GetAutoJoinRoleId()(*string)
    GetAutoJoinRoleName()(*string)
    GetCreatedAt()(*string)
    GetDomain()(*string)
    GetOrgId()(*string)
    GetUpdatedAt()(*string)
    GetVerified()(*bool)
    GetVerifiedAt()(*string)
    SetAutoJoin(value *bool)()
    SetAutoJoinRoleId(value *string)()
    SetAutoJoinRoleName(value *string)()
    SetCreatedAt(value *string)()
    SetDomain(value *string)()
    SetOrgId(value *string)()
    SetUpdatedAt(value *string)()
    SetVerified(value *bool)()
    SetVerifiedAt(value *string)()
}
