/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createAdminDeleteDomainResponseFromDiscriminatorValue, createAdminUpdateDomainResponseFromDiscriminatorValue, createErrorResponseFromDiscriminatorValue, serializeAdminUpdateDomainRequest, serializeAdminUpdateDomainResponse, type AdminDeleteDomainResponse, type AdminUpdateDomainRequest, type AdminUpdateDomainResponse, type ErrorResponse } from '../../../../../../models/index.js';
// @ts-ignore
import { type VerifyRequestBuilder, VerifyRequestBuilderNavigationMetadata, VerifyRequestBuilderRequestsMetadata } from './verify/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/admin/orgs/{orgId}/domains/{domain}
 */
export interface WithDomainItemRequestBuilder extends BaseRequestBuilder<WithDomainItemRequestBuilder> {
    /**
     * The verify property
     */
    get verify(): VerifyRequestBuilder;
    /**
     * Deletes a domain from an organization.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<AdminDeleteDomainResponse>}
     * @throws {ErrorResponse} error when the service returns a 400 status code
     * @throws {ErrorResponse} error when the service returns a 401 status code
     * @throws {ErrorResponse} error when the service returns a 404 status code
     * @throws {ErrorResponse} error when the service returns a 500 status code
     */
     delete(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<AdminDeleteDomainResponse | undefined>;
    /**
     * Updates a domain for an organization.
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<AdminUpdateDomainResponse>}
     * @throws {ErrorResponse} error when the service returns a 400 status code
     * @throws {ErrorResponse} error when the service returns a 401 status code
     * @throws {ErrorResponse} error when the service returns a 404 status code
     * @throws {ErrorResponse} error when the service returns a 500 status code
     */
     patch(body: AdminUpdateDomainRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<AdminUpdateDomainResponse | undefined>;
    /**
     * Deletes a domain from an organization.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toDeleteRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
    /**
     * Updates a domain for an organization.
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPatchRequestInformation(body: AdminUpdateDomainRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const WithDomainItemRequestBuilderUriTemplate = "{+baseurl}/api/admin/orgs/{orgId}/domains/{domain}";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const WithDomainItemRequestBuilderNavigationMetadata: Record<Exclude<keyof WithDomainItemRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    verify: {
        requestsMetadata: VerifyRequestBuilderRequestsMetadata,
        navigationMetadata: VerifyRequestBuilderNavigationMetadata,
    },
};
/**
 * Metadata for all the requests in the request builder.
 */
export const WithDomainItemRequestBuilderRequestsMetadata: RequestsMetadata = {
    delete: {
        uriTemplate: WithDomainItemRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createErrorResponseFromDiscriminatorValue as ParsableFactory<Parsable>,
            401: createErrorResponseFromDiscriminatorValue as ParsableFactory<Parsable>,
            404: createErrorResponseFromDiscriminatorValue as ParsableFactory<Parsable>,
            500: createErrorResponseFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createAdminDeleteDomainResponseFromDiscriminatorValue,
    },
    patch: {
        uriTemplate: WithDomainItemRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createErrorResponseFromDiscriminatorValue as ParsableFactory<Parsable>,
            401: createErrorResponseFromDiscriminatorValue as ParsableFactory<Parsable>,
            404: createErrorResponseFromDiscriminatorValue as ParsableFactory<Parsable>,
            500: createErrorResponseFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createAdminUpdateDomainResponseFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeAdminUpdateDomainRequest,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
