/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { ConfigRequestBuilderRequestsMetadata, type ConfigRequestBuilder } from './config/index.js';
// @ts-ignore
import { OrgsRequestBuilderNavigationMetadata, OrgsRequestBuilderRequestsMetadata, type OrgsRequestBuilder } from './orgs/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/sys/admin
 */
export interface AdminRequestBuilder extends BaseRequestBuilder<AdminRequestBuilder> {
    /**
     * The config property
     */
    get config(): ConfigRequestBuilder;
    /**
     * The orgs property
     */
    get orgs(): OrgsRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const AdminRequestBuilderUriTemplate = "{+baseurl}/api/sys/admin";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const AdminRequestBuilderNavigationMetadata: Record<Exclude<keyof AdminRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    config: {
        requestsMetadata: ConfigRequestBuilderRequestsMetadata,
    },
    orgs: {
        requestsMetadata: OrgsRequestBuilderRequestsMetadata,
        navigationMetadata: OrgsRequestBuilderNavigationMetadata,
    },
};
/* tslint:enable */
/* eslint-enable */
