/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createErrorResponseFromDiscriminatorValue, createSysAdminCreateOrgResponseFromDiscriminatorValue, serializeSysAdminCreateOrgRequest, serializeSysAdminCreateOrgResponse, type ErrorResponse, type SysAdminCreateOrgRequest, type SysAdminCreateOrgResponse } from '../../../../models/index.js';
// @ts-ignore
import { type WithOrgItemRequestBuilder, WithOrgItemRequestBuilderRequestsMetadata } from './item/index.js';
// @ts-ignore
import { ListRequestBuilderRequestsMetadata, type ListRequestBuilder } from './list/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Guid, type KeysToExcludeForNavigationMetadata, type NavigationMetadata, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/sys/admin/orgs
 */
export interface OrgsRequestBuilder extends BaseRequestBuilder<OrgsRequestBuilder> {
    /**
     * The list property
     */
    get list(): ListRequestBuilder;
    /**
     * Gets an item from the ApiSdk.api.sys.admin.orgs.item collection
     * @param orgId Organization ID
     * @returns {WithOrgItemRequestBuilder}
     */
     byOrgId(orgId: Guid) : WithOrgItemRequestBuilder;
    /**
     * Create a new organization.
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<SysAdminCreateOrgResponse>}
     * @throws {ErrorResponse} error when the service returns a 400 status code
     * @throws {ErrorResponse} error when the service returns a 401 status code
     * @throws {ErrorResponse} error when the service returns a 500 status code
     */
     post(body: SysAdminCreateOrgRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<SysAdminCreateOrgResponse | undefined>;
    /**
     * Create a new organization.
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: SysAdminCreateOrgRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const OrgsRequestBuilderUriTemplate = "{+baseurl}/api/sys/admin/orgs";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const OrgsRequestBuilderNavigationMetadata: Record<Exclude<keyof OrgsRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    byOrgId: {
        requestsMetadata: WithOrgItemRequestBuilderRequestsMetadata,
        pathParametersMappings: ["orgId"],
    },
    list: {
        requestsMetadata: ListRequestBuilderRequestsMetadata,
    },
};
/**
 * Metadata for all the requests in the request builder.
 */
export const OrgsRequestBuilderRequestsMetadata: RequestsMetadata = {
    post: {
        uriTemplate: OrgsRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createErrorResponseFromDiscriminatorValue as ParsableFactory<Parsable>,
            401: createErrorResponseFromDiscriminatorValue as ParsableFactory<Parsable>,
            500: createErrorResponseFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createSysAdminCreateOrgResponseFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeSysAdminCreateOrgRequest,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
