/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { type Parsable, type ParseNode, type SerializationWriter } from '@microsoft/kiota-abstractions';

/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {PublicFacingBrandingConfig}
 */
// @ts-ignore
export function createPublicFacingBrandingConfigFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoPublicFacingBrandingConfig;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {PublicFacingJWTConfig}
 */
// @ts-ignore
export function createPublicFacingJWTConfigFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoPublicFacingJWTConfig;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {PublicFacingMultitenancyConfig}
 */
// @ts-ignore
export function createPublicFacingMultitenancyConfigFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoPublicFacingMultitenancyConfig;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {PublicFacingNotificationsConfig}
 */
// @ts-ignore
export function createPublicFacingNotificationsConfigFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoPublicFacingNotificationsConfig;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {PublicFacingNotificationsEmailConfigEndpoints}
 */
// @ts-ignore
export function createPublicFacingNotificationsEmailConfigEndpointsFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoPublicFacingNotificationsEmailConfigEndpoints;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {PublicFacingNotificationsEmailConfig}
 */
// @ts-ignore
export function createPublicFacingNotificationsEmailConfigFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoPublicFacingNotificationsEmailConfig;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {PublicFacingNotificationsSMSConfig}
 */
// @ts-ignore
export function createPublicFacingNotificationsSMSConfigFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoPublicFacingNotificationsSMSConfig;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {PublicFacingPublicEndpointConfig}
 */
// @ts-ignore
export function createPublicFacingPublicEndpointConfigFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoPublicFacingPublicEndpointConfig;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {PublicFacingSecurityAPIKeyConfig}
 */
// @ts-ignore
export function createPublicFacingSecurityAPIKeyConfigFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoPublicFacingSecurityAPIKeyConfig;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {PublicFacingSecurityAuditLogsConfig}
 */
// @ts-ignore
export function createPublicFacingSecurityAuditLogsConfigFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoPublicFacingSecurityAuditLogsConfig;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {PublicFacingSecurityConfig}
 */
// @ts-ignore
export function createPublicFacingSecurityConfigFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoPublicFacingSecurityConfig;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {PublicFacingSecurityRateLimitConfig}
 */
// @ts-ignore
export function createPublicFacingSecurityRateLimitConfigFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoPublicFacingSecurityRateLimitConfig;
}
/**
 * The deserialization information for the current model
 * @param PublicFacingBrandingConfig The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoPublicFacingBrandingConfig(publicFacingBrandingConfig: Partial<PublicFacingBrandingConfig> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "appName": n => { publicFacingBrandingConfig.appName = n.getStringValue(); },
        "companyName": n => { publicFacingBrandingConfig.companyName = n.getStringValue(); },
        "companyNameShort": n => { publicFacingBrandingConfig.companyNameShort = n.getStringValue(); },
        "supportURL": n => { publicFacingBrandingConfig.supportURL = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param PublicFacingJWTConfig The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoPublicFacingJWTConfig(publicFacingJWTConfig: Partial<PublicFacingJWTConfig> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "refreshTokenExpirySeconds": n => { publicFacingJWTConfig.refreshTokenExpirySeconds = n.getNumberValue(); },
        "sessionTokenExpirySeconds": n => { publicFacingJWTConfig.sessionTokenExpirySeconds = n.getNumberValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param PublicFacingMultitenancyConfig The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoPublicFacingMultitenancyConfig(publicFacingMultitenancyConfig: Partial<PublicFacingMultitenancyConfig> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "enabled": n => { publicFacingMultitenancyConfig.enabled = n.getBooleanValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param PublicFacingNotificationsConfig The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoPublicFacingNotificationsConfig(publicFacingNotificationsConfig: Partial<PublicFacingNotificationsConfig> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "email": n => { publicFacingNotificationsConfig.email = n.getObjectValue<PublicFacingNotificationsEmailConfig>(createPublicFacingNotificationsEmailConfigFromDiscriminatorValue); },
        "sms": n => { publicFacingNotificationsConfig.sms = n.getObjectValue<PublicFacingNotificationsSMSConfig>(createPublicFacingNotificationsSMSConfigFromDiscriminatorValue); },
    }
}
/**
 * The deserialization information for the current model
 * @param PublicFacingNotificationsEmailConfig The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoPublicFacingNotificationsEmailConfig(publicFacingNotificationsEmailConfig: Partial<PublicFacingNotificationsEmailConfig> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "endpoints": n => { publicFacingNotificationsEmailConfig.endpoints = n.getObjectValue<PublicFacingNotificationsEmailConfigEndpoints>(createPublicFacingNotificationsEmailConfigEndpointsFromDiscriminatorValue); },
        "provider": n => { publicFacingNotificationsEmailConfig.provider = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param PublicFacingNotificationsEmailConfigEndpoints The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoPublicFacingNotificationsEmailConfigEndpoints(publicFacingNotificationsEmailConfigEndpoints: Partial<PublicFacingNotificationsEmailConfigEndpoints> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "passwordReset": n => { publicFacingNotificationsEmailConfigEndpoints.passwordReset = n.getStringValue(); },
        "verification": n => { publicFacingNotificationsEmailConfigEndpoints.verification = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param PublicFacingNotificationsSMSConfig The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoPublicFacingNotificationsSMSConfig(publicFacingNotificationsSMSConfig: Partial<PublicFacingNotificationsSMSConfig> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "provider": n => { publicFacingNotificationsSMSConfig.provider = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param PublicFacingPublicEndpointConfig The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoPublicFacingPublicEndpointConfig(publicFacingPublicEndpointConfig: Partial<PublicFacingPublicEndpointConfig> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "debugBaseURL": n => { publicFacingPublicEndpointConfig.debugBaseURL = n.getStringValue(); },
        "domain": n => { publicFacingPublicEndpointConfig.domain = n.getStringValue(); },
        "scheme": n => { publicFacingPublicEndpointConfig.scheme = n.getStringValue(); },
        "subdomain": n => { publicFacingPublicEndpointConfig.subdomain = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param PublicFacingSecurityAPIKeyConfig The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoPublicFacingSecurityAPIKeyConfig(publicFacingSecurityAPIKeyConfig: Partial<PublicFacingSecurityAPIKeyConfig> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "description": n => { publicFacingSecurityAPIKeyConfig.description = n.getStringValue(); },
        "name": n => { publicFacingSecurityAPIKeyConfig.name = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param PublicFacingSecurityAuditLogsConfig The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoPublicFacingSecurityAuditLogsConfig(publicFacingSecurityAuditLogsConfig: Partial<PublicFacingSecurityAuditLogsConfig> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "enabled": n => { publicFacingSecurityAuditLogsConfig.enabled = n.getBooleanValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param PublicFacingSecurityConfig The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoPublicFacingSecurityConfig(publicFacingSecurityConfig: Partial<PublicFacingSecurityConfig> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "apiKeys": n => { publicFacingSecurityConfig.apiKeys = n.getCollectionOfObjectValues<PublicFacingSecurityAPIKeyConfig>(createPublicFacingSecurityAPIKeyConfigFromDiscriminatorValue); },
        "auditLogs": n => { publicFacingSecurityConfig.auditLogs = n.getObjectValue<PublicFacingSecurityAuditLogsConfig>(createPublicFacingSecurityAuditLogsConfigFromDiscriminatorValue); },
        "rateLimit": n => { publicFacingSecurityConfig.rateLimit = n.getObjectValue<PublicFacingSecurityRateLimitConfig>(createPublicFacingSecurityRateLimitConfigFromDiscriminatorValue); },
    }
}
/**
 * The deserialization information for the current model
 * @param PublicFacingSecurityRateLimitConfig The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoPublicFacingSecurityRateLimitConfig(publicFacingSecurityRateLimitConfig: Partial<PublicFacingSecurityRateLimitConfig> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "enabled": n => { publicFacingSecurityRateLimitConfig.enabled = n.getBooleanValue(); },
        "rate": n => { publicFacingSecurityRateLimitConfig.rate = n.getStringValue(); },
    }
}
/**
 * Branding configuration for the public-facing Nexeres system.
 */
export interface PublicFacingBrandingConfig extends Parsable {
    /**
     * Name of the application.
     */
    appName?: string | null;
    /**
     * Name of the company.
     */
    companyName?: string | null;
    /**
     * Short name of the company.
     */
    companyNameShort?: string | null;
    /**
     * URL for support.
     */
    supportURL?: string | null;
}
/**
 * JWT configuration for the Nexeres system.
 */
export interface PublicFacingJWTConfig extends Parsable {
    /**
     * The number of seconds in which an issued refresh token expires.
     */
    refreshTokenExpirySeconds?: number | null;
    /**
     * The number of seconds in which an issued session token/session expires.
     */
    sessionTokenExpirySeconds?: number | null;
}
/**
 * Multitenancy configuration for the public-facing Nexeres system.
 */
export interface PublicFacingMultitenancyConfig extends Parsable {
    /**
     * Indicates if multitenancy is enabled.
     */
    enabled?: boolean | null;
}
/**
 * Notifications configuration for the Nexeres system.
 */
export interface PublicFacingNotificationsConfig extends Parsable {
    /**
     * Email notifications configuration for the Nexeres system.
     */
    email?: PublicFacingNotificationsEmailConfig | null;
    /**
     * SMS notifications configuration for the Nexeres system.
     */
    sms?: PublicFacingNotificationsSMSConfig | null;
}
/**
 * Email notifications configuration for the Nexeres system.
 */
export interface PublicFacingNotificationsEmailConfig extends Parsable {
    /**
     * Endpoints configuration for email notifications.
     */
    endpoints?: PublicFacingNotificationsEmailConfigEndpoints | null;
    /**
     * Email service provider name.
     */
    provider?: string | null;
}
/**
 * Endpoints configuration for email notifications.
 */
export interface PublicFacingNotificationsEmailConfigEndpoints extends Parsable {
    /**
     * Your app's UI Endpoint URL to be included in the password reset emails.
     */
    passwordReset?: string | null;
    /**
     * Your app's UI Endpoint URL to be included in the email verification messages.
     */
    verification?: string | null;
}
/**
 * SMS notifications configuration for the Nexeres system.
 */
export interface PublicFacingNotificationsSMSConfig extends Parsable {
    /**
     * SMS service provider name.
     */
    provider?: string | null;
}
/**
 * Public endpoint configuration for the Nexeres system.
 */
export interface PublicFacingPublicEndpointConfig extends Parsable {
    /**
     * Base URL used for debugging purposes.
     */
    debugBaseURL?: string | null;
    /**
     * Domain name for the public endpoint.
     */
    domain?: string | null;
    /**
     * URL scheme (e.g., http, https) for the public endpoint.
     */
    scheme?: string | null;
    /**
     * Subdomain for the public endpoint.
     */
    subdomain?: string | null;
}
/**
 * API key configuration for the Nexeres system.
 */
export interface PublicFacingSecurityAPIKeyConfig extends Parsable {
    /**
     * The description of the API Key.
     */
    description?: string | null;
    /**
     * Name of the API key.
     */
    name?: string | null;
}
/**
 * Audit logs configuration for the Nexeres system.
 */
export interface PublicFacingSecurityAuditLogsConfig extends Parsable {
    /**
     * Indicates if audit logging is enabled.
     */
    enabled?: boolean | null;
}
/**
 * Security configuration for the Nexeres system.
 */
export interface PublicFacingSecurityConfig extends Parsable {
    /**
     * The apiKeys property
     */
    apiKeys?: PublicFacingSecurityAPIKeyConfig[] | null;
    /**
     * Audit logs configuration for the Nexeres system.
     */
    auditLogs?: PublicFacingSecurityAuditLogsConfig | null;
    /**
     * Rate limiting configuration for the Nexeres system.
     */
    rateLimit?: PublicFacingSecurityRateLimitConfig | null;
}
/**
 * Rate limiting configuration for the Nexeres system.
 */
export interface PublicFacingSecurityRateLimitConfig extends Parsable {
    /**
     * Indicates if rate limiting is enabled.
     */
    enabled?: boolean | null;
    /**
     * Rate in the format of "r-u", where r is the number of requests and u is the time unit (e.g., "100-S" for 100 requests per second).
     */
    rate?: string | null;
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param PublicFacingBrandingConfig The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializePublicFacingBrandingConfig(writer: SerializationWriter, publicFacingBrandingConfig: Partial<PublicFacingBrandingConfig> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!publicFacingBrandingConfig || isSerializingDerivedType) { return; }
    writer.writeStringValue("appName", publicFacingBrandingConfig.appName);
    writer.writeStringValue("companyName", publicFacingBrandingConfig.companyName);
    writer.writeStringValue("companyNameShort", publicFacingBrandingConfig.companyNameShort);
    writer.writeStringValue("supportURL", publicFacingBrandingConfig.supportURL);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param PublicFacingJWTConfig The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializePublicFacingJWTConfig(writer: SerializationWriter, publicFacingJWTConfig: Partial<PublicFacingJWTConfig> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!publicFacingJWTConfig || isSerializingDerivedType) { return; }
    writer.writeNumberValue("refreshTokenExpirySeconds", publicFacingJWTConfig.refreshTokenExpirySeconds);
    writer.writeNumberValue("sessionTokenExpirySeconds", publicFacingJWTConfig.sessionTokenExpirySeconds);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param PublicFacingMultitenancyConfig The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializePublicFacingMultitenancyConfig(writer: SerializationWriter, publicFacingMultitenancyConfig: Partial<PublicFacingMultitenancyConfig> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!publicFacingMultitenancyConfig || isSerializingDerivedType) { return; }
    writer.writeBooleanValue("enabled", publicFacingMultitenancyConfig.enabled);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param PublicFacingNotificationsConfig The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializePublicFacingNotificationsConfig(writer: SerializationWriter, publicFacingNotificationsConfig: Partial<PublicFacingNotificationsConfig> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!publicFacingNotificationsConfig || isSerializingDerivedType) { return; }
    writer.writeObjectValue<PublicFacingNotificationsEmailConfig>("email", publicFacingNotificationsConfig.email, serializePublicFacingNotificationsEmailConfig);
    writer.writeObjectValue<PublicFacingNotificationsSMSConfig>("sms", publicFacingNotificationsConfig.sms, serializePublicFacingNotificationsSMSConfig);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param PublicFacingNotificationsEmailConfig The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializePublicFacingNotificationsEmailConfig(writer: SerializationWriter, publicFacingNotificationsEmailConfig: Partial<PublicFacingNotificationsEmailConfig> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!publicFacingNotificationsEmailConfig || isSerializingDerivedType) { return; }
    writer.writeObjectValue<PublicFacingNotificationsEmailConfigEndpoints>("endpoints", publicFacingNotificationsEmailConfig.endpoints, serializePublicFacingNotificationsEmailConfigEndpoints);
    writer.writeStringValue("provider", publicFacingNotificationsEmailConfig.provider);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param PublicFacingNotificationsEmailConfigEndpoints The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializePublicFacingNotificationsEmailConfigEndpoints(writer: SerializationWriter, publicFacingNotificationsEmailConfigEndpoints: Partial<PublicFacingNotificationsEmailConfigEndpoints> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!publicFacingNotificationsEmailConfigEndpoints || isSerializingDerivedType) { return; }
    writer.writeStringValue("passwordReset", publicFacingNotificationsEmailConfigEndpoints.passwordReset);
    writer.writeStringValue("verification", publicFacingNotificationsEmailConfigEndpoints.verification);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param PublicFacingNotificationsSMSConfig The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializePublicFacingNotificationsSMSConfig(writer: SerializationWriter, publicFacingNotificationsSMSConfig: Partial<PublicFacingNotificationsSMSConfig> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!publicFacingNotificationsSMSConfig || isSerializingDerivedType) { return; }
    writer.writeStringValue("provider", publicFacingNotificationsSMSConfig.provider);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param PublicFacingPublicEndpointConfig The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializePublicFacingPublicEndpointConfig(writer: SerializationWriter, publicFacingPublicEndpointConfig: Partial<PublicFacingPublicEndpointConfig> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!publicFacingPublicEndpointConfig || isSerializingDerivedType) { return; }
    writer.writeStringValue("debugBaseURL", publicFacingPublicEndpointConfig.debugBaseURL);
    writer.writeStringValue("domain", publicFacingPublicEndpointConfig.domain);
    writer.writeStringValue("scheme", publicFacingPublicEndpointConfig.scheme);
    writer.writeStringValue("subdomain", publicFacingPublicEndpointConfig.subdomain);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param PublicFacingSecurityAPIKeyConfig The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializePublicFacingSecurityAPIKeyConfig(writer: SerializationWriter, publicFacingSecurityAPIKeyConfig: Partial<PublicFacingSecurityAPIKeyConfig> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!publicFacingSecurityAPIKeyConfig || isSerializingDerivedType) { return; }
    writer.writeStringValue("description", publicFacingSecurityAPIKeyConfig.description);
    writer.writeStringValue("name", publicFacingSecurityAPIKeyConfig.name);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param PublicFacingSecurityAuditLogsConfig The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializePublicFacingSecurityAuditLogsConfig(writer: SerializationWriter, publicFacingSecurityAuditLogsConfig: Partial<PublicFacingSecurityAuditLogsConfig> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!publicFacingSecurityAuditLogsConfig || isSerializingDerivedType) { return; }
    writer.writeBooleanValue("enabled", publicFacingSecurityAuditLogsConfig.enabled);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param PublicFacingSecurityConfig The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializePublicFacingSecurityConfig(writer: SerializationWriter, publicFacingSecurityConfig: Partial<PublicFacingSecurityConfig> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!publicFacingSecurityConfig || isSerializingDerivedType) { return; }
    writer.writeCollectionOfObjectValues<PublicFacingSecurityAPIKeyConfig>("apiKeys", publicFacingSecurityConfig.apiKeys, serializePublicFacingSecurityAPIKeyConfig);
    writer.writeObjectValue<PublicFacingSecurityAuditLogsConfig>("auditLogs", publicFacingSecurityConfig.auditLogs, serializePublicFacingSecurityAuditLogsConfig);
    writer.writeObjectValue<PublicFacingSecurityRateLimitConfig>("rateLimit", publicFacingSecurityConfig.rateLimit, serializePublicFacingSecurityRateLimitConfig);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param PublicFacingSecurityRateLimitConfig The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializePublicFacingSecurityRateLimitConfig(writer: SerializationWriter, publicFacingSecurityRateLimitConfig: Partial<PublicFacingSecurityRateLimitConfig> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!publicFacingSecurityRateLimitConfig || isSerializingDerivedType) { return; }
    writer.writeBooleanValue("enabled", publicFacingSecurityRateLimitConfig.enabled);
    writer.writeStringValue("rate", publicFacingSecurityRateLimitConfig.rate);
}
/* tslint:enable */
/* eslint-enable */
