/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createOrgDomainFromDiscriminatorValue, createRoleFromDiscriminatorValue, serializeOrgDomain, serializeRole, type OrgDomain, type Role } from '../db/index.js';
// @ts-ignore
import { createOrgSettingsFromDiscriminatorValue, serializeOrgSettings, type OrgSettings } from '../models/index.js';
// @ts-ignore
import { type AdditionalDataHolder, type Parsable, type ParseNode, type SerializationWriter } from '@microsoft/kiota-abstractions';

export interface AdminCreateDomainRequest extends AdditionalDataHolder, Parsable {
    /**
     * The autoJoin property
     */
    autoJoin?: boolean | null;
    /**
     * The autoJoinRoleId property
     */
    autoJoinRoleId?: string | null;
    /**
     * The autoJoinRoleName property
     */
    autoJoinRoleName?: string | null;
    /**
     * The domain property
     */
    domain?: string | null;
}
export interface AdminCreateDomainResponse extends AdditionalDataHolder, Parsable {
    /**
     * The domain property
     */
    domain?: OrgDomain | null;
    /**
     * The message property
     */
    message?: string | null;
    /**
     * The success property
     */
    success?: boolean | null;
}
export interface AdminCreateRoleRequest extends AdditionalDataHolder, Parsable {
    /**
     * The description property
     */
    description?: string | null;
    /**
     * The name property
     */
    name?: string | null;
    /**
     * The permissions property
     */
    permissions?: string[] | null;
}
export interface AdminCreateRoleResponse extends AdditionalDataHolder, Parsable {
    /**
     * The message property
     */
    message?: string | null;
    /**
     * The role property
     */
    role?: Role | null;
    /**
     * The success property
     */
    success?: boolean | null;
}
export interface AdminDeleteDomainResponse extends AdditionalDataHolder, Parsable {
    /**
     * The message property
     */
    message?: string | null;
    /**
     * The success property
     */
    success?: boolean | null;
}
export interface AdminDeleteRoleResponse extends AdditionalDataHolder, Parsable {
    /**
     * The message property
     */
    message?: string | null;
    /**
     * The success property
     */
    success?: boolean | null;
}
export interface AdminGetDomainVerifyCodeResponse extends AdditionalDataHolder, Parsable {
    /**
     * The code property
     */
    code?: string | null;
    /**
     * The message property
     */
    message?: string | null;
    /**
     * The success property
     */
    success?: boolean | null;
}
export interface AdminUpdateDomainRequest extends AdditionalDataHolder, Parsable {
    /**
     * The autoJoin property
     */
    autoJoin?: boolean | null;
    /**
     * The autoJoinRoleId property
     */
    autoJoinRoleId?: string | null;
    /**
     * The autoJoinRoleName property
     */
    autoJoinRoleName?: string | null;
}
export interface AdminUpdateDomainResponse extends AdditionalDataHolder, Parsable {
    /**
     * The domain property
     */
    domain?: OrgDomain | null;
    /**
     * The message property
     */
    message?: string | null;
    /**
     * The success property
     */
    success?: boolean | null;
}
export interface AdminUpdateOrgRequest extends AdditionalDataHolder, Parsable {
    /**
     * The description property
     */
    description?: string | null;
    /**
     * The name property
     */
    name?: string | null;
    /**
     * The settings property
     */
    settings?: OrgSettings | null;
}
export interface AdminUpdateOrgResponse extends AdditionalDataHolder, Parsable {
    /**
     * The message property
     */
    message?: string | null;
    /**
     * The success property
     */
    success?: boolean | null;
}
export interface AdminUpdateRoleRequest extends AdditionalDataHolder, Parsable {
    /**
     * The description property
     */
    description?: string | null;
    /**
     * The name property
     */
    name?: string | null;
    /**
     * The permissions property
     */
    permissions?: string[] | null;
}
export interface AdminUpdateRoleResponse extends AdditionalDataHolder, Parsable {
    /**
     * The message property
     */
    message?: string | null;
    /**
     * The success property
     */
    success?: boolean | null;
}
export interface AdminVerifyDomainResponse extends AdditionalDataHolder, Parsable {
    /**
     * The message property
     */
    message?: string | null;
    /**
     * The success property
     */
    success?: boolean | null;
    /**
     * The verified property
     */
    verified?: boolean | null;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {AdminCreateDomainRequest}
 */
// @ts-ignore
export function createAdminCreateDomainRequestFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoAdminCreateDomainRequest;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {AdminCreateDomainResponse}
 */
// @ts-ignore
export function createAdminCreateDomainResponseFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoAdminCreateDomainResponse;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {AdminCreateRoleRequest}
 */
// @ts-ignore
export function createAdminCreateRoleRequestFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoAdminCreateRoleRequest;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {AdminCreateRoleResponse}
 */
// @ts-ignore
export function createAdminCreateRoleResponseFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoAdminCreateRoleResponse;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {AdminDeleteDomainResponse}
 */
// @ts-ignore
export function createAdminDeleteDomainResponseFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoAdminDeleteDomainResponse;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {AdminDeleteRoleResponse}
 */
// @ts-ignore
export function createAdminDeleteRoleResponseFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoAdminDeleteRoleResponse;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {AdminGetDomainVerifyCodeResponse}
 */
// @ts-ignore
export function createAdminGetDomainVerifyCodeResponseFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoAdminGetDomainVerifyCodeResponse;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {AdminUpdateDomainRequest}
 */
// @ts-ignore
export function createAdminUpdateDomainRequestFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoAdminUpdateDomainRequest;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {AdminUpdateDomainResponse}
 */
// @ts-ignore
export function createAdminUpdateDomainResponseFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoAdminUpdateDomainResponse;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {AdminUpdateOrgRequest}
 */
// @ts-ignore
export function createAdminUpdateOrgRequestFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoAdminUpdateOrgRequest;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {AdminUpdateOrgResponse}
 */
// @ts-ignore
export function createAdminUpdateOrgResponseFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoAdminUpdateOrgResponse;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {AdminUpdateRoleRequest}
 */
// @ts-ignore
export function createAdminUpdateRoleRequestFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoAdminUpdateRoleRequest;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {AdminUpdateRoleResponse}
 */
// @ts-ignore
export function createAdminUpdateRoleResponseFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoAdminUpdateRoleResponse;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {AdminVerifyDomainResponse}
 */
// @ts-ignore
export function createAdminVerifyDomainResponseFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoAdminVerifyDomainResponse;
}
/**
 * The deserialization information for the current model
 * @param AdminCreateDomainRequest The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoAdminCreateDomainRequest(adminCreateDomainRequest: Partial<AdminCreateDomainRequest> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "autoJoin": n => { adminCreateDomainRequest.autoJoin = n.getBooleanValue(); },
        "autoJoinRoleId": n => { adminCreateDomainRequest.autoJoinRoleId = n.getStringValue(); },
        "autoJoinRoleName": n => { adminCreateDomainRequest.autoJoinRoleName = n.getStringValue(); },
        "domain": n => { adminCreateDomainRequest.domain = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param AdminCreateDomainResponse The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoAdminCreateDomainResponse(adminCreateDomainResponse: Partial<AdminCreateDomainResponse> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "domain": n => { adminCreateDomainResponse.domain = n.getObjectValue<OrgDomain>(createOrgDomainFromDiscriminatorValue); },
        "message": n => { adminCreateDomainResponse.message = n.getStringValue(); },
        "success": n => { adminCreateDomainResponse.success = n.getBooleanValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param AdminCreateRoleRequest The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoAdminCreateRoleRequest(adminCreateRoleRequest: Partial<AdminCreateRoleRequest> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "description": n => { adminCreateRoleRequest.description = n.getStringValue(); },
        "name": n => { adminCreateRoleRequest.name = n.getStringValue(); },
        "permissions": n => { adminCreateRoleRequest.permissions = n.getCollectionOfPrimitiveValues<string>(); },
    }
}
/**
 * The deserialization information for the current model
 * @param AdminCreateRoleResponse The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoAdminCreateRoleResponse(adminCreateRoleResponse: Partial<AdminCreateRoleResponse> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "message": n => { adminCreateRoleResponse.message = n.getStringValue(); },
        "role": n => { adminCreateRoleResponse.role = n.getObjectValue<Role>(createRoleFromDiscriminatorValue); },
        "success": n => { adminCreateRoleResponse.success = n.getBooleanValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param AdminDeleteDomainResponse The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoAdminDeleteDomainResponse(adminDeleteDomainResponse: Partial<AdminDeleteDomainResponse> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "message": n => { adminDeleteDomainResponse.message = n.getStringValue(); },
        "success": n => { adminDeleteDomainResponse.success = n.getBooleanValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param AdminDeleteRoleResponse The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoAdminDeleteRoleResponse(adminDeleteRoleResponse: Partial<AdminDeleteRoleResponse> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "message": n => { adminDeleteRoleResponse.message = n.getStringValue(); },
        "success": n => { adminDeleteRoleResponse.success = n.getBooleanValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param AdminGetDomainVerifyCodeResponse The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoAdminGetDomainVerifyCodeResponse(adminGetDomainVerifyCodeResponse: Partial<AdminGetDomainVerifyCodeResponse> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "code": n => { adminGetDomainVerifyCodeResponse.code = n.getStringValue(); },
        "message": n => { adminGetDomainVerifyCodeResponse.message = n.getStringValue(); },
        "success": n => { adminGetDomainVerifyCodeResponse.success = n.getBooleanValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param AdminUpdateDomainRequest The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoAdminUpdateDomainRequest(adminUpdateDomainRequest: Partial<AdminUpdateDomainRequest> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "autoJoin": n => { adminUpdateDomainRequest.autoJoin = n.getBooleanValue(); },
        "autoJoinRoleId": n => { adminUpdateDomainRequest.autoJoinRoleId = n.getStringValue(); },
        "autoJoinRoleName": n => { adminUpdateDomainRequest.autoJoinRoleName = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param AdminUpdateDomainResponse The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoAdminUpdateDomainResponse(adminUpdateDomainResponse: Partial<AdminUpdateDomainResponse> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "domain": n => { adminUpdateDomainResponse.domain = n.getObjectValue<OrgDomain>(createOrgDomainFromDiscriminatorValue); },
        "message": n => { adminUpdateDomainResponse.message = n.getStringValue(); },
        "success": n => { adminUpdateDomainResponse.success = n.getBooleanValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param AdminUpdateOrgRequest The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoAdminUpdateOrgRequest(adminUpdateOrgRequest: Partial<AdminUpdateOrgRequest> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "description": n => { adminUpdateOrgRequest.description = n.getStringValue(); },
        "name": n => { adminUpdateOrgRequest.name = n.getStringValue(); },
        "settings": n => { adminUpdateOrgRequest.settings = n.getObjectValue<OrgSettings>(createOrgSettingsFromDiscriminatorValue); },
    }
}
/**
 * The deserialization information for the current model
 * @param AdminUpdateOrgResponse The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoAdminUpdateOrgResponse(adminUpdateOrgResponse: Partial<AdminUpdateOrgResponse> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "message": n => { adminUpdateOrgResponse.message = n.getStringValue(); },
        "success": n => { adminUpdateOrgResponse.success = n.getBooleanValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param AdminUpdateRoleRequest The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoAdminUpdateRoleRequest(adminUpdateRoleRequest: Partial<AdminUpdateRoleRequest> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "description": n => { adminUpdateRoleRequest.description = n.getStringValue(); },
        "name": n => { adminUpdateRoleRequest.name = n.getStringValue(); },
        "permissions": n => { adminUpdateRoleRequest.permissions = n.getCollectionOfPrimitiveValues<string>(); },
    }
}
/**
 * The deserialization information for the current model
 * @param AdminUpdateRoleResponse The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoAdminUpdateRoleResponse(adminUpdateRoleResponse: Partial<AdminUpdateRoleResponse> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "message": n => { adminUpdateRoleResponse.message = n.getStringValue(); },
        "success": n => { adminUpdateRoleResponse.success = n.getBooleanValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param AdminVerifyDomainResponse The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoAdminVerifyDomainResponse(adminVerifyDomainResponse: Partial<AdminVerifyDomainResponse> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "message": n => { adminVerifyDomainResponse.message = n.getStringValue(); },
        "success": n => { adminVerifyDomainResponse.success = n.getBooleanValue(); },
        "verified": n => { adminVerifyDomainResponse.verified = n.getBooleanValue(); },
    }
}
/**
 * Serializes information the current object
 * @param AdminCreateDomainRequest The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeAdminCreateDomainRequest(writer: SerializationWriter, adminCreateDomainRequest: Partial<AdminCreateDomainRequest> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!adminCreateDomainRequest || isSerializingDerivedType) { return; }
    writer.writeBooleanValue("autoJoin", adminCreateDomainRequest.autoJoin);
    writer.writeStringValue("autoJoinRoleId", adminCreateDomainRequest.autoJoinRoleId);
    writer.writeStringValue("autoJoinRoleName", adminCreateDomainRequest.autoJoinRoleName);
    writer.writeStringValue("domain", adminCreateDomainRequest.domain);
    writer.writeAdditionalData(adminCreateDomainRequest.additionalData);
}
/**
 * Serializes information the current object
 * @param AdminCreateDomainResponse The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeAdminCreateDomainResponse(writer: SerializationWriter, adminCreateDomainResponse: Partial<AdminCreateDomainResponse> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!adminCreateDomainResponse || isSerializingDerivedType) { return; }
    writer.writeObjectValue<OrgDomain>("domain", adminCreateDomainResponse.domain, serializeOrgDomain);
    writer.writeStringValue("message", adminCreateDomainResponse.message);
    writer.writeBooleanValue("success", adminCreateDomainResponse.success);
    writer.writeAdditionalData(adminCreateDomainResponse.additionalData);
}
/**
 * Serializes information the current object
 * @param AdminCreateRoleRequest The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeAdminCreateRoleRequest(writer: SerializationWriter, adminCreateRoleRequest: Partial<AdminCreateRoleRequest> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!adminCreateRoleRequest || isSerializingDerivedType) { return; }
    writer.writeStringValue("description", adminCreateRoleRequest.description);
    writer.writeStringValue("name", adminCreateRoleRequest.name);
    writer.writeCollectionOfPrimitiveValues<string>("permissions", adminCreateRoleRequest.permissions);
    writer.writeAdditionalData(adminCreateRoleRequest.additionalData);
}
/**
 * Serializes information the current object
 * @param AdminCreateRoleResponse The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeAdminCreateRoleResponse(writer: SerializationWriter, adminCreateRoleResponse: Partial<AdminCreateRoleResponse> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!adminCreateRoleResponse || isSerializingDerivedType) { return; }
    writer.writeStringValue("message", adminCreateRoleResponse.message);
    writer.writeObjectValue<Role>("role", adminCreateRoleResponse.role, serializeRole);
    writer.writeBooleanValue("success", adminCreateRoleResponse.success);
    writer.writeAdditionalData(adminCreateRoleResponse.additionalData);
}
/**
 * Serializes information the current object
 * @param AdminDeleteDomainResponse The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeAdminDeleteDomainResponse(writer: SerializationWriter, adminDeleteDomainResponse: Partial<AdminDeleteDomainResponse> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!adminDeleteDomainResponse || isSerializingDerivedType) { return; }
    writer.writeStringValue("message", adminDeleteDomainResponse.message);
    writer.writeBooleanValue("success", adminDeleteDomainResponse.success);
    writer.writeAdditionalData(adminDeleteDomainResponse.additionalData);
}
/**
 * Serializes information the current object
 * @param AdminDeleteRoleResponse The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeAdminDeleteRoleResponse(writer: SerializationWriter, adminDeleteRoleResponse: Partial<AdminDeleteRoleResponse> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!adminDeleteRoleResponse || isSerializingDerivedType) { return; }
    writer.writeStringValue("message", adminDeleteRoleResponse.message);
    writer.writeBooleanValue("success", adminDeleteRoleResponse.success);
    writer.writeAdditionalData(adminDeleteRoleResponse.additionalData);
}
/**
 * Serializes information the current object
 * @param AdminGetDomainVerifyCodeResponse The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeAdminGetDomainVerifyCodeResponse(writer: SerializationWriter, adminGetDomainVerifyCodeResponse: Partial<AdminGetDomainVerifyCodeResponse> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!adminGetDomainVerifyCodeResponse || isSerializingDerivedType) { return; }
    writer.writeStringValue("code", adminGetDomainVerifyCodeResponse.code);
    writer.writeStringValue("message", adminGetDomainVerifyCodeResponse.message);
    writer.writeBooleanValue("success", adminGetDomainVerifyCodeResponse.success);
    writer.writeAdditionalData(adminGetDomainVerifyCodeResponse.additionalData);
}
/**
 * Serializes information the current object
 * @param AdminUpdateDomainRequest The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeAdminUpdateDomainRequest(writer: SerializationWriter, adminUpdateDomainRequest: Partial<AdminUpdateDomainRequest> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!adminUpdateDomainRequest || isSerializingDerivedType) { return; }
    writer.writeBooleanValue("autoJoin", adminUpdateDomainRequest.autoJoin);
    writer.writeStringValue("autoJoinRoleId", adminUpdateDomainRequest.autoJoinRoleId);
    writer.writeStringValue("autoJoinRoleName", adminUpdateDomainRequest.autoJoinRoleName);
    writer.writeAdditionalData(adminUpdateDomainRequest.additionalData);
}
/**
 * Serializes information the current object
 * @param AdminUpdateDomainResponse The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeAdminUpdateDomainResponse(writer: SerializationWriter, adminUpdateDomainResponse: Partial<AdminUpdateDomainResponse> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!adminUpdateDomainResponse || isSerializingDerivedType) { return; }
    writer.writeObjectValue<OrgDomain>("domain", adminUpdateDomainResponse.domain, serializeOrgDomain);
    writer.writeStringValue("message", adminUpdateDomainResponse.message);
    writer.writeBooleanValue("success", adminUpdateDomainResponse.success);
    writer.writeAdditionalData(adminUpdateDomainResponse.additionalData);
}
/**
 * Serializes information the current object
 * @param AdminUpdateOrgRequest The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeAdminUpdateOrgRequest(writer: SerializationWriter, adminUpdateOrgRequest: Partial<AdminUpdateOrgRequest> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!adminUpdateOrgRequest || isSerializingDerivedType) { return; }
    writer.writeStringValue("description", adminUpdateOrgRequest.description);
    writer.writeStringValue("name", adminUpdateOrgRequest.name);
    writer.writeObjectValue<OrgSettings>("settings", adminUpdateOrgRequest.settings, serializeOrgSettings);
    writer.writeAdditionalData(adminUpdateOrgRequest.additionalData);
}
/**
 * Serializes information the current object
 * @param AdminUpdateOrgResponse The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeAdminUpdateOrgResponse(writer: SerializationWriter, adminUpdateOrgResponse: Partial<AdminUpdateOrgResponse> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!adminUpdateOrgResponse || isSerializingDerivedType) { return; }
    writer.writeStringValue("message", adminUpdateOrgResponse.message);
    writer.writeBooleanValue("success", adminUpdateOrgResponse.success);
    writer.writeAdditionalData(adminUpdateOrgResponse.additionalData);
}
/**
 * Serializes information the current object
 * @param AdminUpdateRoleRequest The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeAdminUpdateRoleRequest(writer: SerializationWriter, adminUpdateRoleRequest: Partial<AdminUpdateRoleRequest> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!adminUpdateRoleRequest || isSerializingDerivedType) { return; }
    writer.writeStringValue("description", adminUpdateRoleRequest.description);
    writer.writeStringValue("name", adminUpdateRoleRequest.name);
    writer.writeCollectionOfPrimitiveValues<string>("permissions", adminUpdateRoleRequest.permissions);
    writer.writeAdditionalData(adminUpdateRoleRequest.additionalData);
}
/**
 * Serializes information the current object
 * @param AdminUpdateRoleResponse The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeAdminUpdateRoleResponse(writer: SerializationWriter, adminUpdateRoleResponse: Partial<AdminUpdateRoleResponse> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!adminUpdateRoleResponse || isSerializingDerivedType) { return; }
    writer.writeStringValue("message", adminUpdateRoleResponse.message);
    writer.writeBooleanValue("success", adminUpdateRoleResponse.success);
    writer.writeAdditionalData(adminUpdateRoleResponse.additionalData);
}
/**
 * Serializes information the current object
 * @param AdminVerifyDomainResponse The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeAdminVerifyDomainResponse(writer: SerializationWriter, adminVerifyDomainResponse: Partial<AdminVerifyDomainResponse> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!adminVerifyDomainResponse || isSerializingDerivedType) { return; }
    writer.writeStringValue("message", adminVerifyDomainResponse.message);
    writer.writeBooleanValue("success", adminVerifyDomainResponse.success);
    writer.writeBooleanValue("verified", adminVerifyDomainResponse.verified);
    writer.writeAdditionalData(adminVerifyDomainResponse.additionalData);
}
/* tslint:enable */
/* eslint-enable */
